package com.mirkori.inplacex.platform.localization

internal object GameCatalog {
    val ru = localizationCatalog(
        name = "game.ru",
        entries = listOf(
            localizationEntry("game.status.default", "Введите комбинацию или отметьте таблицу"),
            localizationEntry("game.status.time_over", "Время вышло"),
            localizationEntry("game.status.no_hints", "Подсказки этого типа закончились"),
            localizationEntry("game.status.watch_ad_for_hint", "Можно посмотреть рекламу и получить бонусную подсказку"),
            localizationEntry("game.status.select_table_cell", "Выберите клетку таблицы для проверки позиции"),
            localizationEntry("game.status.select_slot", "Выберите слот в комбинации, чтобы открыть позицию"),
            localizationEntry("game.status.select_digit", "Выберите цифру на клавиатуре ввода"),
            localizationEntry("game.status.hint_unavailable", "Подсказка недоступна"),
            localizationEntry("game.status.hint_match_here", "Подсказка: цифра {digit} стоит в этой позиции"),
            localizationEntry("game.status.hint_no_match_here", "Подсказка: цифра {digit} не стоит в этой позиции"),
            localizationEntry("game.status.hint_position_contains", "Подсказка: в позиции {position} стоит цифра {digit}"),
            localizationEntry("game.status.hint_digit_count", "Цифра {digit} встречается {count} раз"),
            localizationEntry("game.status.hint_applied", "Подсказка применена"),
            localizationEntry("game.status.no_move_boosts", "Бустеры ходов закончились"),
            localizationEntry("game.status.moves_added", "Добавлено ходов: {count}"),
            localizationEntry("game.status.no_time_boosts", "Бустеры времени закончились"),
            localizationEntry("game.status.time_added", "Добавлено времени: {minutes} мин"),
            localizationEntry("game.status.new_secret", "Сгенерировано новое число"),
            localizationEntry("game.status.wait_opponent", "Подождите ход соперника"),
            localizationEntry("game.status.enter_digits", "Введите {count} цифр"),
            localizationEntry("game.status.attempt_not_accepted", "Попытка не принята"),
            localizationEntry("game.status.solved_new_secret", "Угадано. Сгенерировано новое число"),
            localizationEntry("game.status.no_attempts_left", "Попытки закончились"),
            localizationEntry("game.status.matches", "Совпадений: {count}"),
            localizationEntry("game.validation.all_same_digits", "Нельзя вводить комбинацию из одинаковых цифр"),
            localizationEntry("game.validation.duplicate_digits", "Повторяющиеся цифры запрещены"),
            localizationEntry("game.validation.adjacent_duplicates", "Одинаковые цифры подряд запрещены"),
            localizationEntry("game.validation.triple_duplicates", "Три одинаковые цифры подряд запрещены"),
            localizationEntry("game.validation.only_digits", "Можно вводить только цифры"),
            localizationEntry("game.status.auto_enabled", "Авто режим включен"),
            localizationEntry("game.status.auto_disabled", "Авто режим выключен"),
            localizationEntry("game.status.auto_requires_pro", "Авто режим входит в подписку Pro"),
            localizationEntry("game.status.bonus_hint_ready", "Бонусная подсказка готова к использованию"),
            localizationEntry("game.status.bonus_not_granted", "Бонус не получен"),
            localizationEntry("game.dialog.bonus_hint.title", "Получить бонусную подсказку?"),
            localizationEntry("game.dialog.bonus_hint.text", "Посмотреть рекламу и получить 1 использование выбранной подсказки."),
            localizationEntry("game.dialog.hint.title", "Подсказка"),
            localizationEntry("game.action.watch", "Смотреть"),
            localizationEntry("game.action.cancel", "Отмена"),
            localizationEntry("game.action.ok", "Ок"),
            localizationEntry("game.top.moves", "Ходы"),
            localizationEntry("game.top.total", "Общее"),
            localizationEntry("game.top.turn", "Ход"),
            localizationEntry("game.attempts.title", "Попытки"),
            localizationEntry("game.attempts.empty", "Здесь будут отображаться ваши попытки угадать"),
            localizationEntry("game.hint.open_position", "Открыть позицию"),
            localizationEntry("game.hint.check_digit", "Проверить цифру"),
            localizationEntry("game.hint.check_position", "Проверить позицию"),
            localizationEntry("game.boost.add_moves", "Добавить ходы"),
            localizationEntry("game.boost.add_time", "Добавить время"),
            localizationEntry("game.boost.moves_short", "ход."),
            localizationEntry("game.auto_mode", "Авто режим"),
            localizationEntry("game.auto_mode.pro", "PRO"),
            localizationEntry("game.auto_mode.auto", "Авто"),
            localizationEntry("game.auto_mode.manual", "Ручной"),
            localizationEntry("game.tool.no", "Нет"),
            localizationEntry("game.tool.maybe", "Возможно"),
            localizationEntry("game.tool.yes", "Точно"),
            localizationEntry("game.combination", "Комбинация"),
            localizationEntry("game.action.reset", "Сброс"),
            localizationEntry("game.action.confirm", "Подтвердить"),
            localizationEntry("game.action.delete", "Стереть"),
            localizationEntry("game.ad_slot", "Рекламный слот игрового экрана"),
            localizationEntry("game.debug.secret", "Секрет: {value}"),
            localizationEntry("game.debug.hints", "Подсказки: {open} / {digit} / {position}"),
            localizationEntry("game.debug.boosts", "Бустеры: {moves} / {time}"),
            localizationEntry("game.debug.add_hints", "+3 подсказки"),
        ),
    )

    val en = localizationCatalog(
        name = "game.en",
        entries = listOf(
            localizationEntry("game.status.default", "Enter a combination or mark the table"),
            localizationEntry("game.status.time_over", "Time is over"),
            localizationEntry("game.status.no_hints", "No hints of this type left"),
            localizationEntry("game.status.watch_ad_for_hint", "Watch an ad to get a bonus hint"),
            localizationEntry("game.status.select_table_cell", "Select a table cell to check position"),
            localizationEntry("game.status.select_slot", "Select a combination slot to open"),
            localizationEntry("game.status.select_digit", "Select a digit on the input pad"),
            localizationEntry("game.status.hint_unavailable", "Hint is unavailable"),
            localizationEntry("game.status.hint_match_here", "Hint: digit {digit} is correct here"),
            localizationEntry("game.status.hint_no_match_here", "Hint: digit {digit} is not correct here"),
            localizationEntry("game.status.hint_position_contains", "Hint: position {position} contains {digit}"),
            localizationEntry("game.status.hint_digit_count", "Digit {digit} appears {count} time(s)"),
            localizationEntry("game.status.hint_applied", "Hint applied"),
            localizationEntry("game.status.no_move_boosts", "No move boosts left"),
            localizationEntry("game.status.moves_added", "Added moves: {count}"),
            localizationEntry("game.status.no_time_boosts", "No time boosts left"),
            localizationEntry("game.status.time_added", "Added time: {minutes} min"),
            localizationEntry("game.status.new_secret", "A new secret has been generated"),
            localizationEntry("game.status.wait_opponent", "Wait for opponent turn"),
            localizationEntry("game.status.enter_digits", "Enter {count} digits"),
            localizationEntry("game.status.attempt_not_accepted", "Attempt not accepted"),
            localizationEntry("game.status.solved_new_secret", "Solved. A new secret has been generated"),
            localizationEntry("game.status.no_attempts_left", "No attempts left"),
            localizationEntry("game.status.matches", "Matches: {count}"),
            localizationEntry("game.validation.all_same_digits", "The combination cannot contain only one repeated digit"),
            localizationEntry("game.validation.duplicate_digits", "Duplicate digits are forbidden"),
            localizationEntry("game.validation.adjacent_duplicates", "Adjacent duplicate digits are forbidden"),
            localizationEntry("game.validation.triple_duplicates", "Three identical digits in a row are forbidden"),
            localizationEntry("game.validation.only_digits", "Only digits are allowed"),
            localizationEntry("game.status.auto_enabled", "Auto mode enabled"),
            localizationEntry("game.status.auto_disabled", "Auto mode disabled"),
            localizationEntry("game.status.auto_requires_pro", "Auto mode is part of Pro"),
            localizationEntry("game.status.bonus_hint_ready", "Bonus hint is ready"),
            localizationEntry("game.status.bonus_not_granted", "Bonus was not granted"),
            localizationEntry("game.dialog.bonus_hint.title", "Get a bonus hint?"),
            localizationEntry("game.dialog.bonus_hint.text", "Watch an ad to receive 1 use of the selected hint."),
            localizationEntry("game.dialog.hint.title", "Hint"),
            localizationEntry("game.action.watch", "Watch"),
            localizationEntry("game.action.cancel", "Cancel"),
            localizationEntry("game.action.ok", "OK"),
            localizationEntry("game.top.moves", "Moves"),
            localizationEntry("game.top.total", "Total"),
            localizationEntry("game.top.turn", "Turn"),
            localizationEntry("game.attempts.title", "Attempts"),
            localizationEntry("game.attempts.empty", "Your attempts to guess the secret will appear here"),
            localizationEntry("game.hint.open_position", "Open position"),
            localizationEntry("game.hint.check_digit", "Check digit"),
            localizationEntry("game.hint.check_position", "Check position"),
            localizationEntry("game.boost.add_moves", "Add moves"),
            localizationEntry("game.boost.add_time", "Add time"),
            localizationEntry("game.boost.moves_short", "moves"),
            localizationEntry("game.auto_mode", "Auto mode"),
            localizationEntry("game.auto_mode.pro", "PRO"),
            localizationEntry("game.auto_mode.auto", "Auto"),
            localizationEntry("game.auto_mode.manual", "Manual"),
            localizationEntry("game.tool.no", "No"),
            localizationEntry("game.tool.maybe", "Maybe"),
            localizationEntry("game.tool.yes", "Yes"),
            localizationEntry("game.combination", "Combination"),
            localizationEntry("game.action.reset", "Reset"),
            localizationEntry("game.action.confirm", "Confirm"),
            localizationEntry("game.action.delete", "Delete"),
            localizationEntry("game.ad_slot", "Game screen ad slot"),
            localizationEntry("game.debug.secret", "Secret: {value}"),
            localizationEntry("game.debug.hints", "Hints: {open} / {digit} / {position}"),
            localizationEntry("game.debug.boosts", "Boosts: {moves} / {time}"),
            localizationEntry("game.debug.add_hints", "+3 hints"),
        ),
    )
}
