package com.mirkori.inplacex.platform.localization

internal object HomeCatalog {
    val ru = localizationCatalog(
        name = "home.ru",
        entries = listOf(
            localizationEntry("top.back", "Назад"),
            localizationEntry("top.settings", "Настройки"),
            localizationEntry("top.energy", "Энергия"),
            localizationEntry("top.coins", "Монеты"),
            localizationEntry("section.home.title", "Главная"),
            localizationEntry("section.home.short", "Главная"),
            localizationEntry("section.home.reserve", "Нижний резерв: баннер / акция / быстрый вход"),
            localizationEntry("section.social.title", "Друзья / Онлайн"),
            localizationEntry("section.social.short", "Друзья"),
            localizationEntry("section.social.reserve", "Нижний резерв: реклама / комната / онлайн-событие"),
            localizationEntry("section.company.title", "Компания"),
            localizationEntry("section.company.short", "Компания"),
            localizationEntry("section.company.reserve", "Нижний резерв: компания / прогресс / цели"),
            localizationEntry("section.shop.title", "Магазин"),
            localizationEntry("section.shop.short", "Магазин"),
            localizationEntry("section.shop.reserve", "Нижний резерв: оффер / подписка / акция"),
            localizationEntry("section.profile.title", "Профиль"),
            localizationEntry("section.profile.short", "Профиль"),
            localizationEntry("section.profile.reserve", "Нижний резерв: премиум / статус / сервис"),
            localizationEntry("mode.pve.title", "Гонка"),
            localizationEntry("mode.pve.subtitle", "Раскройте код быстрее, чем закончатся ходы"),
            localizationEntry("mode.pvp.title", "Дуэль"),
            localizationEntry("mode.pvp.subtitle", "Сразитесь с соперником ход за ходом"),
            localizationEntry("home.title", "InplaceX"),
            localizationEntry("home.subtitle", "Логика, скорость и точный расчёт"),
            localizationEntry("home.description", "Главный экран. Отсюда идём в настройку матча и дальше в экран гонки."),
            localizationEntry("home.code_length", "%d цифр"),
            localizationEntry("home.duel.kind", "Против бота"),
            localizationEntry("home.company.teaser", "Кампания, награды и запас энергии находятся во вкладке «Компания»."),
            localizationEntry("home.company.continue", "Продолжить компанию"),
            localizationEntry("home.reserve.ad", "Нижний резерв экрана\nпод рекламу / системный блок"),
            localizationEntry("home.reserve.premium", "Заглушка премиум\nздесь может быть чистый нижний блок"),
            localizationEntry("home.pve.screen.title", "Режимы против бота"),
            localizationEntry("home.pve.screen.description", "Здесь будут режимы против бота и одиночные режимы."),
            localizationEntry("home.pve.race", "Гонка с ботом"),
            localizationEntry("home.pve.campaign", "Кампания"),
            localizationEntry("home.pvp.screen.title", "Режимы с друзьями и онлайн"),
            localizationEntry("home.pvp.screen.description", "Здесь будут режимы с друзьями и онлайн-матчи."),
            localizationEntry("home.pvp.friend", "Играть с другом"),
            localizationEntry("home.pvp.online", "Онлайн-матч"),
            localizationEntry("home.duel.turn.player", "Ход игрока"),
            localizationEntry("home.duel.turn.opponent", "Ход соперника"),
            localizationEntry("home.duel.status.with_score", "Последний счёт соперника: %d • Подтверждено: %d/%d"),
            localizationEntry("home.duel.status.waiting", "Соперник ещё не ходил • Подтверждено: %d/%d"),
            localizationEntry("home.duel.result.bot_win", "Соперник угадал ваш секрет. Последний счёт бота: %d"),
            localizationEntry("home.duel.result.player_win", "Вы первыми угадали секрет соперника."),
            localizationEntry("home.dialog.exit.title", "Выйти из текущей игры?"),
            localizationEntry("home.dialog.exit.text", "Текущий матч будет закрыт, и вы вернётесь на главный экран."),
            localizationEntry("home.dialog.exit.confirm", "Выйти"),
            localizationEntry("home.dialog.exit.stay", "Остаться"),
            localizationEntry("home.dialog.result.title", "Результат дуэли"),
            localizationEntry("home.dialog.result.ok", "ОК"),
            localizationEntry("home.dialog.setup.title", "Настройка секрета"),
            localizationEntry("home.dialog.setup.secret_prompt", "Задайте свой секрет до начала дуэли."),
            localizationEntry("home.dialog.setup.secret_label", "Секрет (%d цифр)"),
            localizationEntry("home.dialog.setup.time_left", "Осталось времени: %d с"),
            localizationEntry("home.dialog.setup.wait_opponent", "Ожидание секрета соперника…"),
            localizationEntry("home.dialog.setup.bot_ready", "Бот будет готов через %d с"),
            localizationEntry("home.dialog.setup.timeout", "Время выбора секрета истекло. Матч отменён."),
            localizationEntry("home.dialog.setup.preparing", "Подготовка матча…"),
            localizationEntry("home.dialog.setup.enter_digits", "Введите %d цифр"),
            localizationEntry("home.dialog.setup.invalid_secret", "Секрет не соответствует правилам дуэли"),
            localizationEntry("home.dialog.setup.confirm", "Подтвердить"),
            localizationEntry("home.dialog.setup.close", "Закрыть"),
            localizationEntry("home.dialog.setup.cancel", "Отмена"),
            localizationEntry("social.title", "Друзья / Онлайн"),
            localizationEntry("social.friends", "Друзья"),
            localizationEntry("social.online", "Онлайн"),
        ),
    )

    val en = localizationCatalog(
        name = "home.en",
        entries = listOf(
            localizationEntry("top.back", "Back"),
            localizationEntry("top.settings", "Settings"),
            localizationEntry("top.energy", "Energy"),
            localizationEntry("top.coins", "Coins"),
            localizationEntry("section.home.title", "Home"),
            localizationEntry("section.home.short", "Home"),
            localizationEntry("section.home.reserve", "Bottom reserve: banner / promo / quick entry"),
            localizationEntry("section.social.title", "Friends / Online"),
            localizationEntry("section.social.short", "Friends"),
            localizationEntry("section.social.reserve", "Bottom reserve: ad / room / online event"),
            localizationEntry("section.company.title", "Company"),
            localizationEntry("section.company.short", "Company"),
            localizationEntry("section.company.reserve", "Bottom reserve: company / progress / goals"),
            localizationEntry("section.shop.title", "Shop"),
            localizationEntry("section.shop.short", "Shop"),
            localizationEntry("section.shop.reserve", "Bottom reserve: offer / subscription / promo"),
            localizationEntry("section.profile.title", "Profile"),
            localizationEntry("section.profile.short", "Profile"),
            localizationEntry("section.profile.reserve", "Bottom reserve: premium / status / service"),
            localizationEntry("mode.pve.title", "Race"),
            localizationEntry("mode.pve.subtitle", "Crack the code before your moves run out"),
            localizationEntry("mode.pvp.title", "Duel"),
            localizationEntry("mode.pvp.subtitle", "Challenge an opponent turn by turn"),
            localizationEntry("home.title", "InplaceX"),
            localizationEntry("home.subtitle", "Logic, speed, and precise calculation"),
            localizationEntry("home.description", "The home screen. Start here to configure a match and open the race screen."),
            localizationEntry("home.code_length", "%d digits"),
            localizationEntry("home.duel.kind", "Bot duel"),
            localizationEntry("home.company.teaser", "Campaign, rewards, and energy live in the Company tab."),
            localizationEntry("home.company.continue", "Continue company"),
            localizationEntry("home.reserve.ad", "Screen bottom reserve\nfor ads / a system block"),
            localizationEntry("home.reserve.premium", "Premium placeholder\na clean bottom block can go here"),
            localizationEntry("home.pve.screen.title", "Bot modes"),
            localizationEntry("home.pve.screen.description", "Bot and single-player modes will appear here."),
            localizationEntry("home.pve.race", "Bot race"),
            localizationEntry("home.pve.campaign", "Campaign"),
            localizationEntry("home.pvp.screen.title", "Friends and online modes"),
            localizationEntry("home.pvp.screen.description", "Friends and online matches will appear here."),
            localizationEntry("home.pvp.friend", "Play with a friend"),
            localizationEntry("home.pvp.online", "Online match"),
            localizationEntry("home.duel.turn.player", "Player turn"),
            localizationEntry("home.duel.turn.opponent", "Opponent turn"),
            localizationEntry("home.duel.status.with_score", "Opponent's last score: %d • Confirmed: %d/%d"),
            localizationEntry("home.duel.status.waiting", "Opponent has not moved yet • Confirmed: %d/%d"),
            localizationEntry("home.duel.result.bot_win", "The opponent guessed your secret. Last bot score: %d"),
            localizationEntry("home.duel.result.player_win", "You guessed the opponent's secret first."),
            localizationEntry("home.dialog.exit.title", "Exit the current game?"),
            localizationEntry("home.dialog.exit.text", "The current match will close and you will return to the home screen."),
            localizationEntry("home.dialog.exit.confirm", "Exit"),
            localizationEntry("home.dialog.exit.stay", "Stay"),
            localizationEntry("home.dialog.result.title", "Duel result"),
            localizationEntry("home.dialog.result.ok", "OK"),
            localizationEntry("home.dialog.setup.title", "Secret setup"),
            localizationEntry("home.dialog.setup.secret_prompt", "Set your secret before the duel starts."),
            localizationEntry("home.dialog.setup.secret_label", "Secret (%d digits)"),
            localizationEntry("home.dialog.setup.time_left", "Time left: %d s"),
            localizationEntry("home.dialog.setup.wait_opponent", "Waiting for the opponent's secret…"),
            localizationEntry("home.dialog.setup.bot_ready", "The bot will be ready in %d s"),
            localizationEntry("home.dialog.setup.timeout", "Secret selection timed out. The match was cancelled."),
            localizationEntry("home.dialog.setup.preparing", "Preparing the match…"),
            localizationEntry("home.dialog.setup.enter_digits", "Enter %d digits"),
            localizationEntry("home.dialog.setup.invalid_secret", "The secret does not match the duel rules"),
            localizationEntry("home.dialog.setup.confirm", "Confirm"),
            localizationEntry("home.dialog.setup.close", "Close"),
            localizationEntry("home.dialog.setup.cancel", "Cancel"),
            localizationEntry("social.title", "Friends / Online"),
            localizationEntry("social.friends", "Friends"),
            localizationEntry("social.online", "Online"),
        ),
    )
}
