package com.mirkori.inplacex.platform.localization

internal object HomeCatalog {
    val ru = localizationCatalog(
        name = "home.ru",
        entries = listOf(
            localizationEntry("top.back", "Назад"),
            localizationEntry("top.settings", "Настройки"),
            localizationEntry("top.energy", "Энергия"),
            localizationEntry("top.coins", "Монеты"),
            localizationEntry("section.home.title", "Главная"),
            localizationEntry("section.home.short", "Главная"),
            localizationEntry("section.home.reserve", "Нижний резерв: баннер / акция / быстрый вход"),
            localizationEntry("section.social.title", "Друзья / Онлайн"),
            localizationEntry("section.social.short", "Друзья"),
            localizationEntry("section.social.reserve", "Нижний резерв: реклама / комната / онлайн-событие"),
            localizationEntry("section.company.title", "Компания"),
            localizationEntry("section.company.short", "Компания"),
            localizationEntry("section.company.reserve", "Нижний резерв: компания / прогресс / цели"),
            localizationEntry("section.shop.title", "Магазин"),
            localizationEntry("section.shop.short", "Магазин"),
            localizationEntry("section.shop.reserve", "Нижний резерв: оффер / подписка / акция"),
            localizationEntry("section.profile.title", "Профиль"),
            localizationEntry("section.profile.short", "Профиль"),
            localizationEntry("section.profile.reserve", "Нижний резерв: premium / статус / сервис"),
            localizationEntry("mode.pve.title", "Гонка"),
            localizationEntry("mode.pve.subtitle", "Раскройте код быстрее, чем закончатся ходы"),
            localizationEntry("mode.pvp.title", "Дуэль"),
            localizationEntry("mode.pvp.subtitle", "Сразитесь с соперником ход за ходом"),
            localizationEntry("home.title", "InplaceX"),
            localizationEntry("home.subtitle", "Логика, скорость и точный расчёт"),
            localizationEntry("home.code_length", "{count} цифр"),
            localizationEntry("home.duel.kind", "Против бота"),
            localizationEntry("home.company.teaser", "Кампания, награды и запас энергии находятся во вкладке «Компания»."),
            localizationEntry("social.title", "Друзья / Онлайн"),
            localizationEntry("social.friends", "Друзья"),
            localizationEntry("social.online", "Онлайн"),
        ),
    )

    val en = localizationCatalog(
        name = "home.en",
        entries = listOf(
            localizationEntry("top.back", "Back"),
            localizationEntry("top.settings", "Settings"),
            localizationEntry("top.energy", "Energy"),
            localizationEntry("top.coins", "Coins"),
            localizationEntry("section.home.title", "Home"),
            localizationEntry("section.home.short", "Home"),
            localizationEntry("section.home.reserve", "Bottom reserve: banner / promo / quick entry"),
            localizationEntry("section.social.title", "Friends / Online"),
            localizationEntry("section.social.short", "Friends"),
            localizationEntry("section.social.reserve", "Bottom reserve: ad / room / online event"),
            localizationEntry("section.company.title", "Company"),
            localizationEntry("section.company.short", "Company"),
            localizationEntry("section.company.reserve", "Bottom reserve: company / progress / goals"),
            localizationEntry("section.shop.title", "Shop"),
            localizationEntry("section.shop.short", "Shop"),
            localizationEntry("section.shop.reserve", "Bottom reserve: offer / subscription / promo"),
            localizationEntry("section.profile.title", "Profile"),
            localizationEntry("section.profile.short", "Profile"),
            localizationEntry("section.profile.reserve", "Bottom reserve: premium / status / service"),
            localizationEntry("mode.pve.title", "Race"),
            localizationEntry("mode.pve.subtitle", "Crack the code before your moves run out"),
            localizationEntry("mode.pvp.title", "Duel"),
            localizationEntry("mode.pvp.subtitle", "Challenge an opponent turn by turn"),
            localizationEntry("home.title", "InplaceX"),
            localizationEntry("home.subtitle", "Logic, speed, and precise calculation"),
            localizationEntry("home.code_length", "{count} digits"),
            localizationEntry("home.duel.kind", "Bot duel"),
            localizationEntry("home.company.teaser", "Campaign, rewards, and energy live in the Company tab."),
            localizationEntry("social.title", "Friends / Online"),
            localizationEntry("social.friends", "Friends"),
            localizationEntry("social.online", "Online"),
        ),
    )
}
