package com.mirkori.inplacex.platform.localization

internal object HomeCatalog {
    val ru = localizationCatalog(
        name = "home.ru",
        entries = listOf(
            localizationEntry("top.back", "Назад"),
            localizationEntry("top.settings", "Настройки"),
            localizationEntry("top.energy", "Энергия"),
            localizationEntry("top.coins", "Монеты"),
            localizationEntry("section.home.title", "Главная"),
            localizationEntry("section.home.short", "Главная"),
            localizationEntry("section.home.reserve", "Нижний резерв: баннер / акция / быстрый вход"),
            localizationEntry("section.social.title", "Друзья / Онлайн"),
            localizationEntry("section.social.short", "Друзья"),
            localizationEntry("section.social.reserve", "Нижний резерв: реклама / комната / онлайн-событие"),
            localizationEntry("section.company.title", "Компания"),
            localizationEntry("section.company.short", "Компания"),
            localizationEntry("section.company.reserve", "Нижний резерв: компания / прогресс / цели"),
            localizationEntry("section.shop.title", "Магазин"),
            localizationEntry("section.shop.short", "Магазин"),
            localizationEntry("section.shop.reserve", "Нижний резерв: оффер / доступ / акция"),
            localizationEntry("section.profile.title", "Профиль"),
            localizationEntry("section.profile.short", "Профиль"),
            localizationEntry("section.profile.reserve", "Нижний резерв: премиум / статус / сервис"),
            localizationEntry("mode.pve.title", "Гонка"),
            localizationEntry("mode.pve.subtitle", "Раскройте код как можно быстрее"),
            localizationEntry("mode.pvp.title", "Дуэль"),
            localizationEntry("mode.pvp.subtitle", "Сразитесь с соперником ход за ходом"),
            localizationEntry("home.title", "InplaceX"),
            localizationEntry("home.subtitle", "Логика, скорость и точный расчёт"),
            localizationEntry("home.description", "Главный экран. Отсюда идём в настройку матча и дальше в экран гонки."),
            localizationEntry("home.code_length", "%d цифр"),
            localizationEntry("home.duel.kind", "Против бота"),
            localizationEntry("home.company.teaser", "Кампания, награды и запас энергии"),
            localizationEntry("home.company.continue", "Компания"),
            localizationEntry("home.reserve.ad", "Нижний резерв экрана\nпод рекламу / системный блок"),
            localizationEntry("home.reserve.premium", "Заглушка премиум\nздесь может быть чистый нижний блок"),
            localizationEntry("home.pve.screen.title", "Режимы против бота"),
            localizationEntry("home.pve.screen.description", "Здесь будут режимы против бота и одиночные режимы."),
            localizationEntry("home.pve.race", "Гонка с ботом"),
            localizationEntry("home.pve.campaign", "Кампания"),
            localizationEntry("home.race.opponent.title", "Результаты соперника"),
            localizationEntry("home.race.opponent.waiting", "Готовится к первому ходу"),
            localizationEntry("home.race.opponent.thinking", "Подбирает комбинацию…"),
            localizationEntry("home.race.opponent.racing", "Продолжает гонку"),
            localizationEntry("home.race.opponent.finished", "Код раскрыт"),
            localizationEntry("home.race.opponent.failed", "Расчёт остановлен"),
            localizationEntry("home.race.opponent.empty", "Ходов пока нет"),
            localizationEntry("home.pvp.screen.title", "Выберите соперника"),
            localizationEntry(
                "home.pvp.screen.description",
                "В online-матче ищем игрока; после ожидания сервер может подключить бота.",
            ),
            localizationEntry("home.pvp.bot", "С ботом"),
            localizationEntry("home.pvp.online", "Онлайн‑матч"),
            localizationEntry("reference.setup.duplicates", "Цифры могут повторяться"),
            localizationEntry("reference.race.title", "Гонка"),
            localizationEntry("reference.race.subtitle", "Раскройте код быстрее соперника. Здесь решают логика и скорость."),
            localizationEntry("reference.race.quick", "Быстрая гонка"),
            localizationEntry("reference.race.quick.subtitle", "Найти соперника и начать"),
            localizationEntry("reference.race.training", "Тренировка"),
            localizationEntry("reference.race.training.subtitle", "Гонка против бота"),
            localizationEntry("reference.race.records", "Рекорды"),
            localizationEntry("reference.race.records.unavailable", "Раздел готовится"),
            localizationEntry("reference.duel.title", "Дуэль"),
            localizationEntry("reference.duel.subtitle", "Сразитесь с соперником ход за ходом и докажите, что ваша логика сильнее."),
            localizationEntry("reference.duel.bot.subtitle", "Игра против бота"),
            localizationEntry("reference.duel.online.subtitle", "Сразиться с реальным игроком"),
            localizationEntry("reference.setup.back.subtitle", "Вернуться на главную"),
            localizationEntry("home.duel.turn.player", "Ход игрока"),
            localizationEntry("home.duel.turn.opponent", "Ход соперника"),
            localizationEntry("home.duel.status.with_score", "Последний счёт соперника: %d • Подтверждено: %d/%d"),
            localizationEntry("home.duel.status.waiting", "Соперник ещё не ходил • Подтверждено: %d/%d"),
            localizationEntry(
                "home.duel.status.bot_turn_failed",
                "Ход соперника не рассчитан. Дуэль остаётся открытой — повторите свой ход.",
            ),
            localizationEntry("home.duel.result.bot_win", "Соперник угадал ваш секрет. Последний счёт бота: %d"),
            localizationEntry("home.duel.result.player_win", "Вы первыми угадали секрет соперника."),
            localizationEntry("home.dialog.exit.title", "Выйти из текущей игры?"),
            localizationEntry("home.dialog.exit.text", "Текущий матч будет закрыт, и вы вернётесь на главный экран."),
            localizationEntry("home.dialog.exit.confirm", "Выйти"),
            localizationEntry("home.dialog.exit.stay", "Остаться"),
            localizationEntry("home.dialog.result.title", "Результат дуэли"),
            localizationEntry("home.dialog.result.ok", "ОК"),
            localizationEntry("home.race.result.win_title", "Гонка выиграна!"),
            localizationEntry("home.race.result.loss_title", "Ходы закончились"),
            localizationEntry("home.race.result.opponent_title", "Соперник победил"),
            localizationEntry("home.race.result.win_message", "Код раскрыт. Победа сохранена в профиле."),
            localizationEntry("home.race.result.loss_message", "Код не раскрыт. Поражение сохранено в профиле."),
            localizationEntry(
                "home.race.result.opponent_message",
                "Соперник первым раскрыл общий код. Поражение сохранено в профиле.",
            ),
            localizationEntry("home.race.result.attempts", "Попытки: %d из %d"),
            localizationEntry("home.race.result.attempts_unlimited", "Попытки: %d • без лимита"),
            localizationEntry("home.race.result.time", "Время: %s"),
            localizationEntry("home.race.result.reward", "Награда: +%d монет"),
            localizationEntry("home.race.result.retry", "Ещё раз"),
            localizationEntry("home.race.result.home", "На главную"),
            localizationEntry("home.dialog.setup.title", "Настройка секрета"),
            localizationEntry("home.dialog.setup.secret_prompt", "Задайте свой секрет до начала дуэли."),
            localizationEntry("home.dialog.setup.secret_label", "Секрет (%d цифр)"),
            localizationEntry("home.dialog.setup.time_left", "Осталось времени: %d с"),
            localizationEntry("home.dialog.setup.wait_opponent", "Ожидание секрета соперника…"),
            localizationEntry("home.dialog.setup.bot_ready", "Бот будет готов через %d с"),
            localizationEntry("home.dialog.setup.timeout", "Время выбора секрета истекло. Матч отменён."),
            localizationEntry("home.dialog.setup.preparing", "Подготовка матча…"),
            localizationEntry("home.dialog.setup.enter_digits", "Введите %d цифр"),
            localizationEntry("home.dialog.setup.invalid_secret", "Секрет не соответствует правилам дуэли"),
            localizationEntry("home.dialog.setup.confirm", "Подтвердить"),
            localizationEntry("home.dialog.setup.close", "Закрыть"),
            localizationEntry("home.dialog.setup.cancel", "Отмена"),
            localizationEntry("social.title", "Друзья / Онлайн"),
            localizationEntry("social.friends", "Друзья"),
            localizationEntry("social.online", "Онлайн"),
        ),
    )

    val en = localizationCatalog(
        name = "home.en",
        entries = listOf(
            localizationEntry("top.back", "Back"),
            localizationEntry("top.settings", "Settings"),
            localizationEntry("top.energy", "Energy"),
            localizationEntry("top.coins", "Coins"),
            localizationEntry("section.home.title", "Home"),
            localizationEntry("section.home.short", "Home"),
            localizationEntry("section.home.reserve", "Bottom reserve: banner / promo / quick entry"),
            localizationEntry("section.social.title", "Friends / Online"),
            localizationEntry("section.social.short", "Friends"),
            localizationEntry("section.social.reserve", "Bottom reserve: ad / room / online event"),
            localizationEntry("section.company.title", "Company"),
            localizationEntry("section.company.short", "Company"),
            localizationEntry("section.company.reserve", "Bottom reserve: company / progress / goals"),
            localizationEntry("section.shop.title", "Shop"),
            localizationEntry("section.shop.short", "Shop"),
            localizationEntry("section.shop.reserve", "Bottom reserve: offer / access / promo"),
            localizationEntry("section.profile.title", "Profile"),
            localizationEntry("section.profile.short", "Profile"),
            localizationEntry("section.profile.reserve", "Bottom reserve: premium / status / service"),
            localizationEntry("mode.pve.title", "Race"),
            localizationEntry("mode.pve.subtitle", "Crack the code as fast as possible"),
            localizationEntry("mode.pvp.title", "Duel"),
            localizationEntry("mode.pvp.subtitle", "Challenge an opponent turn by turn"),
            localizationEntry("home.title", "InplaceX"),
            localizationEntry("home.subtitle", "Logic, speed, and precise calculation"),
            localizationEntry("home.description", "The home screen. Start here to configure a match and open the race screen."),
            localizationEntry("home.code_length", "%d digits"),
            localizationEntry("home.duel.kind", "Bot duel"),
            localizationEntry("home.company.teaser", "Campaign, rewards, and energy"),
            localizationEntry("home.company.continue", "Company"),
            localizationEntry("home.reserve.ad", "Screen bottom reserve\nfor ads / a system block"),
            localizationEntry("home.reserve.premium", "Premium placeholder\na clean bottom block can go here"),
            localizationEntry("home.pve.screen.title", "Bot modes"),
            localizationEntry("home.pve.screen.description", "Bot and single-player modes will appear here."),
            localizationEntry("home.pve.race", "Bot race"),
            localizationEntry("home.pve.campaign", "Campaign"),
            localizationEntry("home.race.opponent.title", "Opponent results"),
            localizationEntry("home.race.opponent.waiting", "Preparing the first move"),
            localizationEntry("home.race.opponent.thinking", "Choosing a combination…"),
            localizationEntry("home.race.opponent.racing", "Still racing"),
            localizationEntry("home.race.opponent.finished", "Code cracked"),
            localizationEntry("home.race.opponent.failed", "Calculation stopped"),
            localizationEntry("home.race.opponent.empty", "No moves yet"),
            localizationEntry("home.pvp.screen.title", "Choose an opponent"),
            localizationEntry(
                "home.pvp.screen.description",
                "Online matchmaking looks for a player; the server may add a bot after the wait.",
            ),
            localizationEntry("home.pvp.bot", "Play a bot"),
            localizationEntry("home.pvp.online", "Online match"),
            localizationEntry("reference.setup.duplicates", "Digits may repeat"),
            localizationEntry("reference.race.title", "Race"),
            localizationEntry("reference.race.subtitle", "Crack the code before your opponent. Logic and speed decide the race."),
            localizationEntry("reference.race.quick", "Quick race"),
            localizationEntry("reference.race.quick.subtitle", "Find an opponent and start"),
            localizationEntry("reference.race.training", "Training"),
            localizationEntry("reference.race.training.subtitle", "Race against a bot"),
            localizationEntry("reference.race.records", "Records"),
            localizationEntry("reference.race.records.unavailable", "Coming soon"),
            localizationEntry("reference.duel.title", "Duel"),
            localizationEntry("reference.duel.subtitle", "Challenge an opponent turn by turn and prove your logic is stronger."),
            localizationEntry("reference.duel.bot.subtitle", "Play against a bot"),
            localizationEntry("reference.duel.online.subtitle", "Challenge a real player"),
            localizationEntry("reference.setup.back.subtitle", "Return to the home screen"),
            localizationEntry("home.duel.turn.player", "Player turn"),
            localizationEntry("home.duel.turn.opponent", "Opponent turn"),
            localizationEntry("home.duel.status.with_score", "Opponent's last score: %d • Confirmed: %d/%d"),
            localizationEntry("home.duel.status.waiting", "Opponent has not moved yet • Confirmed: %d/%d"),
            localizationEntry(
                "home.duel.status.bot_turn_failed",
                "The opponent's turn could not be calculated. The duel remains open — try your turn again.",
            ),
            localizationEntry("home.duel.result.bot_win", "The opponent guessed your secret. Last bot score: %d"),
            localizationEntry("home.duel.result.player_win", "You guessed the opponent's secret first."),
            localizationEntry("home.dialog.exit.title", "Exit the current game?"),
            localizationEntry("home.dialog.exit.text", "The current match will close and you will return to the home screen."),
            localizationEntry("home.dialog.exit.confirm", "Exit"),
            localizationEntry("home.dialog.exit.stay", "Stay"),
            localizationEntry("home.dialog.result.title", "Duel result"),
            localizationEntry("home.dialog.result.ok", "OK"),
            localizationEntry("home.race.result.win_title", "Race won!"),
            localizationEntry("home.race.result.loss_title", "No moves left"),
            localizationEntry("home.race.result.opponent_title", "Opponent won"),
            localizationEntry("home.race.result.win_message", "Code cracked. The victory was saved to your profile."),
            localizationEntry("home.race.result.loss_message", "Code not cracked. The defeat was saved to your profile."),
            localizationEntry(
                "home.race.result.opponent_message",
                "The opponent cracked the shared code first. The defeat was saved to your profile.",
            ),
            localizationEntry("home.race.result.attempts", "Attempts: %d of %d"),
            localizationEntry("home.race.result.attempts_unlimited", "Attempts: %d • unlimited"),
            localizationEntry("home.race.result.time", "Time: %s"),
            localizationEntry("home.race.result.reward", "Reward: +%d coins"),
            localizationEntry("home.race.result.retry", "Play again"),
            localizationEntry("home.race.result.home", "Home"),
            localizationEntry("home.dialog.setup.title", "Secret setup"),
            localizationEntry("home.dialog.setup.secret_prompt", "Set your secret before the duel starts."),
            localizationEntry("home.dialog.setup.secret_label", "Secret (%d digits)"),
            localizationEntry("home.dialog.setup.time_left", "Time left: %d s"),
            localizationEntry("home.dialog.setup.wait_opponent", "Waiting for the opponent's secret…"),
            localizationEntry("home.dialog.setup.bot_ready", "The bot will be ready in %d s"),
            localizationEntry("home.dialog.setup.timeout", "Secret selection timed out. The match was cancelled."),
            localizationEntry("home.dialog.setup.preparing", "Preparing the match…"),
            localizationEntry("home.dialog.setup.enter_digits", "Enter %d digits"),
            localizationEntry("home.dialog.setup.invalid_secret", "The secret does not match the duel rules"),
            localizationEntry("home.dialog.setup.confirm", "Confirm"),
            localizationEntry("home.dialog.setup.close", "Close"),
            localizationEntry("home.dialog.setup.cancel", "Cancel"),
            localizationEntry("social.title", "Friends / Online"),
            localizationEntry("social.friends", "Friends"),
            localizationEntry("social.online", "Online"),
        ),
    )
}
