package com.mirkori.inplacex.platform.localization

internal object SecondaryCatalog {
    val ru = localizationCatalog(
        name = "secondary.ru",
        entries = listOf(
            localizationEntry("shop.title", "Магазин"),
            localizationEntry("shop.hero.subtitle", "Расходуйте монеты осознанно: запасы, энергия и премиум собраны по категориям."),
            localizationEntry("shop.tab.boosts", "Запасы"),
            localizationEntry("shop.tab.premium", "Премиум"),
            localizationEntry("shop.hints", "Подсказки и бустеры"),
            localizationEntry("shop.hints.subtitle", "6 типов помощи для матчей и прохождения компании"),
            localizationEntry("shop.premium", "Подписки и покупки"),
            localizationEntry("shop.premium.subtitle", "Без рекламы, временный Pro, Pro и Pro+"),
            localizationEntry("shop.rewarded.title", "Бонус за рекламу"),
            localizationEntry("shop.rewarded.coins", "Посмотрите рекламу и получите 20 монет."),
            localizationEntry("shop.rewarded.watch", "Смотреть рекламу"),
            localizationEntry("shop.item.open_position", "Подсказка: открыть позицию"),
            localizationEntry("shop.item.check_digit", "Подсказка: проверить цифру"),
            localizationEntry("shop.item.check_position", "Подсказка: проверить позицию"),
            localizationEntry("shop.item.extra_moves", "Бустер: дополнительные ходы"),
            localizationEntry("shop.item.extra_time", "Бустер: дополнительное время"),
            localizationEntry("shop.item.energy", "Энергия компании +1"),
            localizationEntry("shop.product.remove_ads", "Отключить рекламу"),
            localizationEntry("shop.product.remove_ads.desc", "Разовая покупка. Убирает баннер и редкие рекламные показы после матча."),
            localizationEntry("shop.product.pro", "Подписка Pro"),
            localizationEntry("shop.product.pro.desc", "Авто режим таблицы + без баннера и постматчевой рекламы."),
            localizationEntry("shop.product.temporary_pro", "PRO на 1 час"),
            localizationEntry("shop.product.temporary_pro.desc", "Автотаблица и отключение рекламы на один час. Повторная покупка добавляет ещё час."),
            localizationEntry("shop.product.pro_plus", "Подписка Pro+"),
            localizationEntry("shop.product.pro_plus.desc", "Все бонусы Pro + бесконечные подсказки и полное отключение рекламы."),
            localizationEntry("shop.buy", "Купить"),
            localizationEntry("shop.subscribe", "Подписаться"),
            localizationEntry("shop.owned", "Куплено"),
            localizationEntry("shop.active", "Активно"),
            localizationEntry("shop.price", "{price} монет"),
            localizationEntry("shop.stock", "В запасе: {count}"),
            localizationEntry("shop.not_enough_coins", "Не хватает монет"),
            localizationEntry("shop.result.success", "Готово. Покупка применена к вашему профилю."),
            localizationEntry("shop.result.unavailable", "Действие сейчас недоступно. Баланс и профиль не изменены."),
            localizationEntry("shop.premium.unlocked", "Открыто"),
            localizationEntry("shop.premium.access", "Премиум-доступ"),
            localizationEntry("shop.temporary_pro.duration", "Доступ на 01:00:00"),
            localizationEntry("shop.temporary_pro.remaining", "Осталось {time}"),
            localizationEntry("shop.temporary_pro.included", "Входит в постоянный PRO"),
            localizationEntry("shop.temporary_pro.buy", "Купить за {price} монет"),
            localizationEntry("shop.temporary_pro.extend", "Продлить за {price} монет"),
            localizationEntry("company.title", "Компания"),
            localizationEntry("company.placeholder", "Одиночное прохождение, прогресс и серия уровней."),
            localizationEntry("company.list", "Уровни компании"),
            localizationEntry("profile.title", "Профиль"),
            localizationEntry("profile.account", "Аккаунт"),
            localizationEntry("profile.player", "Игрок"),
            localizationEntry("profile.progress", "Прогресс"),
            localizationEntry("profile.membership", "Статус покупок"),
            localizationEntry("profile.campaign_level", "Открытый уровень"),
            localizationEntry("profile.campaign_rating", "Общий рейтинг компании"),
            localizationEntry("profile.google_play.connected", "Google Play подключен. Прогресс можно синхронизировать."),
            localizationEntry("profile.google_play.connected.short", "Google Play подключен"),
            localizationEntry("profile.google_play.disconnected", "Google Play не подключен. Прогресс хранится только локально."),
            localizationEntry("profile.google_play.sign_in", "Войти через Google Play"),
            localizationEntry("profile.google_play.sign_out", "Выйти из Google Play"),
            localizationEntry("profile.google_play.title", "Google Play"),
            localizationEntry("profile.google_play.guest", "Гостевой режим"),
            localizationEntry("profile.ads_removed.yes", "Реклама отключена навсегда."),
            localizationEntry("profile.ads_removed.no", "Разовая покупка отключения рекламы не активна."),
            localizationEntry("profile.pro.yes", "Подписка Pro активна."),
            localizationEntry("profile.pro.no", "Подписка Pro не активна."),
            localizationEntry("profile.pro_plus.yes", "Подписка Pro+ активна."),
            localizationEntry("profile.pro_plus.no", "Подписка Pro+ не активна."),
            localizationEntry("profile.membership.ads", "Реклама"),
            localizationEntry("profile.membership.pro", "Pro"),
            localizationEntry("profile.membership.pro_plus", "Pro+"),
            localizationEntry("profile.membership.temporary_pro", "Временный Pro"),
            localizationEntry("profile.membership.active", "Активно"),
            localizationEntry("profile.membership.locked", "Заблокировано"),
            localizationEntry("profile.membership.remaining", "Осталось {time}"),
            localizationEntry("profile.membership.included", "Входит в подписку"),
            localizationEntry("profile.match_stats", "Статистика матчей"),
            localizationEntry("profile.match_stats.pve", "PvE"),
            localizationEntry("profile.match_stats.pvp", "PvP"),
            localizationEntry("profile.match_stats.result", "Победы: {wins} / Поражения: {losses}"),
            localizationEntry("profile.overview", "Обзор"),
            localizationEntry("profile.matches", "Матчи"),
            localizationEntry("profile.auth.signed_in", "Вход выполнен. Профиль готов к синхронизации."),
            localizationEntry("profile.auth.signed_out", "Вы вышли из Google Play. Локальный прогресс сохранён."),
            localizationEntry("profile.auth.unavailable", "Вход сейчас недоступен. Вы остаётесь в гостевом режиме, прогресс не потерян."),
            localizationEntry("profile.auth.in_progress", "Подключаем Google-аккаунт…"),
            localizationEntry("profile.auth.cancelled", "Вход отменён. Вы остаётесь в гостевом режиме."),
            localizationEntry("profile.auth.not_configured", "Google-вход пока не включён для этой сборки или сервера."),
            localizationEntry("profile.auth.rejected", "Google не подтвердил вход. Попробуйте ещё раз."),
            localizationEntry("settings.title", "Настройки"),
            localizationEntry("settings.description", "Здесь настраиваются язык и системные параметры оболочки."),
            localizationEntry("settings.language", "Язык"),
            localizationEntry("settings.language.ru", "Русский"),
            localizationEntry("settings.language.en", "Английский"),
            localizationEntry("settings.language.selector", "Выбор языка"),
            localizationEntry("social.description", "В этом разделе будут друзья, приглашения и статус в сети."),
            localizationEntry("social.hero.subtitle", "Друзья, приглашения и сетевые матчи."),
            localizationEntry("social.invites", "Приглашения"),
            localizationEntry("social.friends.empty", "Список друзей пока пуст."),
            localizationEntry("social.invites.empty", "Новых приглашений нет."),
            localizationEntry("social.status.preparing", "Онлайн готовится"),
            localizationEntry("social.status.preparing.description", "Локальная игра доступна; сетевые действия пока отключены."),
            localizationEntry("social.status.available", "Онлайн доступен"),
            localizationEntry("social.status.available.description", "Приватные коды и серверные дуэли работают"),
            localizationEntry("social.online.title", "Онлайн-матчи"),
            localizationEntry("social.online.description", "Быстрый матч или игра по коду."),
            localizationEntry("social.online.safety", "Профиль и прогресс не будут отправляться на сервер без подтверждённой авторизации."),
            localizationEntry("social.friends.subtitle", "Приглашайте игроков и управляйте списком"),
            localizationEntry("social.online.subtitle", "Готовьте онлайн-комнаты и активность в реальном времени"),
            localizationEntry("social.duel.online_title", "Онлайн-дуэль"),
            localizationEntry("social.duel.your_turn", "Ваш ход"),
            localizationEntry("social.duel.opponent_turn", "Ход соперника"),
            localizationEntry("social.duel.server_authoritative", "Ходы проверяет сервер"),
            localizationEntry("social.next_steps", "Следующие шаги для онлайна"),
            localizationEntry("social.next_steps.google_play", "Вход через Google Play"),
            localizationEntry("social.next_steps.cloud_sync", "Синхронизация прогресса в облаке"),
            localizationEntry("social.next_steps.friends_pvp", "Друзья, приглашения и PvP-комнаты"),
            localizationEntry("company.scene.stars", "Звёзды: {current} / {required}"),
            localizationEntry("company.scene.locked", "Заработайте больше звёзд, чтобы открыть следующую главу."),
            localizationEntry("company.scene.unlocked", "Следующая глава уже открыта."),
            localizationEntry("company.scene.history", "История"),
            localizationEntry("company.scene.history.subtitle", "Пройденные уровни"),
            localizationEntry("company.scene.energy", "Энергия"),
            localizationEntry("company.scene.current", "Текущий"),
            localizationEntry("company.scene.best", "Лучший рейтинг"),
            localizationEntry("company.scene.no_energy", "Нет энергии"),
            localizationEntry("company.scene.locked_level", "Уровень заблокирован"),
            localizationEntry("company.scene.level", "Уровень {value}"),
            localizationEntry("company.scene.subtitle", "Маршрут логических испытаний"),
            localizationEntry("company.chapter.number", "ГЛАВА {value}"),
            localizationEntry("company.chapter.title", "Логические цепи"),
            localizationEntry("company.chapter.progress", "{current} из {required} звёзд"),
            localizationEntry("company.chapter.reward", "Награда главы"),
            localizationEntry("company.state.completed", "Пройдено"),
            localizationEntry("company.state.locked", "Заблокировано"),
            localizationEntry("company.lock.stars", "Нужно {value} звёзд"),
            localizationEntry("company.lock.previous", "Сначала пройдите предыдущий уровень"),
            localizationEntry("company.mission.title.standard", "Кодовая матрица"),
            localizationEntry("company.mission.title.spike", "Двойная проверка"),
            localizationEntry("company.mission.title.hardcore", "Контрольный рубеж"),
            localizationEntry("company.difficulty.easy", "Легко"),
            localizationEntry("company.difficulty.medium", "Средне"),
            localizationEntry("company.difficulty.hard", "Сложно"),
            localizationEntry("company.difficulty.hardcore", "Эксперт"),
            localizationEntry("company.mission.objective", "Угадайте код из {digits} цифр за {moves} ходов"),
            localizationEntry("company.mission.time", "Время {value}"),
            localizationEntry("company.mission.repeats.allowed", "Повторы разрешены"),
            localizationEntry("company.mission.repeats.forbidden", "Без повторов"),
            localizationEntry("company.mission.best", "Лучший рейтинг: {value}/10"),
            localizationEntry("company.mission.best.empty", "Личный рекорд ещё не установлен"),
            localizationEntry("company.action.play", "Играть уровень {value} — 1 энергия"),
            localizationEntry("company.action.restore_energy", "Пополнить энергию"),
            localizationEntry("company.action.need_stars", "Нужно {value} звёзд"),
            localizationEntry("company.action.rules", "Правила уровня"),
            localizationEntry("company.rules.title", "Правила уровня {value}"),
            localizationEntry("company.rules.time", "На решение даётся {value}."),
            localizationEntry("company.rules.repeats.allowed", "Одинаковые цифры в коде могут повторяться."),
            localizationEntry("company.rules.repeats.forbidden", "Каждая цифра в коде используется только один раз."),
            localizationEntry("company.rules.rating", "Рейтинг зависит от числа ходов, времени, подсказок и усилителей."),
            localizationEntry("company.history.title", "История"),
            localizationEntry("company.history.subtitle", "Пройденные миссии и лучшие результаты"),
            localizationEntry("company.history.empty", "Здесь появятся пройденные уровни."),
            localizationEntry("company.action.close", "Закрыть"),
            localizationEntry("company.dialog.exit_title", "Выйти из прохождения компании?"),
            localizationEntry("company.dialog.exit_text", "Прогресс текущей попытки будет потерян."),
            localizationEntry("company.dialog.exit_confirm", "Выйти"),
            localizationEntry("company.dialog.stay", "Остаться"),
            localizationEntry("company.dialog.complete_title", "Уровень пройден"),
            localizationEntry("company.dialog.failed_title", "Уровень не пройден"),
            localizationEntry("company.dialog.level", "Уровень {value}"),
            localizationEntry("company.dialog.rating", "Рейтинг: {value}/10"),
            localizationEntry("company.dialog.stars", "Звёзды: {value}"),
        ),
    )

    val en = localizationCatalog(
        name = "secondary.en",
        entries = listOf(
            localizationEntry("shop.title", "Shop"),
            localizationEntry("shop.hero.subtitle", "Spend coins with confidence: supplies, energy, and premium are grouped by category."),
            localizationEntry("shop.tab.boosts", "Supplies"),
            localizationEntry("shop.tab.premium", "Premium"),
            localizationEntry("shop.hints", "Hints and boosts"),
            localizationEntry("shop.hints.subtitle", "6 helper types for matches and campaign runs"),
            localizationEntry("shop.premium", "Subscriptions and purchases"),
            localizationEntry("shop.premium.subtitle", "Ad-free, temporary Pro, Pro and Pro+ access"),
            localizationEntry("shop.rewarded.title", "Ad reward"),
            localizationEntry("shop.rewarded.coins", "Watch an ad and receive 20 coins."),
            localizationEntry("shop.rewarded.watch", "Watch ad"),
            localizationEntry("shop.item.open_position", "Hint: open position"),
            localizationEntry("shop.item.check_digit", "Hint: check digit"),
            localizationEntry("shop.item.check_position", "Hint: check position"),
            localizationEntry("shop.item.extra_moves", "Boost: extra moves"),
            localizationEntry("shop.item.extra_time", "Boost: extra time"),
            localizationEntry("shop.item.energy", "Company energy +1"),
            localizationEntry("shop.product.remove_ads", "Remove ads"),
            localizationEntry("shop.product.remove_ads.desc", "One-time purchase. Removes banner ads and rare post-match ads."),
            localizationEntry("shop.product.pro", "Pro subscription"),
            localizationEntry("shop.product.pro.desc", "Auto table mode + no banner and no post-match ads."),
            localizationEntry("shop.product.temporary_pro", "PRO for 1 hour"),
            localizationEntry("shop.product.temporary_pro.desc", "Auto table mode and no ads for one hour. Another purchase adds one more hour."),
            localizationEntry("shop.product.pro_plus", "Pro+ subscription"),
            localizationEntry("shop.product.pro_plus.desc", "Everything in Pro + infinite hints and full ad removal."),
            localizationEntry("shop.buy", "Buy"),
            localizationEntry("shop.subscribe", "Subscribe"),
            localizationEntry("shop.owned", "Owned"),
            localizationEntry("shop.active", "Active"),
            localizationEntry("shop.price", "{price} coins"),
            localizationEntry("shop.stock", "In stock: {count}"),
            localizationEntry("shop.not_enough_coins", "Not enough coins"),
            localizationEntry("shop.result.success", "Done. The purchase was applied to your profile."),
            localizationEntry("shop.result.unavailable", "This action is unavailable right now. Your balance and profile were not changed."),
            localizationEntry("shop.premium.unlocked", "Unlocked"),
            localizationEntry("shop.premium.access", "Premium access"),
            localizationEntry("shop.temporary_pro.duration", "Access for 01:00:00"),
            localizationEntry("shop.temporary_pro.remaining", "{time} remaining"),
            localizationEntry("shop.temporary_pro.included", "Included with permanent PRO"),
            localizationEntry("shop.temporary_pro.buy", "Buy for {price} coins"),
            localizationEntry("shop.temporary_pro.extend", "Extend for {price} coins"),
            localizationEntry("company.title", "Company"),
            localizationEntry("company.placeholder", "Solo progression, milestones and curated levels."),
            localizationEntry("company.list", "Company Levels"),
            localizationEntry("profile.title", "Profile"),
            localizationEntry("profile.account", "Account"),
            localizationEntry("profile.player", "Player"),
            localizationEntry("profile.progress", "Progress"),
            localizationEntry("profile.membership", "Purchase status"),
            localizationEntry("profile.campaign_level", "Unlocked level"),
            localizationEntry("profile.campaign_rating", "Total company rating"),
            localizationEntry("profile.google_play.connected", "Google Play is connected. Progress can be synced."),
            localizationEntry("profile.google_play.connected.short", "Google Play connected"),
            localizationEntry("profile.google_play.disconnected", "Google Play is not connected. Progress is local only."),
            localizationEntry("profile.google_play.sign_in", "Sign in with Google Play"),
            localizationEntry("profile.google_play.sign_out", "Sign out of Google Play"),
            localizationEntry("profile.google_play.title", "Google Play"),
            localizationEntry("profile.google_play.guest", "Guest mode"),
            localizationEntry("profile.ads_removed.yes", "Ads are removed permanently."),
            localizationEntry("profile.ads_removed.no", "The one-time ad removal purchase is not active."),
            localizationEntry("profile.pro.yes", "Pro subscription is active."),
            localizationEntry("profile.pro.no", "Pro subscription is not active."),
            localizationEntry("profile.pro_plus.yes", "Pro+ subscription is active."),
            localizationEntry("profile.pro_plus.no", "Pro+ subscription is not active."),
            localizationEntry("profile.membership.ads", "Ads"),
            localizationEntry("profile.membership.pro", "Pro"),
            localizationEntry("profile.membership.pro_plus", "Pro+"),
            localizationEntry("profile.membership.temporary_pro", "Temporary Pro"),
            localizationEntry("profile.membership.active", "Active"),
            localizationEntry("profile.membership.locked", "Locked"),
            localizationEntry("profile.membership.remaining", "{time} remaining"),
            localizationEntry("profile.membership.included", "Included in subscription"),
            localizationEntry("profile.match_stats", "Match stats"),
            localizationEntry("profile.match_stats.pve", "PvE"),
            localizationEntry("profile.match_stats.pvp", "PvP"),
            localizationEntry("profile.match_stats.result", "W {wins} / L {losses}"),
            localizationEntry("profile.overview", "Overview"),
            localizationEntry("profile.matches", "Matches"),
            localizationEntry("profile.auth.signed_in", "Signed in. Your profile is ready to sync."),
            localizationEntry("profile.auth.signed_out", "You signed out of Google Play. Local progress was preserved."),
            localizationEntry("profile.auth.unavailable", "Sign-in is unavailable right now. You remain in guest mode and your progress is safe."),
            localizationEntry("profile.auth.in_progress", "Connecting your Google account…"),
            localizationEntry("profile.auth.cancelled", "Sign-in was cancelled. You remain in guest mode."),
            localizationEntry("profile.auth.not_configured", "Google sign-in is not enabled for this build or server yet."),
            localizationEntry("profile.auth.rejected", "Google could not verify this sign-in. Please try again."),
            localizationEntry("settings.title", "Settings"),
            localizationEntry("settings.description", "Use this panel for language and shell system settings."),
            localizationEntry("settings.language", "Language"),
            localizationEntry("settings.language.ru", "Russian"),
            localizationEntry("settings.language.en", "English"),
            localizationEntry("settings.language.selector", "Select language"),
            localizationEntry("social.description", "This section will handle friends, invites and online presence."),
            localizationEntry("social.hero.subtitle", "Friends, invitations, and online matches."),
            localizationEntry("social.invites", "Invitations"),
            localizationEntry("social.friends.empty", "Your friends list is empty."),
            localizationEntry("social.invites.empty", "There are no new invitations."),
            localizationEntry("social.status.preparing", "Online is being prepared"),
            localizationEntry("social.status.preparing.description", "Local play is available; network actions are currently disabled."),
            localizationEntry("social.status.available", "Online is available"),
            localizationEntry("social.status.available.description", "Private codes and server duels are working"),
            localizationEntry("social.online.title", "Online matches"),
            localizationEntry("social.online.description", "Quick match or play by code."),
            localizationEntry("social.online.safety", "Your profile and progress will not be sent to the server without verified authentication."),
            localizationEntry("social.friends.subtitle", "Invite players and manage your list"),
            localizationEntry("social.online.subtitle", "Prepare online rooms and live activity"),
            localizationEntry("social.duel.online_title", "Online duel"),
            localizationEntry("social.duel.your_turn", "Your turn"),
            localizationEntry("social.duel.opponent_turn", "Opponent's turn"),
            localizationEntry("social.duel.server_authoritative", "Moves are verified by the server"),
            localizationEntry("social.next_steps", "Next online steps"),
            localizationEntry("social.next_steps.google_play", "Google Play sign-in"),
            localizationEntry("social.next_steps.cloud_sync", "Cloud progress sync"),
            localizationEntry("social.next_steps.friends_pvp", "Friends, invites and PvP rooms"),
            localizationEntry("company.scene.stars", "Stars: {current} / {required}"),
            localizationEntry("company.scene.locked", "Earn more stars to unlock the next chapter."),
            localizationEntry("company.scene.unlocked", "The next chapter is already unlocked."),
            localizationEntry("company.scene.history", "History"),
            localizationEntry("company.scene.history.subtitle", "Completed levels"),
            localizationEntry("company.scene.energy", "Energy"),
            localizationEntry("company.scene.current", "Current"),
            localizationEntry("company.scene.best", "Best rating"),
            localizationEntry("company.scene.no_energy", "No energy"),
            localizationEntry("company.scene.locked_level", "Level locked"),
            localizationEntry("company.scene.level", "Level {value}"),
            localizationEntry("company.scene.subtitle", "Your route through logic missions"),
            localizationEntry("company.chapter.number", "CHAPTER {value}"),
            localizationEntry("company.chapter.title", "Logic chains"),
            localizationEntry("company.chapter.progress", "{current} of {required} stars"),
            localizationEntry("company.chapter.reward", "Chapter reward"),
            localizationEntry("company.state.completed", "Completed"),
            localizationEntry("company.state.locked", "Locked"),
            localizationEntry("company.lock.stars", "Requires {value} stars"),
            localizationEntry("company.lock.previous", "Complete the previous level first"),
            localizationEntry("company.mission.title.standard", "Code matrix"),
            localizationEntry("company.mission.title.spike", "Double check"),
            localizationEntry("company.mission.title.hardcore", "Control point"),
            localizationEntry("company.difficulty.easy", "Easy"),
            localizationEntry("company.difficulty.medium", "Medium"),
            localizationEntry("company.difficulty.hard", "Hard"),
            localizationEntry("company.difficulty.hardcore", "Expert"),
            localizationEntry("company.mission.objective", "Guess a {digits}-digit code in {moves} moves"),
            localizationEntry("company.mission.time", "Time {value}"),
            localizationEntry("company.mission.repeats.allowed", "Repeats allowed"),
            localizationEntry("company.mission.repeats.forbidden", "No repeats"),
            localizationEntry("company.mission.best", "Best rating: {value}/10"),
            localizationEntry("company.mission.best.empty", "No personal best yet"),
            localizationEntry("company.action.play", "Play level {value} — 1 energy"),
            localizationEntry("company.action.restore_energy", "Restore energy"),
            localizationEntry("company.action.need_stars", "Requires {value} stars"),
            localizationEntry("company.action.rules", "Level rules"),
            localizationEntry("company.rules.title", "Level {value} rules"),
            localizationEntry("company.rules.time", "You have {value} to solve the code."),
            localizationEntry("company.rules.repeats.allowed", "The same digit may appear more than once in the code."),
            localizationEntry("company.rules.repeats.forbidden", "Each digit is used only once in the code."),
            localizationEntry("company.rules.rating", "Your rating depends on moves, time, hints and boosts."),
            localizationEntry("company.history.title", "History"),
            localizationEntry("company.history.subtitle", "Completed missions and personal bests"),
            localizationEntry("company.history.empty", "Completed levels will appear here."),
            localizationEntry("company.action.close", "Close"),
            localizationEntry("company.dialog.exit_title", "Exit campaign run?"),
            localizationEntry("company.dialog.exit_text", "Progress in the current attempt will be lost."),
            localizationEntry("company.dialog.exit_confirm", "Exit"),
            localizationEntry("company.dialog.stay", "Stay"),
            localizationEntry("company.dialog.complete_title", "Level complete"),
            localizationEntry("company.dialog.failed_title", "Level failed"),
            localizationEntry("company.dialog.level", "Level {value}"),
            localizationEntry("company.dialog.rating", "Rating: {value}/10"),
            localizationEntry("company.dialog.stars", "Stars: {value}"),
        ),
    )
}
