package com.mirkori.inplacex.platform.localization

internal object SecondaryCatalog {
    val ru = localizationCatalog(
        name = "secondary.ru",
        entries = listOf(
            localizationEntry("social.reference.title", "Друзья"),
            localizationEntry("social.reference.subtitle", "Играйте и соревнуйтесь с друзьями!"),
            localizationEntry("social.reference.online_count", "Онлайн: {count} друзей"),
            localizationEntry("social.reference.your_friends", "Ваши друзья"),
            localizationEntry("social.reference.online_friends", "Онлайн друзья"),
            localizationEntry("social.reference.all", "Все"),
            localizationEntry("social.reference.empty", "Пригласите друзей, чтобы играть вместе."),
            localizationEntry("social.reference.request", "Заявка в друзья"),
            localizationEntry("social.reference.requests_count", "Все заявки: {count}"),
            localizationEntry("social.reference.requests_title", "Заявки в друзья"),
            localizationEntry("social.reference.no_requests", "Новых заявок нет"),
            localizationEntry("social.reference.open", "Открыть"),
            localizationEntry("social.reference.invite", "Пригласить"),
            localizationEntry("social.reference.invite_description", "Отправьте код\nсвоим друзьям"),
            localizationEntry("social.reference.find_match", "Найти матч"),
            localizationEntry("social.reference.match_description", "Случайный соперник\nонлайн"),
            localizationEntry("social.reference.matches", "Онлайн-матчи"),
            localizationEntry("social.reference.matches_description", "Текущие и завершённые матчи"),
            localizationEntry("shop.title", "Магазин"),
            localizationEntry("shop.hero.subtitle", "Запасы, подсказки и премиум"),
            localizationEntry("shop.tab.boosts", "Запасы"),
            localizationEntry("shop.tab.premium", "Премиум"),
            localizationEntry("shop.hints", "Подсказки и бустеры"),
            localizationEntry("shop.hints.subtitle", "6 типов помощи для матчей и прохождения компании"),
            localizationEntry("shop.premium", "Покупки и доступ"),
            localizationEntry("shop.premium.subtitle", "Без рекламы, временный Pro, Pro и Pro+"),
            localizationEntry("shop.premium.overview.title", "Премиум обзор"),
            localizationEntry("shop.premium.overview.pro.title", "Получите PRO привилегии"),
            localizationEntry("shop.premium.overview.pro.description", "Расширенные возможности и автоматизация на время."),
            localizationEntry("shop.premium.overview.maximum.title", "Максимум возможностей"),
            localizationEntry("shop.premium.overview.maximum.description", "Все бонусы и безлимитные подсказки для комфортной игры."),
            localizationEntry("shop.rewarded.title", "Бонус за рекламу"),
            localizationEntry("shop.rewarded.coins", "Смотрите рекламу и получайте награды каждый день"),
            localizationEntry("shop.rewarded.watch", "Смотреть"),
            localizationEntry("shop.item.open_position", "Подсказка: открыть позицию"),
            localizationEntry("shop.item.check_digit", "Подсказка: проверить цифру"),
            localizationEntry("shop.item.check_position", "Подсказка: проверить позицию"),
            localizationEntry("shop.item.extra_moves", "Бустер: дополнительные ходы"),
            localizationEntry("shop.item.extra_time", "Бустер: дополнительное время"),
            localizationEntry("shop.item.energy", "Энергия компании +1"),
            localizationEntry("shop.item.open_position.desc", "Откройте цифру на одной позиции кода."),
            localizationEntry("shop.item.check_digit.desc", "Проверьте, есть ли выбранная цифра в коде."),
            localizationEntry("shop.item.check_position.desc", "Проверьте выбранную цифру на конкретной позиции."),
            localizationEntry("shop.item.extra_moves.desc", "Добавьте попытки в матче с ограничением ходов."),
            localizationEntry("shop.item.extra_time.desc", "Добавьте время в матче с таймером."),
            localizationEntry("shop.item.energy.desc", "Восстановите одну единицу энергии для компании."),
            localizationEntry("shop.product.remove_ads", "Отключить рекламу"),
            localizationEntry("shop.product.remove_ads.desc", "Разовая покупка. Убирает баннер и редкие рекламные показы после матча."),
            localizationEntry("shop.product.pro", "Pro-доступ"),
            localizationEntry("shop.product.pro.desc", "Авто режим таблицы + без баннера и постматчевой рекламы."),
            localizationEntry("shop.product.temporary_pro", "PRO на 1 час"),
            localizationEntry("shop.product.temporary_pro.desc", "Автотаблица и отключение рекламы на один час. Повторная покупка добавляет ещё час."),
            localizationEntry("shop.product.pro_plus", "Pro+ доступ"),
            localizationEntry("shop.product.pro_plus.desc", "Все бонусы Pro + бесконечные подсказки и полное отключение рекламы."),
            localizationEntry("shop.buy", "Купить"),
            localizationEntry("shop.subscribe", "Купить доступ"),
            localizationEntry("shop.product.prepaid_duration", "Срок доступа: {duration}. Разовая оплата, без автопродления."),
            localizationEntry("shop.product.prepaid_duration_unknown", "Доступ на срок после разовой оплаты, без автопродления."),
            localizationEntry("shop.product.duration_days", "{count} дн."),
            localizationEntry("shop.product.duration_hours", "{count} ч."),
            localizationEntry("shop.product.duration_minutes", "{count} мин."),
            localizationEntry("shop.owned", "Куплено"),
            localizationEntry("shop.active", "Активно"),
            localizationEntry("shop.price", "{price} монет"),
            localizationEntry("shop.stock", "В запасе: {count}"),
            localizationEntry("shop.not_enough_coins", "Не хватает монет"),
            localizationEntry("shop.result.success", "Готово. Локальный бонус применён."),
            localizationEntry("shop.result.unavailable", "Действие сейчас недоступно. Баланс и профиль не изменены."),
            localizationEntry("shop.billing.checking", "Проверяем покупки на сервере…"),
            localizationEntry("shop.billing.ready", "Покупки Mirkori Games синхронизированы."),
            localizationEntry("shop.billing.unavailable", "Покупки сейчас недоступны. Локальные монеты и бонусы не изменены."),
            localizationEntry("shop.billing.unavailable_short", "Недоступно"),
            localizationEntry("shop.billing.open_profile", "Открыть профиль и войти"),
            localizationEntry("shop.billing.retry_payment", "Повторить оплату"),
            localizationEntry("shop.billing.refresh", "Проверить покупки"),
            localizationEntry("shop.billing.buy_for", "Купить за {price}"),
            localizationEntry("shop.billing.checkout_opened", "Оплата открыта во внешнем браузере. Доступ появится только после подтверждения сервера."),
            localizationEntry("shop.billing.awaiting_payment", "Платёж пока не подтверждён. Проверьте статус или снова откройте оплату."),
            localizationEntry("shop.billing.awaiting_entitlement", "Платёж найден, но сервер ещё не подтвердил доступ. Ничего локально не включено."),
            localizationEntry("shop.billing.confirmed", "Сервер подтвердил покупку. Доступ обновлён."),
            localizationEntry("shop.billing.cancelled", "Платёж отменён. Доступ не изменён."),
            localizationEntry("shop.billing.refunded", "Возврат подтверждён сервером. Доступ обновлён."),
            localizationEntry("shop.billing.checkout_expired", "Срок ссылки истёк. Новая оплата будет доступна только после серверного подтверждения отмены исходного платежа."),
            localizationEntry("shop.billing.link_required", "Для оплаты войдите в Mirkori Games. Гостевой прогресс останется на месте."),
            localizationEntry("shop.billing.provider_unavailable", "Платёжный провайдер временно недоступен (503). Попробуйте позже тем же действием."),
            localizationEntry("shop.billing.offline", "Нет сети. Покупки не изменены; подтверждённый временный доступ сохранён только до окончания срока."),
            localizationEntry("shop.billing.retry_required", "Не удалось проверить покупку. Доступ не изменён; повторите попытку."),
            localizationEntry("shop.billing.already_active", "Сервер сообщает, что этот доступ уже активен."),
            localizationEntry("shop.billing.busy", "Сначала завершите или проверьте уже начатую оплату."),
            localizationEntry("shop.billing.configuration_required", "Каталог покупок не настроен для этой сборки."),
            localizationEntry("shop.premium.unlocked", "Открыто"),
            localizationEntry("shop.premium.access", "Премиум-доступ"),
            localizationEntry("shop.temporary_pro.duration", "Доступ на 01:00:00"),
            localizationEntry("shop.temporary_pro.remaining", "Осталось {time}"),
            localizationEntry("shop.temporary_pro.included", "Входит в постоянный PRO"),
            localizationEntry("shop.temporary_pro.buy", "Купить за {price} монет"),
            localizationEntry("shop.temporary_pro.extend", "Продлить за {price} монет"),
            localizationEntry("company.title", "Компания"),
            localizationEntry("company.placeholder", "Одиночное прохождение, прогресс и серия уровней."),
            localizationEntry("company.list", "Уровни компании"),
            localizationEntry("profile.title", "Профиль"),
            localizationEntry("profile.account", "Аккаунт"),
            localizationEntry("profile.connections", "Подключения"),
            localizationEntry("profile.connection.connected", "Подключено"),
            localizationEntry("profile.connection.guest", "Гостевой режим"),
            localizationEntry("profile.connection.connecting", "Подключение…"),
            localizationEntry("profile.connection.unavailable", "Недоступно"),
            localizationEntry("profile.purchases_and_subscriptions", "Покупки и подписки"),
            localizationEntry("profile.premium_account", "Премиум-аккаунт"),
            localizationEntry("profile.premium.active", "Активен"),
            localizationEntry("profile.premium.inactive", "Не активен"),
            localizationEntry("profile.player", "Игрок"),
            localizationEntry("profile.progress", "Прогресс"),
            localizationEntry("profile.membership", "Статус покупок"),
            localizationEntry("profile.campaign_level", "Открытый уровень"),
            localizationEntry("profile.campaign_rating", "Рейтинг компании"),
            localizationEntry("profile.google_play.connected", "Google Play подключен. Прогресс можно синхронизировать."),
            localizationEntry("profile.google_play.connected.short", "Подключено"),
            localizationEntry("profile.google_play.disconnected.short", "Не подключено"),
            localizationEntry("profile.google_play.disconnected", "Google Play не подключен. Прогресс хранится только локально."),
            localizationEntry("profile.google_play.sign_in", "Войти через Google Play"),
            localizationEntry("profile.google_play.sign_out", "Выйти из Google Play"),
            localizationEntry("profile.google_play.title", "Google Play"),
            localizationEntry("profile.google_play.guest", "Гостевой режим"),
            localizationEntry("profile.mirkori.title", "Mirkori Games"),
            localizationEntry("profile.mirkori.connected.short", "Mirkori Games подключён"),
            localizationEntry("profile.mirkori.guest.short", "Гостевой профиль Mirkori Games"),
            localizationEntry("profile.mirkori.initializing", "Подключаем Mirkori Games…"),
            localizationEntry("profile.mirkori.unavailable.short", "Mirkori Games недоступен"),
            localizationEntry("profile.mirkori.connected", "Единый аккаунт подключён. Этот игровой профиль принадлежит вашему аккаунту Mirkori Games."),
            localizationEntry("profile.mirkori.guest", "Гостевой профиль создан. Войдите в Mirkori Games, чтобы закрепить его за единым аккаунтом."),
            localizationEntry("profile.mirkori.unavailable", "Не удалось связаться с Mirkori Games. Локальный прогресс сохранён; можно повторить позже."),
            localizationEntry("profile.mirkori.player_id", "ID игрока: …{id}"),
            localizationEntry("profile.mirkori.copy_player_id", "Скопировать ID игрока"),
            localizationEntry("profile.mirkori.handle", "Публичный ID"),
            localizationEntry("profile.mirkori.handle.not_set", "Публичный ID пока не задан"),
            localizationEntry("profile.mirkori.handle.change", "Изменить публичный ID"),
            localizationEntry("profile.mirkori.handle.rules", "От 3 до 24 латинских букв, цифр или знаков подчёркивания."),
            localizationEntry("profile.mirkori.handle.save", "Сохранить"),
            localizationEntry("profile.mirkori.handle.cancel", "Отмена"),
            localizationEntry("profile.mirkori.handle.saved", "Публичный ID сохранён."),
            localizationEntry("profile.mirkori.handle.taken", "Этот публичный ID уже занят."),
            localizationEntry("profile.mirkori.handle.invalid", "Проверьте формат публичного ID."),
            localizationEntry("profile.mirkori.handle.unavailable", "Сейчас изменить публичный ID не удалось."),
            localizationEntry("profile.mirkori.name", "Имя игрока"),
            localizationEntry("profile.mirkori.name.change", "Изменить имя"),
            localizationEntry("profile.mirkori.name.rules", "Введите имя, которое будут видеть другие игроки."),
            localizationEntry("profile.mirkori.name.save", "Сохранить"),
            localizationEntry("profile.mirkori.name.saved", "Имя сохранено."),
            localizationEntry("profile.mirkori.name.invalid", "Имя не может быть пустым."),
            localizationEntry("profile.mirkori.name.unavailable", "Сейчас изменить имя не удалось."),
            localizationEntry("profile.mirkori.avatar.change", "Изменить аватар"),
            localizationEntry("profile.mirkori.avatar.choose", "Выберите картинку профиля."),
            localizationEntry("profile.mirkori.avatar.saved", "Аватар сохранён."),
            localizationEntry("profile.mirkori.avatar.invalid", "Эту картинку выбрать нельзя."),
            localizationEntry("profile.mirkori.avatar.unavailable", "Сейчас изменить аватар не удалось."),
            localizationEntry("profile.mirkori.sign_in", "Войти в Mirkori Games"),
            localizationEntry("profile.mirkori.in_progress", "Готовим безопасный вход…"),
            localizationEntry("profile.mirkori.browser_opened", "Завершите вход в открывшемся браузере и подтвердите возврат в игру."),
            localizationEntry("profile.mirkori.connected.success", "Аккаунт Mirkori Games подключён."),
            localizationEntry("profile.mirkori.conflict", "В этом аккаунте уже есть другой профиль InplaceX. Ни один профиль не изменён."),
            localizationEntry("profile.google.conflict.title", "Этот Google-аккаунт уже используется"),
            localizationEntry("profile.google.conflict.message", "Для этого Google-аккаунта уже существует профиль InplaceX. Войти в него? Текущий гостевой профиль не будет удалён, а локальный прогресс останется на телефоне."),
            localizationEntry("profile.google.conflict.use_existing", "Войти в существующий профиль"),
            localizationEntry("profile.google.conflict.keep_current", "Остаться в текущем"),
            localizationEntry("profile.google.conflict.kept", "Вы остались в текущем профиле. Ничего не изменено."),
            localizationEntry("profile.mirkori.rejected", "Не удалось подтвердить вход. Запустите его ещё раз из игры."),
            localizationEntry("profile.ads_removed.yes", "Реклама отключена навсегда."),
            localizationEntry("profile.ads_removed.no", "Разовая покупка отключения рекламы не активна."),
            localizationEntry("profile.pro.yes", "Pro-доступ активен."),
            localizationEntry("profile.pro.no", "Pro-доступ не активен."),
            localizationEntry("profile.pro_plus.yes", "Pro+ доступ активен."),
            localizationEntry("profile.pro_plus.no", "Pro+ доступ не активен."),
            localizationEntry("profile.membership.ads", "Реклама"),
            localizationEntry("profile.membership.pro", "Pro"),
            localizationEntry("profile.membership.pro_plus", "Pro+"),
            localizationEntry("profile.membership.temporary_pro", "Временный Pro"),
            localizationEntry("profile.membership.active", "Активно"),
            localizationEntry("profile.membership.locked", "Заблокировано"),
            localizationEntry("profile.membership.remaining", "Осталось {time}"),
            localizationEntry("profile.membership.included", "Входит в платный доступ"),
            localizationEntry("profile.match_stats", "Статистика матчей"),
            localizationEntry("profile.match_stats.pve", "PvE"),
            localizationEntry("profile.match_stats.pvp", "PvP"),
            localizationEntry("profile.match_stats.result", "Победы: {wins} / Поражения: {losses}"),
            localizationEntry("profile.overview", "Обзор"),
            localizationEntry("profile.matches", "Матчи сыграно"),
            localizationEntry("profile.auth.signed_in", "Вход выполнен. Профиль готов к синхронизации."),
            localizationEntry("profile.auth.signed_out", "Google Play на этом устройстве отключён. Аккаунт Mirkori Games не изменён; локальный прогресс сохранён."),
            localizationEntry("profile.auth.unavailable", "Вход сейчас недоступен. Вы остаётесь в гостевом режиме, прогресс не потерян."),
            localizationEntry("profile.auth.in_progress", "Подключаем Google-аккаунт…"),
            localizationEntry("profile.auth.cancelled", "Вход отменён. Вы остаётесь в гостевом режиме."),
            localizationEntry("profile.auth.not_configured", "Google-вход пока не включён для этой сборки или сервера."),
            localizationEntry("profile.auth.rejected", "Google не подтвердил вход. Попробуйте ещё раз."),
            localizationEntry("settings.title", "Настройки"),
            localizationEntry("settings.description", "Здесь настраиваются язык и системные параметры оболочки."),
            localizationEntry("settings.language", "Язык"),
            localizationEntry("settings.language.ru", "Русский"),
            localizationEntry("settings.language.en", "Английский"),
            localizationEntry("settings.language.selector", "Выбор языка"),
            localizationEntry("settings.ad_privacy", "Настройки рекламы"),
            localizationEntry("settings.feedback.title", "Звук и отклик"),
            localizationEntry("settings.vibration", "Вибрация"),
            localizationEntry("settings.vibration.description", "Отклик на игровые действия и результаты."),
            localizationEntry("settings.sound", "Звуки"),
            localizationEntry("settings.sound.description", "Кнопки, подсказки, ошибки и завершение матча."),
            localizationEntry("settings.music", "Музыка"),
            localizationEntry("settings.music.description", "Фоновая музыка во время игры и в меню."),
            localizationEntry("settings.information.title", "Информация и поддержка"),
            localizationEntry("settings.contact", "Связаться с нами"),
            localizationEntry("settings.terms", "Условия использования"),
            localizationEntry("settings.privacy", "Политика конфиденциальности"),
            localizationEntry("settings.about", "О нас"),
            localizationEntry("settings.open_source_licenses", "Лицензии открытого кода"),
            localizationEntry("ads.privacy.title", "Конфиденциальность рекламы"),
            localizationEntry("ads.privacy.description", "Рекламные сервисы могут обрабатывать данные устройства для подбора, измерения и защиты рекламы. Разрешить персонализированную рекламу? При отказе приложение сможет показывать только неперсонализированную рекламу."),
            localizationEntry("ads.privacy.accept", "Разрешить"),
            localizationEntry("ads.privacy.decline", "Без персонализации"),
            localizationEntry("ads.privacy.status.undecided", "не выбрано"),
            localizationEntry("ads.privacy.status.accepted", "разрешена персонализация"),
            localizationEntry("ads.privacy.status.declined", "без персонализации"),
            localizationEntry("social.description", "В этом разделе будут друзья, приглашения и статус в сети."),
            localizationEntry("social.hero.subtitle", "Друзья, приглашения и сетевые матчи."),
            localizationEntry("social.invites", "Приглашения"),
            localizationEntry("social.invites.incoming.notice", "Новых приглашений: {count}"),
            localizationEntry("social.invites.incoming.title", "Приглашение в игру"),
            localizationEntry("social.invites.accept", "Принять"),
            localizationEntry("social.invites.open", "Открыть друзей"),
            localizationEntry("social.friends.empty", "Список друзей пока пуст."),
            localizationEntry("social.friend.saved", "Друг сохранён в вашем списке"),
            localizationEntry("social.friend.match.title", "Игра с {name}"),
            localizationEntry("social.friend.match.title.generic", "Игра с другом"),
            localizationEntry("social.friend.match.description", "Выберите формат игры и отправьте адресное приглашение."),
            localizationEntry("social.friend.add.title", "Добавить друга"),
            localizationEntry("social.friend.add.description", "Попросите друга скопировать полный ID игрока из профиля."),
            localizationEntry("social.friend.add.name", "Имя друга"),
            localizationEntry("social.friend.add.player_id", "ID игрока"),
            localizationEntry("social.friend.add.action", "Добавить"),
            localizationEntry("social.friend.add.added", "Добавлен"),
            localizationEntry("social.friend.add.invalid_name", "Введите имя друга."),
            localizationEntry("social.friend.add.invalid_player_id", "ID игрока должен быть полным UUID."),
            localizationEntry("social.friend.add.self", "Нельзя добавить самого себя."),
            localizationEntry("social.friend.add.saved", "Друг добавлен."),
            localizationEntry("social.friend.request.sent", "Заявка в друзья отправлена."),
            localizationEntry("social.friend.request.sent.short", "Отправлена"),
            localizationEntry("social.friend.request.incoming", "Хочет добавить вас в друзья"),
            localizationEntry("social.friend.request.accept", "Принять"),
            localizationEntry("social.friend.request.accepted", "Заявка принята."),
            localizationEntry("social.friend.request.rejected", "Заявку выполнить не удалось."),
            localizationEntry("social.friend.request.unavailable", "Сервис друзей сейчас недоступен."),
            localizationEntry("social.friend.request.root_notice", "{name} предлагает дружить."),
            localizationEntry("social.friend.request.open", "Открыть запрос"),
            localizationEntry("social.friend.request.notification.title", "Новая заявка в друзья"),
            localizationEntry("social.friend.request.notification.message", "{name} хочет добавить вас в друзья."),
            localizationEntry("social.friend.search.query", "Имя или публичный ID"),
            localizationEntry("social.friend.search.action", "Найти"),
            localizationEntry("social.friend.search.invalid", "Введите имя или публичный ID игрока."),
            localizationEntry("social.friend.search.empty", "Игроки не найдены."),
            localizationEntry("social.friend.search.unavailable", "Поиск сейчас недоступен. Попробуйте позже."),
            localizationEntry("social.friend.search.close", "Закрыть"),
            localizationEntry("social.friend.id_fallback", "ID: …{id}"),
            localizationEntry("social.invites.empty", "Новых приглашений нет."),
            localizationEntry("social.invites.guide", "Создайте код и отправьте его другу."),
            localizationEntry("social.invites.screen_description", "Создайте приватную игру или войдите по коду друга. Здесь нет случайного поиска соперника."),
            localizationEntry("social.invites.how_to", "Как пригласить друга"),
            localizationEntry("social.invites.step_1", "1. Нажмите «Создать код» в онлайн-матче."),
            localizationEntry("social.invites.step_2", "2. Скопируйте код или отправьте его через «Поделиться»."),
            localizationEntry("social.invites.step_3", "3. Друг вводит код на втором телефоне и входит в комнату."),
            localizationEntry("social.test_friend.title", "Mirkori Bot"),
            localizationEntry("social.test_friend.subtitle", "Тестовый друг · серверный бот"),
            localizationEntry("social.test_friend.offline", "Тестовый друг · онлайн сейчас недоступен"),
            localizationEntry("social.test_friend.play", "Играть"),
            localizationEntry("social.online.searching", "Ищем соперника…"),
            localizationEntry("social.online.restoring", "Восстанавливаем матч…"),
            localizationEntry("social.online.error.restore_auth", "Не удалось восстановить гостевую сессию"),
            localizationEntry("social.online.error.membership", "Сервер отклонил участие в этом матче"),
            localizationEntry("social.online.error.revision", "Матч изменился. Состояние будет загружено заново"),
            localizationEntry("social.online.error.offline", "Нет подключения к сети"),
            localizationEntry("social.online.error.unavailable", "Сервер временно недоступен"),
            localizationEntry("social.online.error.invalid_response", "Сервер вернул некорректный ответ"),
            localizationEntry("social.online.error.guest_auth", "Не удалось войти как гость"),
            localizationEntry("social.online.error.invite_owner", "Это приглашение принадлежит другому игроку"),
            localizationEntry("social.online.error.invite_used", "Приглашение уже использовано"),
            localizationEntry("social.online.error.invite_invalid", "Код не найден или приглашение уже истекло"),
            localizationEntry("social.online.error.invite_open", "Не удалось открыть приглашение"),
            localizationEntry("social.online.error.room_missing", "Сервер не создал комнату"),
            localizationEntry("social.online.error.match_missing", "Сервер не создал матч"),
            localizationEntry("social.online.error.invite_expired", "Время приглашения истекло"),
            localizationEntry("social.online.settings", "Настройки онлайн-матча"),
            localizationEntry("social.online.secret_length", "Длина секрета"),
            localizationEntry("social.online.secret_length.decrease", "Уменьшить длину секрета"),
            localizationEntry("social.online.secret_length.increase", "Увеличить длину секрета"),
            localizationEntry("social.online.code_length.four", "{count} цифры"),
            localizationEntry("social.online.code_length.other", "{count} цифр"),
            localizationEntry("social.online.rules", "Цифры могут повторяться, но не больше трёх одинаковых подряд. Лимита ходов нет, время матча — 10 минут."),
            localizationEntry("social.online.find_opponent", "Найти соперника"),
            localizationEntry("social.online.bot_fallback", "Если игрока с такими же настройками нет, сервер подключит бота."),
            localizationEntry("social.online.find_match", "Найти матч"),
            localizationEntry("social.online.play_friend", "Играть с другом"),
            localizationEntry("social.online.creating_invite", "Создаём приглашение…"),
            localizationEntry("social.online.create_code", "Создать код"),
            localizationEntry("social.online.send_invite", "Отправить приглашение"),
            localizationEntry("social.online.invite_sent", "Приглашение отправлено. Код ниже — запасной способ подключения."),
            localizationEntry("social.notification.title", "Приглашение в InPlaceX"),
            localizationEntry("social.notification.race", "Друг приглашает вас в гонку."),
            localizationEntry("social.notification.turn_based", "Друг приглашает вас в дуэль."),
            localizationEntry("social.online.friend_code", "Код друга"),
            localizationEntry("social.online.friend_code.placeholder", "Введите код друга"),
            localizationEntry("social.online.joining_friend", "Подключаемся к другу…"),
            localizationEntry("social.online.join_code", "Войти по коду"),
            localizationEntry("social.online.share_code", "Передайте код другу"),
            localizationEntry("social.online.waiting_phone", "Ожидаем второй телефон. Комната действует 10 минут."),
            localizationEntry("social.online.invite_summary", "{style} · {length} · без лимита ходов"),
            localizationEntry("social.online.cancel", "Отмена"),
            localizationEntry("social.online.retry", "Попробовать снова"),
            localizationEntry("social.online.setup.wait_opponent", "Ждём секрет соперника"),
            localizationEntry("social.online.setup.enter_secret", "Задайте свой секретный код"),
            localizationEntry("social.online.opponent_turn", "Ход соперника"),
            localizationEntry("social.online.result.time_expired", "Время вышло"),
            localizationEntry("social.online.result.player_won", "Вы победили!"),
            localizationEntry("social.online.result.opponent_won", "Соперник победил"),
            localizationEntry("social.online.result.finished", "Матч завершён"),
            localizationEntry("social.online.match", "Матч"),
            localizationEntry("social.online.match_summary", "{style} · {length} · ходов: {attempts}"),
            localizationEntry("social.online.attempt.player", "Ваш ход #{number}: точно {exact}"),
            localizationEntry("social.online.attempt.opponent", "Соперник #{number}: точно {exact}"),
            localizationEntry("social.online.secret", "Ваш секрет"),
            localizationEntry("social.online.combination", "Ваша комбинация"),
            localizationEntry("social.online.duplicate_error", "Нельзя вводить больше трёх одинаковых цифр подряд"),
            localizationEntry("social.online.syncing", "Синхронизируем ход…"),
            localizationEntry("social.online.save_secret", "Сохранить секрет"),
            localizationEntry("social.online.confirm_move", "Подтвердить ход"),
            localizationEntry("social.online.opponent_setting_secret", "Соперник задаёт свой секрет…"),
            localizationEntry("social.online.waiting_opponent_move", "Ожидаем ход соперника…"),
            localizationEntry("social.online.new_match", "Новый матч"),
            localizationEntry("social.invite.clipboard_label", "Код приглашения InplaceX"),
            localizationEntry("social.invite.copy", "Копировать"),
            localizationEntry("social.invite.copied", "Код скопирован"),
            localizationEntry("social.invite.share", "Поделиться"),
            localizationEntry("social.invite.share_title", "Пригласить в InplaceX"),
            localizationEntry("social.invite.share_text", "Сыграем в InplaceX? Введи код {code} в разделе «Друзья»."),
            localizationEntry("social.invite.join.title", "Войти по коду"),
            localizationEntry("social.invite.join.description", "Введите код приглашения от друга, чтобы присоединиться к игре."),
            localizationEntry("social.invite.join.code_label", "Пригласительный код"),
            localizationEntry("social.invite.join.code_length", "Код состоит из {count} символов"),
            localizationEntry("social.invite.join.expiry", "Код использует цифры и латинские буквы и действует 10 минут с момента создания."),
            localizationEntry("social.invite.join.action", "Войти в игру"),
            localizationEntry("social.invite.create_own", "Создать свой код"),
            localizationEntry("social.invite.remaining", "Код действует ещё {time}"),
            localizationEntry("social.reference.or", "или"),
            localizationEntry("social.status.preparing", "Онлайн готовится"),
            localizationEntry("social.status.preparing.description", "Локальная игра доступна; сетевые действия пока отключены."),
            localizationEntry("social.status.available", "Онлайн доступен"),
            localizationEntry("social.status.available.description", "Приватные коды и онлайн-матчи работают"),
            localizationEntry("social.online.title", "Онлайн‑матчи"),
            localizationEntry("social.online.description", "Найдите случайного соперника или серверного бота."),
            localizationEntry("social.online.screen_description", "Настройте быстрый матч и найдите соперника. Приватные коды находятся в разделе «Приглашения»."),
            localizationEntry("social.online.safety", "Профиль и прогресс не будут отправляться на сервер без подтверждённой авторизации."),
            localizationEntry("social.friends.subtitle", "Приглашайте игроков и управляйте списком"),
            localizationEntry("social.online.subtitle", "Готовьте онлайн-комнаты и активность в реальном времени"),
            localizationEntry("social.match.title", "Онлайн‑матч"),
            localizationEntry("social.match.format", "Формат матча"),
            localizationEntry("social.match.timed", "На время"),
            localizationEntry("social.match.turn_based", "По очереди"),
            localizationEntry("social.match.timed.description", "Оба игрока разгадывают одновременно. Побеждает тот, кто первым найдёт код."),
            localizationEntry("social.match.turn_based.description", "Игроки делают по одному ходу. После принятого хода очередь переходит сопернику."),
            localizationEntry("social.match.timed.started", "Матч на время начался"),
            localizationEntry("social.match.timed.field_title", "Онлайн · На время"),
            localizationEntry("social.match.turn_based.field_title", "Онлайн · По очереди"),
            localizationEntry("social.match.timed.turn_status", "Оба игрока разгадывают одновременно"),
            localizationEntry("social.duel.online_title", "Онлайн-дуэль"),
            localizationEntry("social.duel.your_turn", "Ваш ход"),
            localizationEntry("social.duel.opponent_turn", "Ход соперника"),
            localizationEntry("social.duel.server_authoritative", "Ходы проверяет сервер"),
            localizationEntry("social.next_steps", "Следующие шаги для онлайна"),
            localizationEntry("social.next_steps.google_play", "Вход через Google Play"),
            localizationEntry("social.next_steps.cloud_sync", "Синхронизация прогресса в облаке"),
            localizationEntry("social.next_steps.friends_pvp", "Друзья, приглашения и PvP-комнаты"),
            localizationEntry("company.scene.stars", "Звёзды: {current} / {required}"),
            localizationEntry("company.scene.locked", "Заработайте больше звёзд, чтобы открыть следующую главу."),
            localizationEntry("company.scene.unlocked", "Следующая глава уже открыта."),
            localizationEntry("company.scene.history", "История"),
            localizationEntry("company.scene.history.subtitle", "Пройденные уровни"),
            localizationEntry("company.scene.energy", "Энергия"),
            localizationEntry("company.scene.current", "Текущий"),
            localizationEntry("company.scene.best", "Лучший рейтинг"),
            localizationEntry("company.scene.no_energy", "Нет энергии"),
            localizationEntry("company.scene.locked_level", "Уровень заблокирован"),
            localizationEntry("company.scene.level", "Уровень {value}"),
            localizationEntry("company.scene.subtitle", "Маршрут логических испытаний"),
            localizationEntry("company.chapter.number", "ГЛАВА {value}"),
            localizationEntry("company.chapter.first_title", "Начало пути"),
            localizationEntry("company.chapter.previous", "Предыдущая глава"),
            localizationEntry("company.chapter.next", "Следующая глава"),
            localizationEntry("company.chapter.title", "Логические цепи"),
            localizationEntry("company.chapter.progress", "{current} из {required} звёзд"),
            localizationEntry("company.chapter.reward", "Награда главы"),
            localizationEntry("company.chapter.reward.available", "Забрать награду"),
            localizationEntry("company.chapter.reward.claimed", "Получено"),
            localizationEntry("company.reward.dialog.title", "Награда главы"),
            localizationEntry("company.reward.dialog.locked", "Пройдите все 10 уровней этой главы, чтобы получить награду."),
            localizationEntry("company.reward.dialog.claimed", "Награда этой главы уже получена."),
            localizationEntry("company.reward.dialog.collected", "Получено: {coins} монет и по одной подсказке каждого типа."),
            localizationEntry("company.retention.title", "Ежедневные бонусы"),
            localizationEntry("company.retention.action", "Награды"),
            localizationEntry("profile.google_play.mirkori_connected", "Google Play не подключён. Вход выполнен через Mirkori Games."),
            localizationEntry("company.retention.daily.reward", "Каждый день: 20 монет и 1 подсказка «Проверить цифру»."),
            localizationEntry("company.retention.weekly.reward", "Каждую неделю: 100 монет, по 1 подсказке каждого типа и по 1 усилителю ходов и времени."),
            localizationEntry("company.retention.claim", "Забрать"),
            localizationEntry("company.retention.claimed", "Получено"),
            localizationEntry("company.state.completed", "Пройдено"),
            localizationEntry("company.state.locked", "Заблокировано"),
            localizationEntry("company.lock.stars", "Нужно {value} звёзд"),
            localizationEntry("company.lock.previous", "Сначала пройдите предыдущий уровень"),
            localizationEntry("company.mission.title.standard", "Кодовая матрица"),
            localizationEntry("company.mission.title.spike", "Двойная проверка"),
            localizationEntry("company.mission.title.hardcore", "Контрольный рубеж"),
            localizationEntry("company.difficulty.easy", "Легко"),
            localizationEntry("company.difficulty.label", "Сложность"),
            localizationEntry("company.difficulty.medium", "Средне"),
            localizationEntry("company.difficulty.hard", "Сложно"),
            localizationEntry("company.difficulty.hardcore", "Эксперт"),
            localizationEntry("company.mission.objective", "Угадайте код из {digits} цифр за {moves} ходов"),
            localizationEntry("company.mission.time", "Время {value}"),
            localizationEntry("company.mission.repeats.allowed", "Повторы разрешены"),
            localizationEntry("company.mission.repeats.forbidden", "Без повторов"),
            localizationEntry("company.mission.best", "Лучший рейтинг: {value}/10"),
            localizationEntry("company.mission.best.empty", "Личный рекорд ещё не установлен"),
            localizationEntry("company.action.play", "Играть уровень {value} — 1 энергия"),
            localizationEntry("company.action.restore_energy", "Пополнить энергию"),
            localizationEntry("company.action.need_stars", "Нужно {value} звёзд"),
            localizationEntry("company.action.rules", "Правила уровня"),
            localizationEntry("company.rules.title", "Правила уровня {value}"),
            localizationEntry("company.rules.time", "На решение даётся {value}."),
            localizationEntry("company.rules.repeats.allowed", "Одинаковые цифры в коде могут повторяться."),
            localizationEntry("company.rules.repeats.forbidden", "Каждая цифра в коде используется только один раз."),
            localizationEntry("company.rules.rating", "Рейтинг зависит от числа ходов, времени, подсказок и усилителей."),
            localizationEntry("company.history.title", "История"),
            localizationEntry("company.history.subtitle", "Пройденные миссии и лучшие результаты"),
            localizationEntry("company.history.empty", "Здесь появятся пройденные уровни."),
            localizationEntry("company.action.close", "Закрыть"),
            localizationEntry("company.dialog.exit_title", "Выйти из прохождения компании?"),
            localizationEntry("company.dialog.exit_text", "Прогресс текущей попытки будет потерян."),
            localizationEntry("company.dialog.exit_confirm", "Выйти"),
            localizationEntry("company.dialog.stay", "Остаться"),
            localizationEntry("company.tutorial.step", "Шаг {current} из {total}"),
            localizationEntry("company.tutorial.goal.title", "Как играть"),
            localizationEntry("company.tutorial.goal.body", "Цель — угадать скрытый код. Нажимайте цифры, заполните все позиции в нижней строке и подтвердите ход."),
            localizationEntry("company.tutorial.feedback.title", "Читайте результат хода"),
            localizationEntry("company.tutorial.feedback.body", "После подтверждения игра покажет, сколько цифр стоит на правильных позициях. Используйте предыдущие попытки и таблицу анализа, чтобы сузить варианты."),
            localizationEntry("company.tutorial.hints.title", "Подсказки и усилители"),
            localizationEntry("company.tutorial.hints.body", "Подсказки открывают позицию, проверяют цифру или конкретное место. Сначала выберите тип подсказки, затем нужную цифру или позицию. Усилители добавляют ходы или время."),
            localizationEntry("company.tutorial.next", "Далее"),
            localizationEntry("company.tutorial.start", "Начать игру"),
            localizationEntry("company.tutorial.later", "Вернуться"),
            localizationEntry("company.dialog.complete_title", "Уровень пройден"),
            localizationEntry("company.dialog.failed_title", "Уровень не пройден"),
            localizationEntry("company.dialog.level", "Уровень {value}"),
            localizationEntry("company.dialog.rating", "Рейтинг: {value}/10"),
            localizationEntry("company.dialog.stars", "Звёзды: {value}"),
        ),
    )

    val en = localizationCatalog(
        name = "secondary.en",
        entries = listOf(
            localizationEntry("social.reference.title", "Friends"),
            localizationEntry("social.reference.subtitle", "Play and compete with your friends!"),
            localizationEntry("social.reference.online_count", "Friends online: {count}"),
            localizationEntry("social.reference.your_friends", "Your friends"),
            localizationEntry("social.reference.online_friends", "Online friends"),
            localizationEntry("social.reference.all", "All"),
            localizationEntry("social.reference.empty", "Invite your friends to play together."),
            localizationEntry("social.reference.request", "Friend request"),
            localizationEntry("social.reference.requests_count", "All requests: {count}"),
            localizationEntry("social.reference.requests_title", "Friend requests"),
            localizationEntry("social.reference.no_requests", "No new requests"),
            localizationEntry("social.reference.open", "Open"),
            localizationEntry("social.reference.invite", "Invite"),
            localizationEntry("social.reference.invite_description", "Send a code\nto your friends"),
            localizationEntry("social.reference.find_match", "Find a match"),
            localizationEntry("social.reference.match_description", "A random opponent\nonline"),
            localizationEntry("social.reference.matches", "Online matches"),
            localizationEntry("social.reference.matches_description", "Current and completed matches"),
            localizationEntry("shop.title", "Shop"),
            localizationEntry("shop.hero.subtitle", "Supplies, hints, and premium"),
            localizationEntry("shop.tab.boosts", "Supplies"),
            localizationEntry("shop.tab.premium", "Premium"),
            localizationEntry("shop.hints", "Hints and boosts"),
            localizationEntry("shop.hints.subtitle", "6 helper types for matches and campaign runs"),
            localizationEntry("shop.premium", "Purchases and access"),
            localizationEntry("shop.premium.subtitle", "Ad-free, temporary Pro, Pro and Pro+ access"),
            localizationEntry("shop.premium.overview.title", "Premium overview"),
            localizationEntry("shop.premium.overview.pro.title", "Get PRO privileges"),
            localizationEntry("shop.premium.overview.pro.description", "Expanded features and temporary automation."),
            localizationEntry("shop.premium.overview.maximum.title", "Maximum possibilities"),
            localizationEntry("shop.premium.overview.maximum.description", "All bonuses and unlimited hints for comfortable play."),
            localizationEntry("shop.rewarded.title", "Ad reward"),
            localizationEntry("shop.rewarded.coins", "Watch ads and earn rewards every day"),
            localizationEntry("shop.rewarded.watch", "Watch"),
            localizationEntry("shop.item.open_position", "Hint: open position"),
            localizationEntry("shop.item.check_digit", "Hint: check digit"),
            localizationEntry("shop.item.check_position", "Hint: check position"),
            localizationEntry("shop.item.extra_moves", "Boost: extra moves"),
            localizationEntry("shop.item.extra_time", "Boost: extra time"),
            localizationEntry("shop.item.energy", "Company energy +1"),
            localizationEntry("shop.item.open_position.desc", "Reveal the digit at one code position."),
            localizationEntry("shop.item.check_digit.desc", "Check whether a chosen digit is in the code."),
            localizationEntry("shop.item.check_position.desc", "Check a chosen digit at a specific position."),
            localizationEntry("shop.item.extra_moves.desc", "Add attempts to a match with a move limit."),
            localizationEntry("shop.item.extra_time.desc", "Add time to a match with a timer."),
            localizationEntry("shop.item.energy.desc", "Restore one energy point for the company."),
            localizationEntry("shop.product.remove_ads", "Remove ads"),
            localizationEntry("shop.product.remove_ads.desc", "One-time purchase. Removes banner ads and rare post-match ads."),
            localizationEntry("shop.product.pro", "Pro access"),
            localizationEntry("shop.product.pro.desc", "Auto table mode + no banner and no post-match ads."),
            localizationEntry("shop.product.temporary_pro", "PRO for 1 hour"),
            localizationEntry("shop.product.temporary_pro.desc", "Auto table mode and no ads for one hour. Another purchase adds one more hour."),
            localizationEntry("shop.product.pro_plus", "Pro+ access"),
            localizationEntry("shop.product.pro_plus.desc", "Everything in Pro + infinite hints and full ad removal."),
            localizationEntry("shop.buy", "Buy"),
            localizationEntry("shop.subscribe", "Buy access"),
            localizationEntry("shop.product.prepaid_duration", "Access term: {duration}. One-time payment, no auto-renewal."),
            localizationEntry("shop.product.prepaid_duration_unknown", "Fixed-term access after a one-time payment, with no auto-renewal."),
            localizationEntry("shop.product.duration_days", "{count} days"),
            localizationEntry("shop.product.duration_hours", "{count} hours"),
            localizationEntry("shop.product.duration_minutes", "{count} minutes"),
            localizationEntry("shop.owned", "Owned"),
            localizationEntry("shop.active", "Active"),
            localizationEntry("shop.price", "{price} coins"),
            localizationEntry("shop.stock", "In stock: {count}"),
            localizationEntry("shop.not_enough_coins", "Not enough coins"),
            localizationEntry("shop.result.success", "Done. The local bonus was applied."),
            localizationEntry("shop.result.unavailable", "This action is unavailable right now. Your balance and profile were not changed."),
            localizationEntry("shop.billing.checking", "Checking purchases with the server…"),
            localizationEntry("shop.billing.ready", "Mirkori Games purchases are synchronized."),
            localizationEntry("shop.billing.unavailable", "Purchases are unavailable. Local coins and bonuses were not changed."),
            localizationEntry("shop.billing.unavailable_short", "Unavailable"),
            localizationEntry("shop.billing.open_profile", "Open profile and sign in"),
            localizationEntry("shop.billing.retry_payment", "Retry payment"),
            localizationEntry("shop.billing.refresh", "Check purchases"),
            localizationEntry("shop.billing.buy_for", "Buy for {price}"),
            localizationEntry("shop.billing.checkout_opened", "Payment opened in your external browser. Access changes only after server confirmation."),
            localizationEntry("shop.billing.awaiting_payment", "Payment is not confirmed yet. Check its status or reopen checkout."),
            localizationEntry("shop.billing.awaiting_entitlement", "The payment was found, but access is not confirmed yet. Nothing was enabled locally."),
            localizationEntry("shop.billing.confirmed", "The server confirmed the purchase. Access was refreshed."),
            localizationEntry("shop.billing.cancelled", "Payment was cancelled. Access was not changed."),
            localizationEntry("shop.billing.refunded", "The server confirmed the refund. Access was refreshed."),
            localizationEntry("shop.billing.checkout_expired", "The payment link expired. A new payment stays blocked until the server confirms cancellation of the original attempt."),
            localizationEntry("shop.billing.link_required", "Sign in to Mirkori Games before paying. Guest progress stays in place."),
            localizationEntry("shop.billing.provider_unavailable", "The payment provider is temporarily unavailable (503). Retry the same action later."),
            localizationEntry("shop.billing.offline", "You are offline. Purchases were not changed; confirmed timed access remains only until it expires."),
            localizationEntry("shop.billing.retry_required", "The purchase could not be checked. Access was not changed; try again."),
            localizationEntry("shop.billing.already_active", "The server reports that this access is already active."),
            localizationEntry("shop.billing.busy", "Finish or check the payment already in progress first."),
            localizationEntry("shop.billing.configuration_required", "The purchase catalog is not configured for this build."),
            localizationEntry("shop.premium.unlocked", "Unlocked"),
            localizationEntry("shop.premium.access", "Premium access"),
            localizationEntry("shop.temporary_pro.duration", "Access for 01:00:00"),
            localizationEntry("shop.temporary_pro.remaining", "{time} remaining"),
            localizationEntry("shop.temporary_pro.included", "Included with permanent PRO"),
            localizationEntry("shop.temporary_pro.buy", "Buy for {price} coins"),
            localizationEntry("shop.temporary_pro.extend", "Extend for {price} coins"),
            localizationEntry("company.title", "Company"),
            localizationEntry("company.placeholder", "Solo progression, milestones and curated levels."),
            localizationEntry("company.list", "Company Levels"),
            localizationEntry("profile.title", "Profile"),
            localizationEntry("profile.account", "Account"),
            localizationEntry("profile.connections", "Connections"),
            localizationEntry("profile.connection.connected", "Connected"),
            localizationEntry("profile.connection.guest", "Guest mode"),
            localizationEntry("profile.connection.connecting", "Connecting…"),
            localizationEntry("profile.connection.unavailable", "Unavailable"),
            localizationEntry("profile.purchases_and_subscriptions", "Purchases and subscriptions"),
            localizationEntry("profile.premium_account", "Premium account"),
            localizationEntry("profile.premium.active", "Active"),
            localizationEntry("profile.premium.inactive", "Inactive"),
            localizationEntry("profile.player", "Player"),
            localizationEntry("profile.progress", "Progress"),
            localizationEntry("profile.membership", "Purchase status"),
            localizationEntry("profile.campaign_level", "Unlocked level"),
            localizationEntry("profile.campaign_rating", "Company rating"),
            localizationEntry("profile.google_play.connected", "Google Play is connected. Progress can be synced."),
            localizationEntry("profile.google_play.connected.short", "Connected"),
            localizationEntry("profile.google_play.disconnected.short", "Not connected"),
            localizationEntry("profile.google_play.disconnected", "Google Play is not connected. Progress is local only."),
            localizationEntry("profile.google_play.sign_in", "Sign in with Google Play"),
            localizationEntry("profile.google_play.sign_out", "Sign out of Google Play"),
            localizationEntry("profile.google_play.title", "Google Play"),
            localizationEntry("profile.google_play.guest", "Guest mode"),
            localizationEntry("profile.mirkori.title", "Mirkori Games"),
            localizationEntry("profile.mirkori.connected.short", "Mirkori Games connected"),
            localizationEntry("profile.mirkori.guest.short", "Mirkori Games guest profile"),
            localizationEntry("profile.mirkori.initializing", "Connecting to Mirkori Games…"),
            localizationEntry("profile.mirkori.unavailable.short", "Mirkori Games unavailable"),
            localizationEntry("profile.mirkori.connected", "Your global account is connected and owns this game profile."),
            localizationEntry("profile.mirkori.guest", "A guest profile is ready. Sign in to attach it to your global Mirkori Games account."),
            localizationEntry("profile.mirkori.unavailable", "Mirkori Games is unavailable. Local progress is safe; try again later."),
            localizationEntry("profile.mirkori.player_id", "Player ID: …{id}"),
            localizationEntry("profile.mirkori.copy_player_id", "Copy player ID"),
            localizationEntry("profile.mirkori.handle", "Public ID"),
            localizationEntry("profile.mirkori.handle.not_set", "Public ID is not set yet"),
            localizationEntry("profile.mirkori.handle.change", "Change public ID"),
            localizationEntry("profile.mirkori.handle.rules", "Use 3 to 24 Latin letters, digits, or underscores."),
            localizationEntry("profile.mirkori.handle.save", "Save"),
            localizationEntry("profile.mirkori.handle.cancel", "Cancel"),
            localizationEntry("profile.mirkori.handle.saved", "Public ID saved."),
            localizationEntry("profile.mirkori.handle.taken", "This public ID is already taken."),
            localizationEntry("profile.mirkori.handle.invalid", "Check the public ID format."),
            localizationEntry("profile.mirkori.handle.unavailable", "The public ID could not be changed right now."),
            localizationEntry("profile.mirkori.name", "Player name"),
            localizationEntry("profile.mirkori.name.change", "Change name"),
            localizationEntry("profile.mirkori.name.rules", "Enter the name other players will see."),
            localizationEntry("profile.mirkori.name.save", "Save"),
            localizationEntry("profile.mirkori.name.saved", "Name saved."),
            localizationEntry("profile.mirkori.name.invalid", "Name cannot be empty."),
            localizationEntry("profile.mirkori.name.unavailable", "The name could not be changed right now."),
            localizationEntry("profile.mirkori.avatar.change", "Change avatar"),
            localizationEntry("profile.mirkori.avatar.choose", "Choose a profile picture."),
            localizationEntry("profile.mirkori.avatar.saved", "Avatar saved."),
            localizationEntry("profile.mirkori.avatar.invalid", "This avatar cannot be selected."),
            localizationEntry("profile.mirkori.avatar.unavailable", "The avatar could not be changed right now."),
            localizationEntry("profile.mirkori.sign_in", "Sign in to Mirkori Games"),
            localizationEntry("profile.mirkori.in_progress", "Preparing secure sign-in…"),
            localizationEntry("profile.mirkori.browser_opened", "Finish signing in in the browser and confirm the return to the game."),
            localizationEntry("profile.mirkori.connected.success", "Mirkori Games account connected."),
            localizationEntry("profile.mirkori.conflict", "This account already owns another InplaceX profile. Neither profile was changed."),
            localizationEntry("profile.google.conflict.title", "This Google account is already in use"),
            localizationEntry("profile.google.conflict.message", "An InplaceX profile already exists for this Google account. Sign in to it? The current guest profile will not be deleted, and local progress will remain on this device."),
            localizationEntry("profile.google.conflict.use_existing", "Use existing profile"),
            localizationEntry("profile.google.conflict.keep_current", "Keep current profile"),
            localizationEntry("profile.google.conflict.kept", "You kept the current profile. Nothing was changed."),
            localizationEntry("profile.mirkori.rejected", "Sign-in could not be confirmed. Start it again from the game."),
            localizationEntry("profile.ads_removed.yes", "Ads are removed permanently."),
            localizationEntry("profile.ads_removed.no", "The one-time ad removal purchase is not active."),
            localizationEntry("profile.pro.yes", "Pro access is active."),
            localizationEntry("profile.pro.no", "Pro access is not active."),
            localizationEntry("profile.pro_plus.yes", "Pro+ access is active."),
            localizationEntry("profile.pro_plus.no", "Pro+ access is not active."),
            localizationEntry("profile.membership.ads", "Ads"),
            localizationEntry("profile.membership.pro", "Pro"),
            localizationEntry("profile.membership.pro_plus", "Pro+"),
            localizationEntry("profile.membership.temporary_pro", "Temporary Pro"),
            localizationEntry("profile.membership.active", "Active"),
            localizationEntry("profile.membership.locked", "Locked"),
            localizationEntry("profile.membership.remaining", "{time} remaining"),
            localizationEntry("profile.membership.included", "Included in paid access"),
            localizationEntry("profile.match_stats", "Match stats"),
            localizationEntry("profile.match_stats.pve", "PvE"),
            localizationEntry("profile.match_stats.pvp", "PvP"),
            localizationEntry("profile.match_stats.result", "W {wins} / L {losses}"),
            localizationEntry("profile.overview", "Overview"),
            localizationEntry("profile.matches", "Matches played"),
            localizationEntry("profile.auth.signed_in", "Signed in. Your profile is ready to sync."),
            localizationEntry("profile.auth.signed_out", "Google Play was disconnected on this device. Your Mirkori Games account was not changed; local progress was preserved."),
            localizationEntry("profile.auth.unavailable", "Sign-in is unavailable right now. You remain in guest mode and your progress is safe."),
            localizationEntry("profile.auth.in_progress", "Connecting your Google account…"),
            localizationEntry("profile.auth.cancelled", "Sign-in was cancelled. You remain in guest mode."),
            localizationEntry("profile.auth.not_configured", "Google sign-in is not enabled for this build or server yet."),
            localizationEntry("profile.auth.rejected", "Google could not verify this sign-in. Please try again."),
            localizationEntry("settings.title", "Settings"),
            localizationEntry("settings.description", "Use this panel for language and shell system settings."),
            localizationEntry("settings.language", "Language"),
            localizationEntry("settings.language.ru", "Russian"),
            localizationEntry("settings.language.en", "English"),
            localizationEntry("settings.language.selector", "Select language"),
            localizationEntry("settings.ad_privacy", "Advertising privacy"),
            localizationEntry("settings.feedback.title", "Sound and feedback"),
            localizationEntry("settings.vibration", "Vibration"),
            localizationEntry("settings.vibration.description", "Feedback for game actions and results."),
            localizationEntry("settings.sound", "Sound effects"),
            localizationEntry("settings.sound.description", "Buttons, hints, errors, and match results."),
            localizationEntry("settings.music", "Music"),
            localizationEntry("settings.music.description", "Background music in menus and during play."),
            localizationEntry("settings.information.title", "Information and support"),
            localizationEntry("settings.contact", "Contact us"),
            localizationEntry("settings.terms", "Terms of use"),
            localizationEntry("settings.privacy", "Privacy policy"),
            localizationEntry("settings.about", "About us"),
            localizationEntry("settings.open_source_licenses", "Open-source licenses"),
            localizationEntry("ads.privacy.title", "Advertising privacy"),
            localizationEntry("ads.privacy.description", "Advertising services may process device data to select, measure, and protect ads. Allow personalized advertising? If you decline, the app may show only non-personalized advertising."),
            localizationEntry("ads.privacy.accept", "Allow"),
            localizationEntry("ads.privacy.decline", "No personalization"),
            localizationEntry("ads.privacy.status.undecided", "not selected"),
            localizationEntry("ads.privacy.status.accepted", "personalization allowed"),
            localizationEntry("ads.privacy.status.declined", "no personalization"),
            localizationEntry("social.description", "This section will handle friends, invites and online presence."),
            localizationEntry("social.hero.subtitle", "Friends, invitations, and online matches."),
            localizationEntry("social.invites", "Invitations"),
            localizationEntry("social.invites.incoming.notice", "New invitations: {count}"),
            localizationEntry("social.invites.incoming.title", "Game invitation"),
            localizationEntry("social.invites.accept", "Accept"),
            localizationEntry("social.invites.open", "Open friends"),
            localizationEntry("social.friends.empty", "Your friends list is empty."),
            localizationEntry("social.friend.saved", "Saved in your friends list"),
            localizationEntry("social.friend.match.title", "Play with {name}"),
            localizationEntry("social.friend.match.title.generic", "Play with a friend"),
            localizationEntry("social.friend.match.description", "Choose the game format and send a direct invitation."),
            localizationEntry("social.friend.add.title", "Add friend"),
            localizationEntry("social.friend.add.description", "Ask your friend to copy the full player ID from their profile."),
            localizationEntry("social.friend.add.name", "Friend name"),
            localizationEntry("social.friend.add.player_id", "Player ID"),
            localizationEntry("social.friend.add.action", "Add"),
            localizationEntry("social.friend.add.added", "Added"),
            localizationEntry("social.friend.add.invalid_name", "Enter your friend's name."),
            localizationEntry("social.friend.add.invalid_player_id", "Player ID must be a full UUID."),
            localizationEntry("social.friend.add.self", "You cannot add yourself."),
            localizationEntry("social.friend.add.saved", "Friend added."),
            localizationEntry("social.friend.request.sent", "Friend request sent."),
            localizationEntry("social.friend.request.sent.short", "Sent"),
            localizationEntry("social.friend.request.incoming", "Wants to add you as a friend"),
            localizationEntry("social.friend.request.accept", "Accept"),
            localizationEntry("social.friend.request.accepted", "Friend request accepted."),
            localizationEntry("social.friend.request.rejected", "The friend request could not be completed."),
            localizationEntry("social.friend.request.unavailable", "The friends service is currently unavailable."),
            localizationEntry("social.friend.request.root_notice", "{name} sent you a friend request."),
            localizationEntry("social.friend.request.open", "Open request"),
            localizationEntry("social.friend.request.notification.title", "New friend request"),
            localizationEntry("social.friend.request.notification.message", "{name} wants to add you as a friend."),
            localizationEntry("social.friend.search.query", "Name or public ID"),
            localizationEntry("social.friend.search.action", "Find"),
            localizationEntry("social.friend.search.invalid", "Enter a player name or public ID."),
            localizationEntry("social.friend.search.empty", "No players found."),
            localizationEntry("social.friend.search.unavailable", "Search is unavailable. Try again later."),
            localizationEntry("social.friend.search.close", "Close"),
            localizationEntry("social.friend.id_fallback", "ID: …{id}"),
            localizationEntry("social.invites.empty", "There are no new invitations."),
            localizationEntry("social.invites.guide", "Create a code and send it to your friend."),
            localizationEntry("social.invites.screen_description", "Create a private game or enter your friend's code. Random matchmaking is kept out of invitations."),
            localizationEntry("social.invites.how_to", "How to invite a friend"),
            localizationEntry("social.invites.step_1", "1. Tap “Create code” in the online match."),
            localizationEntry("social.invites.step_2", "2. Copy the code or send it with “Share”."),
            localizationEntry("social.invites.step_3", "3. Your friend enters the code on a second phone and joins the room."),
            localizationEntry("social.test_friend.title", "Mirkori Bot"),
            localizationEntry("social.test_friend.subtitle", "Test friend · server bot"),
            localizationEntry("social.test_friend.offline", "Test friend · online is currently unavailable"),
            localizationEntry("social.test_friend.play", "Play"),
            localizationEntry("social.online.searching", "Finding an opponent…"),
            localizationEntry("social.online.restoring", "Restoring match…"),
            localizationEntry("social.online.error.restore_auth", "Could not restore the guest session"),
            localizationEntry("social.online.error.membership", "The server rejected access to this match"),
            localizationEntry("social.online.error.revision", "The match changed. Its state will be loaded again"),
            localizationEntry("social.online.error.offline", "No network connection"),
            localizationEntry("social.online.error.unavailable", "The server is temporarily unavailable"),
            localizationEntry("social.online.error.invalid_response", "The server returned an invalid response"),
            localizationEntry("social.online.error.guest_auth", "Could not sign in as a guest"),
            localizationEntry("social.online.error.invite_owner", "This invitation belongs to another player"),
            localizationEntry("social.online.error.invite_used", "This invitation has already been used"),
            localizationEntry("social.online.error.invite_invalid", "Code not found or the invitation has expired"),
            localizationEntry("social.online.error.invite_open", "Could not open the invitation"),
            localizationEntry("social.online.error.room_missing", "The server did not create a room"),
            localizationEntry("social.online.error.match_missing", "The server did not create a match"),
            localizationEntry("social.online.error.invite_expired", "The invitation has expired"),
            localizationEntry("social.online.settings", "Online match settings"),
            localizationEntry("social.online.secret_length", "Secret length"),
            localizationEntry("social.online.secret_length.decrease", "Decrease secret length"),
            localizationEntry("social.online.secret_length.increase", "Increase secret length"),
            localizationEntry("social.online.code_length.four", "{count} digits"),
            localizationEntry("social.online.code_length.other", "{count} digits"),
            localizationEntry("social.online.rules", "Digits may repeat, but no more than three identical digits in a row. There is no move limit, and the match lasts 10 minutes."),
            localizationEntry("social.online.find_opponent", "Find an opponent"),
            localizationEntry("social.online.bot_fallback", "If no player has the same settings, the server will connect a bot."),
            localizationEntry("social.online.find_match", "Find match"),
            localizationEntry("social.online.play_friend", "Play with a friend"),
            localizationEntry("social.online.creating_invite", "Creating invitation…"),
            localizationEntry("social.online.create_code", "Create code"),
            localizationEntry("social.online.send_invite", "Send invitation"),
            localizationEntry("social.online.invite_sent", "Invitation sent. The code below is a fallback way to join."),
            localizationEntry("social.notification.title", "InPlaceX invitation"),
            localizationEntry("social.notification.race", "A friend invited you to a race."),
            localizationEntry("social.notification.turn_based", "A friend invited you to a duel."),
            localizationEntry("social.online.friend_code", "Friend's code"),
            localizationEntry("social.online.friend_code.placeholder", "Enter your friend's code"),
            localizationEntry("social.online.joining_friend", "Joining your friend…"),
            localizationEntry("social.online.join_code", "Join with code"),
            localizationEntry("social.online.share_code", "Send the code to your friend"),
            localizationEntry("social.online.waiting_phone", "Waiting for the second phone. The room is available for 10 minutes."),
            localizationEntry("social.online.invite_summary", "{style} · {length} · no move limit"),
            localizationEntry("social.online.cancel", "Cancel"),
            localizationEntry("social.online.retry", "Try again"),
            localizationEntry("social.online.setup.wait_opponent", "Waiting for the opponent's secret"),
            localizationEntry("social.online.setup.enter_secret", "Set your secret code"),
            localizationEntry("social.online.opponent_turn", "Opponent's turn"),
            localizationEntry("social.online.result.time_expired", "Time is up"),
            localizationEntry("social.online.result.player_won", "You won!"),
            localizationEntry("social.online.result.opponent_won", "Opponent won"),
            localizationEntry("social.online.result.finished", "Match finished"),
            localizationEntry("social.online.match", "Match"),
            localizationEntry("social.online.match_summary", "{style} · {length} · moves: {attempts}"),
            localizationEntry("social.online.attempt.player", "Your move #{number}: exact {exact}"),
            localizationEntry("social.online.attempt.opponent", "Opponent #{number}: exact {exact}"),
            localizationEntry("social.online.secret", "Your secret"),
            localizationEntry("social.online.combination", "Your combination"),
            localizationEntry("social.online.duplicate_error", "You cannot enter more than three identical digits in a row"),
            localizationEntry("social.online.syncing", "Syncing move…"),
            localizationEntry("social.online.save_secret", "Save secret"),
            localizationEntry("social.online.confirm_move", "Confirm move"),
            localizationEntry("social.online.opponent_setting_secret", "The opponent is setting a secret…"),
            localizationEntry("social.online.waiting_opponent_move", "Waiting for the opponent's move…"),
            localizationEntry("social.online.new_match", "New match"),
            localizationEntry("social.invite.clipboard_label", "InplaceX invitation code"),
            localizationEntry("social.invite.copy", "Copy"),
            localizationEntry("social.invite.copied", "Code copied"),
            localizationEntry("social.invite.share", "Share"),
            localizationEntry("social.invite.share_title", "Invite to InplaceX"),
            localizationEntry("social.invite.share_text", "Let's play InplaceX. Enter code {code} in Friends."),
            localizationEntry("social.invite.join.title", "Join with code"),
            localizationEntry("social.invite.join.description", "Enter your friend's invitation code to join the game."),
            localizationEntry("social.invite.join.code_label", "Invitation code"),
            localizationEntry("social.invite.join.code_length", "The code contains {count} characters"),
            localizationEntry("social.invite.join.expiry", "The code uses digits and Latin letters and remains valid for 10 minutes after creation."),
            localizationEntry("social.invite.join.action", "Join game"),
            localizationEntry("social.invite.create_own", "Create your own code"),
            localizationEntry("social.invite.remaining", "Code remains valid for {time}"),
            localizationEntry("social.reference.or", "or"),
            localizationEntry("social.status.preparing", "Online is being prepared"),
            localizationEntry("social.status.preparing.description", "Local play is available; network actions are currently disabled."),
            localizationEntry("social.status.available", "Online is available"),
            localizationEntry("social.status.available.description", "Private codes and online matches are working"),
            localizationEntry("social.online.title", "Online matches"),
            localizationEntry("social.online.description", "Find a random opponent or a server bot."),
            localizationEntry("social.online.screen_description", "Configure a quick match and find an opponent. Private codes live under Invitations."),
            localizationEntry("social.online.safety", "Your profile and progress will not be sent to the server without verified authentication."),
            localizationEntry("social.friends.subtitle", "Invite players and manage your list"),
            localizationEntry("social.online.subtitle", "Prepare online rooms and live activity"),
            localizationEntry("social.match.title", "Online match"),
            localizationEntry("social.match.format", "Match format"),
            localizationEntry("social.match.timed", "Timed"),
            localizationEntry("social.match.turn_based", "Turn by turn"),
            localizationEntry("social.match.timed.description", "Both players solve at the same time. The first player to find the code wins."),
            localizationEntry("social.match.turn_based.description", "Players make one move at a time. After an accepted move, the turn passes to the opponent."),
            localizationEntry("social.match.timed.started", "Timed match started"),
            localizationEntry("social.match.timed.field_title", "Online · Timed"),
            localizationEntry("social.match.turn_based.field_title", "Online · Turn by turn"),
            localizationEntry("social.match.timed.turn_status", "Both players solve at the same time"),
            localizationEntry("social.duel.online_title", "Online duel"),
            localizationEntry("social.duel.your_turn", "Your turn"),
            localizationEntry("social.duel.opponent_turn", "Opponent's turn"),
            localizationEntry("social.duel.server_authoritative", "Moves are verified by the server"),
            localizationEntry("social.next_steps", "Next online steps"),
            localizationEntry("social.next_steps.google_play", "Google Play sign-in"),
            localizationEntry("social.next_steps.cloud_sync", "Cloud progress sync"),
            localizationEntry("social.next_steps.friends_pvp", "Friends, invites and PvP rooms"),
            localizationEntry("company.scene.stars", "Stars: {current} / {required}"),
            localizationEntry("company.scene.locked", "Earn more stars to unlock the next chapter."),
            localizationEntry("company.scene.unlocked", "The next chapter is already unlocked."),
            localizationEntry("company.scene.history", "History"),
            localizationEntry("company.scene.history.subtitle", "Completed levels"),
            localizationEntry("company.scene.energy", "Energy"),
            localizationEntry("company.scene.current", "Current"),
            localizationEntry("company.scene.best", "Best rating"),
            localizationEntry("company.scene.no_energy", "No energy"),
            localizationEntry("company.scene.locked_level", "Level locked"),
            localizationEntry("company.scene.level", "Level {value}"),
            localizationEntry("company.scene.subtitle", "Your route through logic missions"),
            localizationEntry("company.chapter.number", "CHAPTER {value}"),
            localizationEntry("company.chapter.first_title", "First steps"),
            localizationEntry("company.chapter.previous", "Previous chapter"),
            localizationEntry("company.chapter.next", "Next chapter"),
            localizationEntry("company.chapter.title", "Logic chains"),
            localizationEntry("company.chapter.progress", "{current} of {required} stars"),
            localizationEntry("company.chapter.reward", "Chapter reward"),
            localizationEntry("company.chapter.reward.available", "Collect reward"),
            localizationEntry("company.chapter.reward.claimed", "Collected"),
            localizationEntry("company.reward.dialog.title", "Chapter reward"),
            localizationEntry("company.reward.dialog.locked", "Complete all 10 levels in this chapter to collect its reward."),
            localizationEntry("company.reward.dialog.claimed", "This chapter reward has already been collected."),
            localizationEntry("company.reward.dialog.collected", "Collected: {coins} coins and one hint of every type."),
            localizationEntry("company.retention.title", "Daily bonuses"),
            localizationEntry("company.retention.action", "Rewards"),
            localizationEntry("profile.google_play.mirkori_connected", "Google Play is not connected. You are signed in with Mirkori Games."),
            localizationEntry("company.retention.daily.reward", "Every day: 20 coins and 1 Check digit hint."),
            localizationEntry("company.retention.weekly.reward", "Every week: 100 coins, 1 hint of every type, and 1 moves and time boost."),
            localizationEntry("company.retention.claim", "Collect"),
            localizationEntry("company.retention.claimed", "Collected"),
            localizationEntry("company.state.completed", "Completed"),
            localizationEntry("company.state.locked", "Locked"),
            localizationEntry("company.lock.stars", "Requires {value} stars"),
            localizationEntry("company.lock.previous", "Complete the previous level first"),
            localizationEntry("company.mission.title.standard", "Code matrix"),
            localizationEntry("company.mission.title.spike", "Double check"),
            localizationEntry("company.mission.title.hardcore", "Control point"),
            localizationEntry("company.difficulty.easy", "Easy"),
            localizationEntry("company.difficulty.label", "Difficulty"),
            localizationEntry("company.difficulty.medium", "Medium"),
            localizationEntry("company.difficulty.hard", "Hard"),
            localizationEntry("company.difficulty.hardcore", "Expert"),
            localizationEntry("company.mission.objective", "Guess a {digits}-digit code in {moves} moves"),
            localizationEntry("company.mission.time", "Time {value}"),
            localizationEntry("company.mission.repeats.allowed", "Repeats allowed"),
            localizationEntry("company.mission.repeats.forbidden", "No repeats"),
            localizationEntry("company.mission.best", "Best rating: {value}/10"),
            localizationEntry("company.mission.best.empty", "No personal best yet"),
            localizationEntry("company.action.play", "Play level {value} — 1 energy"),
            localizationEntry("company.action.restore_energy", "Restore energy"),
            localizationEntry("company.action.need_stars", "Requires {value} stars"),
            localizationEntry("company.action.rules", "Level rules"),
            localizationEntry("company.rules.title", "Level {value} rules"),
            localizationEntry("company.rules.time", "You have {value} to solve the code."),
            localizationEntry("company.rules.repeats.allowed", "The same digit may appear more than once in the code."),
            localizationEntry("company.rules.repeats.forbidden", "Each digit is used only once in the code."),
            localizationEntry("company.rules.rating", "Your rating depends on moves, time, hints and boosts."),
            localizationEntry("company.history.title", "History"),
            localizationEntry("company.history.subtitle", "Completed missions and personal bests"),
            localizationEntry("company.history.empty", "Completed levels will appear here."),
            localizationEntry("company.action.close", "Close"),
            localizationEntry("company.dialog.exit_title", "Exit campaign run?"),
            localizationEntry("company.dialog.exit_text", "Progress in the current attempt will be lost."),
            localizationEntry("company.dialog.exit_confirm", "Exit"),
            localizationEntry("company.dialog.stay", "Stay"),
            localizationEntry("company.tutorial.step", "Step {current} of {total}"),
            localizationEntry("company.tutorial.goal.title", "How to play"),
            localizationEntry("company.tutorial.goal.body", "Your goal is to guess the hidden code. Tap digits, fill every position in the bottom row, and submit the guess."),
            localizationEntry("company.tutorial.feedback.title", "Read the result"),
            localizationEntry("company.tutorial.feedback.body", "After each guess, the game shows how many digits are in their exact positions. Use earlier attempts and the analysis table to narrow the possibilities."),
            localizationEntry("company.tutorial.hints.title", "Hints and boosts"),
            localizationEntry("company.tutorial.hints.body", "Hints can reveal a position, check a digit, or check one place. Select the hint first, then the digit or position. Boosts add moves or time."),
            localizationEntry("company.tutorial.next", "Next"),
            localizationEntry("company.tutorial.start", "Start game"),
            localizationEntry("company.tutorial.later", "Go back"),
            localizationEntry("company.dialog.complete_title", "Level complete"),
            localizationEntry("company.dialog.failed_title", "Level failed"),
            localizationEntry("company.dialog.level", "Level {value}"),
            localizationEntry("company.dialog.rating", "Rating: {value}/10"),
            localizationEntry("company.dialog.stars", "Stars: {value}"),
        ),
    )
}
