package com.mirkori.inplacex.platform.localization

internal object SecondaryCatalog {
    val ru = localizationCatalog(
        name = "secondary.ru",
        entries = listOf(
            localizationEntry("shop.title", "Магазин"),
            localizationEntry("shop.hints", "Подсказки и бустеры"),
            localizationEntry("shop.hints.subtitle", "6 типов помощи для матчей и прохождения компании"),
            localizationEntry("shop.premium", "Подписки и покупки"),
            localizationEntry("shop.premium.subtitle", "Без рекламы, Pro и Pro+"),
            localizationEntry("shop.rewarded.title", "Бонус за рекламу"),
            localizationEntry("shop.rewarded.coins", "Посмотрите рекламу и получите 20 монет."),
            localizationEntry("shop.rewarded.watch", "Смотреть рекламу"),
            localizationEntry("shop.item.open_position", "Подсказка: открыть позицию"),
            localizationEntry("shop.item.check_digit", "Подсказка: проверить цифру"),
            localizationEntry("shop.item.check_position", "Подсказка: проверить позицию"),
            localizationEntry("shop.item.extra_moves", "Бустер: дополнительные ходы"),
            localizationEntry("shop.item.extra_time", "Бустер: дополнительное время"),
            localizationEntry("shop.item.energy", "Энергия компании +1"),
            localizationEntry("shop.product.remove_ads", "Отключить рекламу"),
            localizationEntry("shop.product.remove_ads.desc", "Разовая покупка. Убирает баннер и редкие рекламные показы после матча."),
            localizationEntry("shop.product.pro", "Подписка Pro"),
            localizationEntry("shop.product.pro.desc", "Авто режим таблицы + без баннера и постматчевой рекламы."),
            localizationEntry("shop.product.pro_plus", "Подписка Pro+"),
            localizationEntry("shop.product.pro_plus.desc", "Все бонусы Pro + бесконечные подсказки и полное отключение рекламы."),
            localizationEntry("shop.buy", "Купить"),
            localizationEntry("shop.subscribe", "Подписаться"),
            localizationEntry("shop.owned", "Куплено"),
            localizationEntry("shop.active", "Активно"),
            localizationEntry("shop.price", "{price} монет"),
            localizationEntry("shop.premium.unlocked", "Открыто"),
            localizationEntry("shop.premium.access", "Премиум-доступ"),
            localizationEntry("company.title", "Компания"),
            localizationEntry("company.placeholder", "Одиночное прохождение, прогресс и серия уровней."),
            localizationEntry("company.list", "Уровни компании"),
            localizationEntry("profile.title", "Профиль"),
            localizationEntry("profile.account", "Аккаунт"),
            localizationEntry("profile.player", "Игрок"),
            localizationEntry("profile.progress", "Прогресс"),
            localizationEntry("profile.membership", "Статус покупок"),
            localizationEntry("profile.campaign_level", "Открытый уровень"),
            localizationEntry("profile.campaign_rating", "Общий рейтинг компании"),
            localizationEntry("profile.google_play.connected", "Google Play подключен. Прогресс можно синхронизировать."),
            localizationEntry("profile.google_play.disconnected", "Google Play не подключен. Прогресс хранится только локально."),
            localizationEntry("profile.google_play.sign_in", "Войти через Google Play"),
            localizationEntry("profile.google_play.sign_out", "Выйти из Google Play"),
            localizationEntry("profile.google_play.title", "Google Play"),
            localizationEntry("profile.google_play.guest", "Гостевой режим"),
            localizationEntry("profile.ads_removed.yes", "Реклама отключена навсегда."),
            localizationEntry("profile.ads_removed.no", "Разовая покупка отключения рекламы не активна."),
            localizationEntry("profile.pro.yes", "Подписка Pro активна."),
            localizationEntry("profile.pro.no", "Подписка Pro не активна."),
            localizationEntry("profile.pro_plus.yes", "Подписка Pro+ активна."),
            localizationEntry("profile.pro_plus.no", "Подписка Pro+ не активна."),
            localizationEntry("profile.developer", "Разработчик"),
            localizationEntry("profile.developer.add_coins", "+100 монет"),
            localizationEntry("profile.membership.ads", "Реклама"),
            localizationEntry("profile.membership.pro", "Pro"),
            localizationEntry("profile.membership.pro_plus", "Pro+"),
            localizationEntry("profile.membership.active", "Активно"),
            localizationEntry("profile.membership.locked", "Заблокировано"),
            localizationEntry("profile.match_stats", "Статистика матчей"),
            localizationEntry("profile.match_stats.pve", "PvE"),
            localizationEntry("profile.match_stats.pvp", "PvP"),
            localizationEntry("profile.match_stats.result", "Победы: {wins} / Поражения: {losses}"),
            localizationEntry("settings.title", "Настройки"),
            localizationEntry("settings.description", "Здесь настраиваются язык и системные параметры оболочки."),
            localizationEntry("settings.language", "Язык"),
            localizationEntry("settings.language.ru", "Русский"),
            localizationEntry("settings.language.en", "Английский"),
            localizationEntry("settings.language.selector", "Выбор языка"),
            localizationEntry("settings.developer", "Режим разработчика"),
            localizationEntry("developer.title", "Режим разработчика"),
            localizationEntry("developer.description", "Внутренний экран для отладки ресурсов, подписок и поведения бота."),
            localizationEntry("developer.section.resources", "Ресурсы"),
            localizationEntry("developer.section.membership", "Подписки и доступы"),
            localizationEntry("developer.action.add_coins", "+100 монет"),
            localizationEntry("developer.action.add_helpers", "+3 помощи"),
            localizationEntry("developer.action.refill_energy", "Восстановить энергию"),
            localizationEntry("developer.action.clear_boosts", "Сбросить бусты"),
            localizationEntry("developer.action.enable_ads_free", "Включить без рекламы"),
            localizationEntry("developer.action.enable_pro", "Включить Pro"),
            localizationEntry("developer.action.enable_pro_plus", "Включить Pro+"),
            localizationEntry("developer.action.disable_ads_free", "Выключить без рекламы"),
            localizationEntry("developer.action.disable_pro", "Выключить Pro"),
            localizationEntry("developer.action.disable_pro_plus", "Выключить Pro+"),
            localizationEntry("developer.membership.ads", "Реклама"),
            localizationEntry("developer.membership.pro", "Pro"),
            localizationEntry("developer.bot_lab.title", "Лаборатория бота"),
            localizationEntry("developer.bot_lab.subtitle", "Песочница для проверки логики бота и дуэлей."),
            localizationEntry("developer.user_data.title", "Данные пользователя"),
            localizationEntry("developer.user_data.subtitle", "Открыть локальный снимок пользователя и состояние доступов."),
            localizationEntry("developer.user_data.close", "Закрыть"),
            localizationEntry("developer.user_data.player", "Игрок"),
            localizationEntry("developer.user_data.player_id", "ID игрока"),
            localizationEntry("developer.user_data.install_id", "ID установки"),
            localizationEntry("developer.user_data.auth", "Аутентификация"),
            localizationEntry("developer.user_data.guest", "Гость"),
            localizationEntry("developer.user_data.online", "Онлайн"),
            localizationEntry("developer.user_data.locale", "Локаль"),
            localizationEntry("developer.user_data.region", "Регион"),
            localizationEntry("developer.user_data.cloud_revision", "Ревизия облака"),
            localizationEntry("developer.user_data.google_play", "Google Play"),
            localizationEntry("developer.user_data.coins", "Монеты"),
            localizationEntry("developer.user_data.energy", "Энергия"),
            localizationEntry("developer.user_data.energy_refill", "Восстановление энергии"),
            localizationEntry("developer.user_data.minutes", "{value} мин."),
            localizationEntry("developer.user_data.matches_played", "Сыграно матчей"),
            localizationEntry("developer.user_data.matches_won", "Выиграно матчей"),
            localizationEntry("developer.user_data.campaign_level", "Уровень компании"),
            localizationEntry("developer.user_data.campaign_rating", "Рейтинг компании"),
            localizationEntry("developer.user_data.hints", "Подсказки"),
            localizationEntry("developer.user_data.boosts", "Бустеры"),
            localizationEntry("developer.user_data.ads_disabled", "Реклама отключена"),
            localizationEntry("developer.user_data.ad_free", "Без рекламы"),
            localizationEntry("developer.user_data.pro", "Pro"),
            localizationEntry("developer.user_data.pro_plus", "Pro+"),
            localizationEntry("developer.user_data.pve", "PvE"),
            localizationEntry("developer.user_data.pvp", "PvP"),
            localizationEntry("developer.user_data.company", "Компания"),
            localizationEntry("developer.user_data.match_result", "Победы: {wins} / Поражения: {losses}"),
            localizationEntry("developer.user_data.campaign_rows", "Строки компании"),
            localizationEntry("developer.user_data.identity_links", "Связи идентичности"),
            localizationEntry("developer.user_data.relationships", "Отношения"),
            localizationEntry("developer.user_data.rooms", "Комнаты"),
            localizationEntry("developer.user_data.matches", "Матчи"),
            localizationEntry("developer.user_data.sync_queue", "Очередь синхронизации"),
            localizationEntry("developer.bot_lab.back", "Назад"),
            localizationEntry("developer.bot_lab.description", "Экран разработчика для проверки бота. Задайте секрет и сравните число ходов для каждой сложности."),
            localizationEntry("developer.bot_lab.secret", "Секрет (пусто — автоматически)"),
            localizationEntry("developer.bot_lab.length", "Длина"),
            localizationEntry("developer.bot_lab.runs", "Запуски"),
            localizationEntry("developer.bot_lab.allow_duplicates", "Разрешить повторяющиеся цифры"),
            localizationEntry("developer.bot_lab.forbid_adjacent", "Запретить соседние повторы"),
            localizationEntry("developer.bot_lab.forbid_triple", "Запретить тройные повторы"),
            localizationEntry("developer.bot_lab.behavior", "Модель поведения"),
            localizationEntry("developer.bot_lab.error.code_length", "Длина кода должна быть от 4 до 20."),
            localizationEntry("developer.bot_lab.error.secret_length", "Секрет должен содержать ровно {value} цифр."),
            localizationEntry("developer.bot_lab.error.secret_rules", "Секрет не соответствует активным правилам."),
            localizationEntry("developer.bot_lab.running", "Выполнение…"),
            localizationEntry("developer.bot_lab.run", "Запустить проверку"),
            localizationEntry("developer.bot_lab.report", "Отчёт"),
            localizationEntry("developer.bot_lab.report.code_length", "Длина кода: {value}"),
            localizationEntry("developer.bot_lab.report.allow_duplicates", "Повторы разрешены: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_adjacent", "Соседние повторы запрещены: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_triple", "Тройные повторы запрещены: {value}"),
            localizationEntry("developer.bot_lab.report.behavior", "Поведение: {value}"),
            localizationEntry("developer.bot_lab.report.wins", "Победы: {wins}/{samples} ({rate}%)"),
            localizationEntry("developer.bot_lab.report.average_turns", "Среднее число ходов: {value}"),
            localizationEntry("developer.bot_lab.report.best_worst", "Лучший / худший: {best} / {worst}"),
            localizationEntry("developer.bot_lab.report.target_pace", "Целевой темп: {value} ходов"),
            localizationEntry("developer.bot_lab.report.secrets", "Секреты: {value}"),
            localizationEntry("social.description", "В этом разделе будут друзья, приглашения и статус в сети."),
            localizationEntry("social.friends.subtitle", "Приглашайте игроков и управляйте списком"),
            localizationEntry("social.online.subtitle", "Готовьте онлайн-комнаты и активность в реальном времени"),
            localizationEntry("social.next_steps", "Следующие шаги для онлайна"),
            localizationEntry("social.next_steps.google_play", "Вход через Google Play"),
            localizationEntry("social.next_steps.cloud_sync", "Синхронизация прогресса в облаке"),
            localizationEntry("social.next_steps.friends_pvp", "Друзья, приглашения и PvP-комнаты"),
            localizationEntry("company.scene.stars", "Звёзды: {current} / {required}"),
            localizationEntry("company.scene.locked", "Заработайте больше звёзд, чтобы открыть следующую главу."),
            localizationEntry("company.scene.unlocked", "Следующая глава уже открыта."),
            localizationEntry("company.scene.history", "История"),
            localizationEntry("company.scene.history.subtitle", "Пройденные уровни"),
            localizationEntry("company.scene.energy", "Энергия"),
            localizationEntry("company.scene.current", "Текущий"),
            localizationEntry("company.scene.best", "Лучший рейтинг"),
            localizationEntry("company.scene.no_energy", "Нет энергии"),
            localizationEntry("company.scene.locked_level", "Уровень заблокирован"),
            localizationEntry("company.scene.level", "Уровень {value}"),
            localizationEntry("company.history.title", "История"),
            localizationEntry("company.history.empty", "Здесь появятся пройденные уровни."),
            localizationEntry("company.action.close", "Закрыть"),
            localizationEntry("company.dialog.exit_title", "Выйти из прохождения компании?"),
            localizationEntry("company.dialog.exit_text", "Прогресс текущей попытки будет потерян."),
            localizationEntry("company.dialog.exit_confirm", "Выйти"),
            localizationEntry("company.dialog.stay", "Остаться"),
            localizationEntry("company.dialog.complete_title", "Уровень пройден"),
            localizationEntry("company.dialog.failed_title", "Уровень не пройден"),
            localizationEntry("company.dialog.level", "Уровень {value}"),
            localizationEntry("company.dialog.rating", "Рейтинг: {value}/10"),
            localizationEntry("company.dialog.stars", "Звёзды: {value}"),
        ),
    )

    val en = localizationCatalog(
        name = "secondary.en",
        entries = listOf(
            localizationEntry("shop.title", "Shop"),
            localizationEntry("shop.hints", "Hints and boosts"),
            localizationEntry("shop.hints.subtitle", "6 helper types for matches and campaign runs"),
            localizationEntry("shop.premium", "Subscriptions and purchases"),
            localizationEntry("shop.premium.subtitle", "Ad-free, Pro and Pro+ access"),
            localizationEntry("shop.rewarded.title", "Ad reward"),
            localizationEntry("shop.rewarded.coins", "Watch an ad and receive 20 coins."),
            localizationEntry("shop.rewarded.watch", "Watch ad"),
            localizationEntry("shop.item.open_position", "Hint: open position"),
            localizationEntry("shop.item.check_digit", "Hint: check digit"),
            localizationEntry("shop.item.check_position", "Hint: check position"),
            localizationEntry("shop.item.extra_moves", "Boost: extra moves"),
            localizationEntry("shop.item.extra_time", "Boost: extra time"),
            localizationEntry("shop.item.energy", "Company energy +1"),
            localizationEntry("shop.product.remove_ads", "Remove ads"),
            localizationEntry("shop.product.remove_ads.desc", "One-time purchase. Removes banner ads and rare post-match ads."),
            localizationEntry("shop.product.pro", "Pro subscription"),
            localizationEntry("shop.product.pro.desc", "Auto table mode + no banner and no post-match ads."),
            localizationEntry("shop.product.pro_plus", "Pro+ subscription"),
            localizationEntry("shop.product.pro_plus.desc", "Everything in Pro + infinite hints and full ad removal."),
            localizationEntry("shop.buy", "Buy"),
            localizationEntry("shop.subscribe", "Subscribe"),
            localizationEntry("shop.owned", "Owned"),
            localizationEntry("shop.active", "Active"),
            localizationEntry("shop.price", "{price} coins"),
            localizationEntry("shop.premium.unlocked", "Unlocked"),
            localizationEntry("shop.premium.access", "Premium access"),
            localizationEntry("company.title", "Company"),
            localizationEntry("company.placeholder", "Solo progression, milestones and curated levels."),
            localizationEntry("company.list", "Company Levels"),
            localizationEntry("profile.title", "Profile"),
            localizationEntry("profile.account", "Account"),
            localizationEntry("profile.player", "Player"),
            localizationEntry("profile.progress", "Progress"),
            localizationEntry("profile.membership", "Purchase status"),
            localizationEntry("profile.campaign_level", "Unlocked level"),
            localizationEntry("profile.campaign_rating", "Total company rating"),
            localizationEntry("profile.google_play.connected", "Google Play is connected. Progress can be synced."),
            localizationEntry("profile.google_play.disconnected", "Google Play is not connected. Progress is local only."),
            localizationEntry("profile.google_play.sign_in", "Sign in with Google Play"),
            localizationEntry("profile.google_play.sign_out", "Sign out of Google Play"),
            localizationEntry("profile.google_play.title", "Google Play"),
            localizationEntry("profile.google_play.guest", "Guest mode"),
            localizationEntry("profile.ads_removed.yes", "Ads are removed permanently."),
            localizationEntry("profile.ads_removed.no", "The one-time ad removal purchase is not active."),
            localizationEntry("profile.pro.yes", "Pro subscription is active."),
            localizationEntry("profile.pro.no", "Pro subscription is not active."),
            localizationEntry("profile.pro_plus.yes", "Pro+ subscription is active."),
            localizationEntry("profile.pro_plus.no", "Pro+ subscription is not active."),
            localizationEntry("profile.developer", "Developer"),
            localizationEntry("profile.developer.add_coins", "+100 coins"),
            localizationEntry("profile.membership.ads", "Ads"),
            localizationEntry("profile.membership.pro", "Pro"),
            localizationEntry("profile.membership.pro_plus", "Pro+"),
            localizationEntry("profile.membership.active", "Active"),
            localizationEntry("profile.membership.locked", "Locked"),
            localizationEntry("profile.match_stats", "Match stats"),
            localizationEntry("profile.match_stats.pve", "PvE"),
            localizationEntry("profile.match_stats.pvp", "PvP"),
            localizationEntry("profile.match_stats.result", "W {wins} / L {losses}"),
            localizationEntry("settings.title", "Settings"),
            localizationEntry("settings.description", "Use this panel for language and shell system settings."),
            localizationEntry("settings.language", "Language"),
            localizationEntry("settings.language.ru", "Russian"),
            localizationEntry("settings.language.en", "English"),
            localizationEntry("settings.language.selector", "Select language"),
            localizationEntry("settings.developer", "Developer tools"),
            localizationEntry("developer.title", "Developer tools"),
            localizationEntry("developer.description", "Internal screen for debug resources, entitlements and bot diagnostics."),
            localizationEntry("developer.section.resources", "Resources"),
            localizationEntry("developer.section.membership", "Entitlements"),
            localizationEntry("developer.action.add_coins", "+100 coins"),
            localizationEntry("developer.action.add_helpers", "+3 helpers"),
            localizationEntry("developer.action.refill_energy", "Refill energy"),
            localizationEntry("developer.action.clear_boosts", "Clear boosts"),
            localizationEntry("developer.action.enable_ads_free", "Enable ad-free"),
            localizationEntry("developer.action.enable_pro", "Enable Pro"),
            localizationEntry("developer.action.enable_pro_plus", "Enable Pro+"),
            localizationEntry("developer.action.disable_ads_free", "Disable ad-free"),
            localizationEntry("developer.action.disable_pro", "Disable Pro"),
            localizationEntry("developer.action.disable_pro_plus", "Disable Pro+"),
            localizationEntry("developer.membership.ads", "Ads"),
            localizationEntry("developer.membership.pro", "Pro"),
            localizationEntry("developer.bot_lab.title", "Bot Lab"),
            localizationEntry("developer.bot_lab.subtitle", "Open the bot sandbox and debug duel logic."),
            localizationEntry("developer.user_data.title", "User Data"),
            localizationEntry("developer.user_data.subtitle", "Open the full local user snapshot and entitlement state."),
            localizationEntry("developer.user_data.close", "Close"),
            localizationEntry("developer.user_data.player", "Player"),
            localizationEntry("developer.user_data.player_id", "Player ID"),
            localizationEntry("developer.user_data.install_id", "Install ID"),
            localizationEntry("developer.user_data.auth", "Auth"),
            localizationEntry("developer.user_data.guest", "Guest"),
            localizationEntry("developer.user_data.online", "Online"),
            localizationEntry("developer.user_data.locale", "Locale"),
            localizationEntry("developer.user_data.region", "Region"),
            localizationEntry("developer.user_data.cloud_revision", "Cloud Rev"),
            localizationEntry("developer.user_data.google_play", "Google Play"),
            localizationEntry("developer.user_data.coins", "Coins"),
            localizationEntry("developer.user_data.energy", "Energy"),
            localizationEntry("developer.user_data.energy_refill", "Energy Refill"),
            localizationEntry("developer.user_data.minutes", "{value} min"),
            localizationEntry("developer.user_data.matches_played", "Matches Played"),
            localizationEntry("developer.user_data.matches_won", "Matches Won"),
            localizationEntry("developer.user_data.campaign_level", "Campaign Level"),
            localizationEntry("developer.user_data.campaign_rating", "Campaign Rating"),
            localizationEntry("developer.user_data.hints", "Hints"),
            localizationEntry("developer.user_data.boosts", "Boosts"),
            localizationEntry("developer.user_data.ads_disabled", "Ads Disabled"),
            localizationEntry("developer.user_data.ad_free", "Ad Free"),
            localizationEntry("developer.user_data.pro", "Pro"),
            localizationEntry("developer.user_data.pro_plus", "Pro+"),
            localizationEntry("developer.user_data.pve", "PvE"),
            localizationEntry("developer.user_data.pvp", "PvP"),
            localizationEntry("developer.user_data.company", "Company"),
            localizationEntry("developer.user_data.match_result", "W {wins} / L {losses}"),
            localizationEntry("developer.user_data.campaign_rows", "Campaign Rows"),
            localizationEntry("developer.user_data.identity_links", "Identity Links"),
            localizationEntry("developer.user_data.relationships", "Relationships"),
            localizationEntry("developer.user_data.rooms", "Rooms"),
            localizationEntry("developer.user_data.matches", "Matches"),
            localizationEntry("developer.user_data.sync_queue", "Sync Queue"),
            localizationEntry("developer.bot_lab.back", "Back"),
            localizationEntry("developer.bot_lab.description", "Developer screen for bot checks. Fix one secret and compare how many turns each difficulty needs."),
            localizationEntry("developer.bot_lab.secret", "Secret (empty = auto)"),
            localizationEntry("developer.bot_lab.length", "Length"),
            localizationEntry("developer.bot_lab.runs", "Runs"),
            localizationEntry("developer.bot_lab.allow_duplicates", "Allow duplicate digits"),
            localizationEntry("developer.bot_lab.forbid_adjacent", "Forbid adjacent duplicates"),
            localizationEntry("developer.bot_lab.forbid_triple", "Forbid triple duplicates"),
            localizationEntry("developer.bot_lab.behavior", "Behavior model"),
            localizationEntry("developer.bot_lab.error.code_length", "Code length must be between 4 and 20."),
            localizationEntry("developer.bot_lab.error.secret_length", "Secret must contain exactly {value} digits."),
            localizationEntry("developer.bot_lab.error.secret_rules", "Secret does not match the active rules."),
            localizationEntry("developer.bot_lab.running", "Running…"),
            localizationEntry("developer.bot_lab.run", "Run benchmark"),
            localizationEntry("developer.bot_lab.report", "Report"),
            localizationEntry("developer.bot_lab.report.code_length", "Code length: {value}"),
            localizationEntry("developer.bot_lab.report.allow_duplicates", "Allow duplicates: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_adjacent", "Forbid adjacent duplicates: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_triple", "Forbid triple duplicates: {value}"),
            localizationEntry("developer.bot_lab.report.behavior", "Behavior: {value}"),
            localizationEntry("developer.bot_lab.report.wins", "Wins: {wins}/{samples} ({rate}%)"),
            localizationEntry("developer.bot_lab.report.average_turns", "Average turns: {value}"),
            localizationEntry("developer.bot_lab.report.best_worst", "Best / worst: {best} / {worst}"),
            localizationEntry("developer.bot_lab.report.target_pace", "Target pace: {value} turns"),
            localizationEntry("developer.bot_lab.report.secrets", "Secrets: {value}"),
            localizationEntry("social.description", "This section will handle friends, invites and online presence."),
            localizationEntry("social.friends.subtitle", "Invite players and manage your list"),
            localizationEntry("social.online.subtitle", "Prepare online rooms and live activity"),
            localizationEntry("social.next_steps", "Next online steps"),
            localizationEntry("social.next_steps.google_play", "Google Play sign-in"),
            localizationEntry("social.next_steps.cloud_sync", "Cloud progress sync"),
            localizationEntry("social.next_steps.friends_pvp", "Friends, invites and PvP rooms"),
            localizationEntry("company.scene.stars", "Stars: {current} / {required}"),
            localizationEntry("company.scene.locked", "Earn more stars to unlock the next chapter."),
            localizationEntry("company.scene.unlocked", "The next chapter is already unlocked."),
            localizationEntry("company.scene.history", "History"),
            localizationEntry("company.scene.history.subtitle", "Completed levels"),
            localizationEntry("company.scene.energy", "Energy"),
            localizationEntry("company.scene.current", "Current"),
            localizationEntry("company.scene.best", "Best rating"),
            localizationEntry("company.scene.no_energy", "No energy"),
            localizationEntry("company.scene.locked_level", "Level locked"),
            localizationEntry("company.scene.level", "Level {value}"),
            localizationEntry("company.history.title", "History"),
            localizationEntry("company.history.empty", "Completed levels will appear here."),
            localizationEntry("company.action.close", "Close"),
            localizationEntry("company.dialog.exit_title", "Exit campaign run?"),
            localizationEntry("company.dialog.exit_text", "Progress in the current attempt will be lost."),
            localizationEntry("company.dialog.exit_confirm", "Exit"),
            localizationEntry("company.dialog.stay", "Stay"),
            localizationEntry("company.dialog.complete_title", "Level complete"),
            localizationEntry("company.dialog.failed_title", "Level failed"),
            localizationEntry("company.dialog.level", "Level {value}"),
            localizationEntry("company.dialog.rating", "Rating: {value}/10"),
            localizationEntry("company.dialog.stars", "Stars: {value}"),
        ),
    )
}
