package com.mirkori.inplacex.platform.localization

private class MapLocalizationProvider(
    private val values: Map<String, String>
) : LocalizationProvider {
    override fun text(key: String): String = values[key] ?: key
}

object StaticLocalizationProvider {
    fun forLanguage(language: AppLanguage): LocalizationProvider {
        return when (language) {
            AppLanguage.RU -> MapLocalizationProvider(ruPack)
            AppLanguage.EN -> MapLocalizationProvider(enPack)
        }
    }

    private val ruPack = mapOf(
        "top.back" to "Назад",
        "top.settings" to "Настройки",
        "top.energy" to "Энергия",
        "top.coins" to "Монеты",

        "section.home.title" to "Главная",
        "section.home.short" to "Главная",
        "section.home.reserve" to "Нижний резерв: баннер / акция / быстрый вход",
        "section.social.title" to "Друзья / Онлайн",
        "section.social.short" to "Друзья",
        "section.social.reserve" to "Нижний резерв: реклама / комната / онлайн-событие",
        "section.company.title" to "Компания",
        "section.company.short" to "Компания",
        "section.company.reserve" to "Нижний резерв: компания / прогресс / цели",
        "section.shop.title" to "Магазин",
        "section.shop.short" to "Магазин",
        "section.shop.reserve" to "Нижний резерв: оффер / подписка / акция",
        "section.profile.title" to "Профиль",
        "section.profile.short" to "Профиль",
        "section.profile.reserve" to "Нижний резерв: premium / статус / сервис",

        "mode.pve.title" to "Гонка",
        "mode.pve.subtitle" to "Раскройте код быстрее, чем закончатся ходы",
        "mode.pvp.title" to "Дуэль",
        "mode.pvp.subtitle" to "Сразитесь с соперником ход за ходом",

        "home.title" to "InplaceX",
        "home.subtitle" to "Логика, скорость и точный расчёт",
        "home.code_length" to "{count} цифр",
        "home.duel.kind" to "Против бота",
        "home.company.teaser" to "Кампания, награды и запас энергии находятся во вкладке «Компания».",
        "social.title" to "Друзья / Онлайн",
        "social.friends" to "Друзья",
        "social.online" to "Онлайн",

        "shop.title" to "Магазин",
        "shop.hints" to "Подсказки и бустеры",
        "shop.premium" to "Подписки и покупки",
        "shop.rewarded.title" to "Бонус за рекламу",
        "shop.rewarded.coins" to "Посмотрите рекламу и получите 20 монет.",
        "shop.rewarded.watch" to "Смотреть рекламу",
        "shop.item.open_position" to "Подсказка: открыть позицию",
        "shop.item.check_digit" to "Подсказка: проверить цифру",
        "shop.item.check_position" to "Подсказка: проверить позицию",
        "shop.item.extra_moves" to "Бустер: дополнительные ходы",
        "shop.item.extra_time" to "Бустер: дополнительное время",
        "shop.item.energy" to "Энергия компании +1",
        "shop.product.remove_ads" to "Отключить рекламу",
        "shop.product.remove_ads.desc" to "Разовая покупка. Убирает баннер и редкие рекламные показы после матча.",
        "shop.product.pro" to "Подписка Pro",
        "shop.product.pro.desc" to "Авто режим таблицы + без баннера и постматчевой рекламы.",
        "shop.product.pro_plus" to "Подписка Pro+",
        "shop.product.pro_plus.desc" to "Все бонусы Pro + бесконечные подсказки и полное отключение рекламы.",
        "shop.buy" to "Купить",
        "shop.subscribe" to "Подписаться",
        "shop.owned" to "Куплено",
        "shop.active" to "Активно",

        "company.title" to "Компания",
        "company.placeholder" to "Одиночное прохождение, прогресс и серия уровней.",
        "company.list" to "Уровни компании",

        "profile.title" to "Профиль",
        "profile.account" to "Аккаунт",
        "profile.player" to "Игрок",
        "profile.progress" to "Прогресс",
        "profile.membership" to "Статус покупок",
        "profile.campaign_level" to "Открытый уровень",
        "profile.campaign_rating" to "Общий рейтинг компании",
        "profile.google_play.connected" to "Google Play подключен. Прогресс можно синхронизировать.",
        "profile.google_play.disconnected" to "Google Play не подключен. Прогресс хранится только локально.",
        "profile.google_play.sign_in" to "Войти через Google Play",
        "profile.google_play.sign_out" to "Выйти из Google Play",
        "profile.ads_removed.yes" to "Реклама отключена навсегда.",
        "profile.ads_removed.no" to "Разовая покупка отключения рекламы не активна.",
        "profile.pro.yes" to "Подписка Pro активна.",
        "profile.pro.no" to "Подписка Pro не активна.",
        "profile.pro_plus.yes" to "Подписка Pro+ активна.",
        "profile.pro_plus.no" to "Подписка Pro+ не активна.",
        "profile.developer" to "Разработчик",
        "profile.developer.add_coins" to "+100 монет",

        "settings.title" to "Настройки",
        "settings.description" to "Здесь настраиваются язык и системные параметры оболочки.",
        "settings.language" to "Язык",
        "settings.language.ru" to "Русский",
        "settings.language.en" to "Английский",
        "settings.language.selector" to "Выбор языка",
        "settings.developer" to "Режим разработчика",

        "developer.title" to "Режим разработчика",
        "developer.description" to "Внутренний экран для отладки ресурсов, подписок и поведения бота.",
        "developer.section.resources" to "Ресурсы",
        "developer.section.membership" to "Подписки и доступы",
        "developer.action.add_coins" to "+100 монет",
        "developer.action.add_helpers" to "+3 помощи",
        "developer.action.refill_energy" to "Восстановить энергию",
        "developer.action.clear_boosts" to "Сбросить бусты",
        "developer.action.enable_ads_free" to "Включить без рекламы",
        "developer.action.enable_pro" to "Включить Pro",
        "developer.action.enable_pro_plus" to "Включить Pro+",
        "developer.bot_lab.title" to "Лаборатория бота",
        "developer.bot_lab.subtitle" to "Песочница для проверки логики бота и дуэлей.",

        "company.scene.stars" to "Stars: {current} / {required}",
        "company.scene.locked" to "Earn more stars to unlock the next chapter.",
        "company.scene.unlocked" to "The next chapter is already unlocked.",
        "company.scene.history" to "History",
        "company.scene.history.subtitle" to "Completed levels",
        "company.scene.energy" to "Energy",
        "company.scene.current" to "Current",
        "company.scene.best" to "Best rating",
        "company.scene.no_energy" to "No energy",
        "company.scene.locked_level" to "Level locked",
        "company.scene.level" to "Level {value}",
        "company.history.title" to "History",
        "company.history.empty" to "Completed levels will appear here.",
        "company.action.close" to "Close",
        "company.dialog.exit_title" to "Exit campaign run?",
        "company.dialog.exit_text" to "Progress in the current attempt will be lost.",
        "company.dialog.exit_confirm" to "Exit",
        "company.dialog.stay" to "Stay",
        "company.dialog.complete_title" to "Level complete",
        "company.dialog.failed_title" to "Level failed",
        "company.dialog.level" to "Level {value}",
        "company.dialog.rating" to "Rating: {value}/10",
        "company.dialog.stars" to "Stars: {value}",

        "game.status.default" to "Введите комбинацию или отметьте таблицу",
        "game.status.time_over" to "Время вышло",
        "game.status.no_hints" to "Подсказки этого типа закончились",
        "game.status.watch_ad_for_hint" to "Можно посмотреть рекламу и получить бонусную подсказку",
        "game.status.select_table_cell" to "Выберите клетку таблицы для проверки позиции",
        "game.status.select_slot" to "Выберите слот в комбинации, чтобы открыть позицию",
        "game.status.select_digit" to "Выберите цифру на клавиатуре ввода",
        "game.status.hint_unavailable" to "Подсказка недоступна",
        "game.status.hint_match_here" to "Подсказка: цифра {digit} стоит в этой позиции",
        "game.status.hint_no_match_here" to "Подсказка: цифра {digit} не стоит в этой позиции",
        "game.status.hint_position_contains" to "Подсказка: в позиции {position} стоит цифра {digit}",
        "game.status.hint_digit_count" to "Цифра {digit} встречается {count} раз",
        "game.status.hint_applied" to "Подсказка применена",
        "game.status.no_move_boosts" to "Бустеры ходов закончились",
        "game.status.moves_added" to "Добавлено ходов: {count}",
        "game.status.no_time_boosts" to "Бустеры времени закончились",
        "game.status.time_added" to "Добавлено времени: {minutes} мин",
        "game.status.new_secret" to "Сгенерировано новое число",
        "game.status.wait_opponent" to "Подождите ход соперника",
        "game.status.enter_digits" to "Введите {count} цифр",
        "game.status.attempt_not_accepted" to "Попытка не принята",
        "game.status.solved_new_secret" to "Угадано. Сгенерировано новое число",
        "game.status.no_attempts_left" to "Попытки закончились",
        "game.status.matches" to "Совпадений: {count}",
        "game.status.auto_enabled" to "Авто режим включен",
        "game.status.auto_disabled" to "Авто режим выключен",
        "game.status.auto_requires_pro" to "Авто режим входит в подписку Pro",
        "game.status.bonus_hint_ready" to "Бонусная подсказка готова к использованию",
        "game.status.bonus_not_granted" to "Бонус не получен",

        "game.dialog.bonus_hint.title" to "Получить бонусную подсказку?",
        "game.dialog.bonus_hint.text" to "Посмотреть рекламу и получить 1 использование выбранной подсказки.",
        "game.dialog.hint.title" to "Подсказка",
        "game.action.watch" to "Смотреть",
        "game.action.cancel" to "Отмена",
        "game.action.ok" to "Ок",

        "game.top.moves" to "Ходы",
        "game.top.total" to "Общее",
        "game.top.turn" to "Ход",
        "game.attempts.title" to "Попытки",
        "game.attempts.empty" to "Здесь будут отображаться ваши попытки угадать",
        "game.hint.open_position" to "Открыть позицию",
        "game.hint.check_digit" to "Проверить цифру",
        "game.hint.check_position" to "Проверить позицию",
        "game.boost.add_moves" to "Добавить ходы",
        "game.boost.add_time" to "Добавить время",
        "game.boost.moves_short" to "ход.",
        "game.auto_mode" to "Авто режим",
        "game.auto_mode.pro" to "PRO",
        "game.auto_mode.auto" to "Авто",
        "game.auto_mode.manual" to "Ручной",
        "game.tool.no" to "Нет",
        "game.tool.maybe" to "Возможно",
        "game.tool.yes" to "Точно",
        "game.combination" to "Комбинация",
        "game.action.reset" to "Сброс",
        "game.action.confirm" to "Подтвердить",
        "game.action.delete" to "Стереть",
        "game.ad_slot" to "Рекламный слот игрового экрана",
        "game.debug.secret" to "Секрет: {value}",
        "game.debug.hints" to "Подсказки: {open} / {digit} / {position}",
        "game.debug.boosts" to "Бустеры: {moves} / {time}",
        "game.debug.add_hints" to "+3 подсказки",
    )

    private val enPack = mapOf(
        "top.back" to "Back",
        "top.settings" to "Settings",
        "top.energy" to "Energy",
        "top.coins" to "Coins",

        "section.home.title" to "Home",
        "section.home.short" to "Home",
        "section.home.reserve" to "Bottom reserve: banner / promo / quick entry",
        "section.social.title" to "Friends / Online",
        "section.social.short" to "Friends",
        "section.social.reserve" to "Bottom reserve: ad / room / online event",
        "section.company.title" to "Company",
        "section.company.short" to "Company",
        "section.company.reserve" to "Bottom reserve: company / progress / goals",
        "section.shop.title" to "Shop",
        "section.shop.short" to "Shop",
        "section.shop.reserve" to "Bottom reserve: offer / subscription / promo",
        "section.profile.title" to "Profile",
        "section.profile.short" to "Profile",
        "section.profile.reserve" to "Bottom reserve: premium / status / service",

        "mode.pve.title" to "Race",
        "mode.pve.subtitle" to "Crack the code before your moves run out",
        "mode.pvp.title" to "Duel",
        "mode.pvp.subtitle" to "Challenge an opponent turn by turn",

        "home.title" to "InplaceX",
        "home.subtitle" to "Logic, speed, and precise calculation",
        "home.code_length" to "{count} digits",
        "home.duel.kind" to "Bot duel",
        "home.company.teaser" to "Campaign, rewards, and energy live in the Company tab.",
        "social.title" to "Friends / Online",
        "social.friends" to "Friends",
        "social.online" to "Online",

        "shop.title" to "Shop",
        "shop.hints" to "Hints and boosts",
        "shop.premium" to "Subscriptions and purchases",
        "shop.rewarded.title" to "Ad reward",
        "shop.rewarded.coins" to "Watch an ad and receive 20 coins.",
        "shop.rewarded.watch" to "Watch ad",
        "shop.item.open_position" to "Hint: open position",
        "shop.item.check_digit" to "Hint: check digit",
        "shop.item.check_position" to "Hint: check position",
        "shop.item.extra_moves" to "Boost: extra moves",
        "shop.item.extra_time" to "Boost: extra time",
        "shop.item.energy" to "Company energy +1",
        "shop.product.remove_ads" to "Remove ads",
        "shop.product.remove_ads.desc" to "One-time purchase. Removes banner ads and rare post-match ads.",
        "shop.product.pro" to "Pro subscription",
        "shop.product.pro.desc" to "Auto table mode + no banner and no post-match ads.",
        "shop.product.pro_plus" to "Pro+ subscription",
        "shop.product.pro_plus.desc" to "Everything in Pro + infinite hints and full ad removal.",
        "shop.buy" to "Buy",
        "shop.subscribe" to "Subscribe",
        "shop.owned" to "Owned",
        "shop.active" to "Active",

        "company.title" to "Company",
        "company.placeholder" to "Solo progression, milestones and curated levels.",
        "company.list" to "Company Levels",

        "profile.title" to "Profile",
        "profile.account" to "Account",
        "profile.player" to "Player",
        "profile.progress" to "Progress",
        "profile.membership" to "Purchase status",
        "profile.campaign_level" to "Unlocked level",
        "profile.campaign_rating" to "Total company rating",
        "profile.google_play.connected" to "Google Play is connected. Progress can be synced.",
        "profile.google_play.disconnected" to "Google Play is not connected. Progress is local only.",
        "profile.google_play.sign_in" to "Sign in with Google Play",
        "profile.google_play.sign_out" to "Sign out of Google Play",
        "profile.ads_removed.yes" to "Ads are removed permanently.",
        "profile.ads_removed.no" to "The one-time ad removal purchase is not active.",
        "profile.pro.yes" to "Pro subscription is active.",
        "profile.pro.no" to "Pro subscription is not active.",
        "profile.pro_plus.yes" to "Pro+ subscription is active.",
        "profile.pro_plus.no" to "Pro+ subscription is not active.",
        "profile.developer" to "Developer",
        "profile.developer.add_coins" to "+100 coins",

        "settings.title" to "Settings",
        "settings.description" to "Use this panel for language and shell system settings.",
        "settings.language" to "Language",
        "settings.language.ru" to "Russian",
        "settings.language.en" to "English",
        "settings.language.selector" to "Select language",
        "settings.developer" to "Developer tools",

        "developer.title" to "Developer tools",
        "developer.description" to "Internal screen for debug resources, entitlements and bot diagnostics.",
        "developer.section.resources" to "Resources",
        "developer.section.membership" to "Entitlements",
        "developer.action.add_coins" to "+100 coins",
        "developer.action.add_helpers" to "+3 helpers",
        "developer.action.refill_energy" to "Refill energy",
        "developer.action.clear_boosts" to "Clear boosts",
        "developer.action.enable_ads_free" to "Enable ad-free",
        "developer.action.enable_pro" to "Enable Pro",
        "developer.action.enable_pro_plus" to "Enable Pro+",
        "developer.bot_lab.title" to "Bot Lab",
        "developer.bot_lab.subtitle" to "Open the bot sandbox and debug duel logic.",

        "company.scene.stars" to "Stars: {current} / {required}",
        "company.scene.locked" to "Earn more stars to unlock the next chapter.",
        "company.scene.unlocked" to "The next chapter is already unlocked.",
        "company.scene.history" to "History",
        "company.scene.history.subtitle" to "Completed levels",
        "company.scene.energy" to "Energy",
        "company.scene.current" to "Current",
        "company.scene.best" to "Best rating",
        "company.scene.no_energy" to "No energy",
        "company.scene.locked_level" to "Level locked",
        "company.scene.level" to "Level {value}",
        "company.history.title" to "History",
        "company.history.empty" to "Completed levels will appear here.",
        "company.action.close" to "Close",
        "company.dialog.exit_title" to "Exit campaign run?",
        "company.dialog.exit_text" to "Progress in the current attempt will be lost.",
        "company.dialog.exit_confirm" to "Exit",
        "company.dialog.stay" to "Stay",
        "company.dialog.complete_title" to "Level complete",
        "company.dialog.failed_title" to "Level failed",
        "company.dialog.level" to "Level {value}",
        "company.dialog.rating" to "Rating: {value}/10",
        "company.dialog.stars" to "Stars: {value}",

        "game.status.default" to "Enter a combination or mark the table",
        "game.status.time_over" to "Time is over",
        "game.status.no_hints" to "No hints of this type left",
        "game.status.watch_ad_for_hint" to "Watch an ad to get a bonus hint",
        "game.status.select_table_cell" to "Select a table cell to check position",
        "game.status.select_slot" to "Select a combination slot to open",
        "game.status.select_digit" to "Select a digit on the input pad",
        "game.status.hint_unavailable" to "Hint is unavailable",
        "game.status.hint_match_here" to "Hint: digit {digit} is correct here",
        "game.status.hint_no_match_here" to "Hint: digit {digit} is not correct here",
        "game.status.hint_position_contains" to "Hint: position {position} contains {digit}",
        "game.status.hint_digit_count" to "Digit {digit} appears {count} time(s)",
        "game.status.hint_applied" to "Hint applied",
        "game.status.no_move_boosts" to "No move boosts left",
        "game.status.moves_added" to "Added moves: {count}",
        "game.status.no_time_boosts" to "No time boosts left",
        "game.status.time_added" to "Added time: {minutes} min",
        "game.status.new_secret" to "A new secret has been generated",
        "game.status.wait_opponent" to "Wait for opponent turn",
        "game.status.enter_digits" to "Enter {count} digits",
        "game.status.attempt_not_accepted" to "Attempt not accepted",
        "game.status.solved_new_secret" to "Solved. A new secret has been generated",
        "game.status.no_attempts_left" to "No attempts left",
        "game.status.matches" to "Matches: {count}",
        "game.status.auto_enabled" to "Auto mode enabled",
        "game.status.auto_disabled" to "Auto mode disabled",
        "game.status.auto_requires_pro" to "Auto mode is part of Pro",
        "game.status.bonus_hint_ready" to "Bonus hint is ready",
        "game.status.bonus_not_granted" to "Bonus was not granted",

        "game.dialog.bonus_hint.title" to "Get a bonus hint?",
        "game.dialog.bonus_hint.text" to "Watch an ad to receive 1 use of the selected hint.",
        "game.dialog.hint.title" to "Hint",
        "game.action.watch" to "Watch",
        "game.action.cancel" to "Cancel",
        "game.action.ok" to "OK",

        "game.top.moves" to "Moves",
        "game.top.total" to "Total",
        "game.top.turn" to "Turn",
        "game.attempts.title" to "Attempts",
        "game.attempts.empty" to "Your attempts to guess the secret will appear here",
        "game.hint.open_position" to "Open position",
        "game.hint.check_digit" to "Check digit",
        "game.hint.check_position" to "Check position",
        "game.boost.add_moves" to "Add moves",
        "game.boost.add_time" to "Add time",
        "game.boost.moves_short" to "moves",
        "game.auto_mode" to "Auto mode",
        "game.auto_mode.pro" to "PRO",
        "game.auto_mode.auto" to "Auto",
        "game.auto_mode.manual" to "Manual",
        "game.tool.no" to "No",
        "game.tool.maybe" to "Maybe",
        "game.tool.yes" to "Yes",
        "game.combination" to "Combination",
        "game.action.reset" to "Reset",
        "game.action.confirm" to "Confirm",
        "game.action.delete" to "Delete",
        "game.ad_slot" to "Game screen ad slot",
        "game.debug.secret" to "Secret: {value}",
        "game.debug.hints" to "Hints: {open} / {digit} / {position}",
        "game.debug.boosts" to "Boosts: {moves} / {time}",
        "game.debug.add_hints" to "+3 hints",
    )
}
