#!/usr/bin/env python3
"""Build the generated Project State current summary."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import documentation_impact_checker
from project_paths import task_manager_dir


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


GENERATED_AT_RE = re.compile(r"Status: generated by `scripts/agent_control/project_state_summary_builder\.py` at `([^`]+)`\.")


def extract_generated_at(content: str) -> str | None:
    match = GENERATED_AT_RE.search(content)
    return match.group(1) if match else None


def normalize_generated_at(content: str) -> str:
    return GENERATED_AT_RE.sub(
        "Status: generated by `scripts/agent_control/project_state_summary_builder.py` at `<generated-at>`.",
        content,
    )


def load_json(path: Path, default: dict[str, Any] | None = None) -> dict[str, Any]:
    if not path.is_file():
        return dict(default or {})
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON object expected: {path}")
    return data


def task_summary(queue: dict[str, Any]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for task in queue.get("tasks") or []:
        if not isinstance(task, dict):
            continue
        status = str(task.get("status") or "unknown")
        counts[status] = counts.get(status, 0) + 1
    return dict(sorted(counts.items()))


def markdown(project_root: Path, *, generated_at: str) -> str:
    version = load_json(project_root / "PROJECT_VERSION.json", {})
    project_map = load_json(project_root / "PROJECT_MAP.json", {})
    task_manager = task_manager_dir(project_root)
    queue = load_json(task_manager / "task_queue.json", {"tasks": []})
    bridge = load_json(task_manager / "automation_bridge_state.json", {})
    convergence = bridge.get("convergence") if isinstance(bridge.get("convergence"), dict) else {}
    hygiene = load_json(task_manager / "repository_hygiene_state.json", {})
    hygiene_cleanup = hygiene.get("branch_cleanup") if isinstance(hygiene.get("branch_cleanup"), dict) else {}
    hygiene_logical_counts = (
        hygiene_cleanup.get("logical_counts") if isinstance(hygiene_cleanup.get("logical_counts"), dict) else {}
    )
    documentation = documentation_impact_checker.build_report(
        project_root,
        project_id=str(version.get("project_id") or ""),
    )
    documentation_summary = (
        documentation.get("classification_summary")
        if isinstance(documentation.get("classification_summary"), dict)
        else {}
    )
    tasks = queue.get("tasks") if isinstance(queue.get("tasks"), list) else []
    worker_ready = [
        str(task.get("id"))
        for task in tasks
        if isinstance(task, dict) and task.get("worker_ready") is True and str(task.get("status") or "") in {"planned", "worker_ready", "needs_stronger_agent"}
    ]
    lines = [
        "# Current Project Summary",
        "",
        "Purpose: fast start context for chats, Codex sessions, automation runners and reviewers.",
        "",
        f"Status: generated by `scripts/agent_control/project_state_summary_builder.py` at `{generated_at}`.",
        "The timestamp records the last committed material summary; validator content comparison determines freshness.",
        "",
        "## Project",
        "",
        f"- Project id: `{version.get('project_id', 'ai-project-agent')}`",
        f"- Branch role: `{version.get('branch_role', 'unknown')}`",
        f"- Product version: `{version.get('product_version', 'unknown')}`",
        f"- Development source of truth: `origin/develop`",
        f"- Stable release branch: `origin/release/main`",
        "",
        "## Start Order",
        "",
        "1. `.agent/START_HERE.md`",
        "2. `AiStudio/Project_state/indexes/current_summary.md`",
        "3. `PROJECT_VERSION.json`",
        "4. `docs/AISTUDIO_INDEX.md`",
        "5. `PROJECT_MAP.json` and `PROJECT_MAP.md`",
        "6. `AiStudio/Task_manager/task_queue.json`",
        "7. Role-specific rules under `agent-core/.agent/roles/`",
        "",
        "## Current Navigation Surfaces",
        "",
        "- Main index: `docs/AISTUDIO_INDEX.md`",
        "- Project state hub: `AiStudio/Project_state/README.md`",
        "- Project map authority: `PROJECT_MAP.json`",
        "- Project map human view: `PROJECT_MAP.md`",
        "- Project memory workspace: `AiStudio/ProjectMemory/`",
        "- Artifact Discovery: `docs/agent/discovery/README.md`",
        "- Change Intake: `docs/agent/change-intake/README.md`",
        "- Repository Hygiene: `docs/automation/REPOSITORY_HYGIENE_CYCLE.md`",
        "",
        "## Current Module Areas",
        "",
    ]
    for module in project_map.get("modules") or []:
        if not isinstance(module, dict):
            continue
        module_id = module.get("module_id")
        area = module.get("area")
        paths = ", ".join(str(item) for item in module.get("primary_paths") or [])
        lines.append(f"- `{module_id}`: {area} ({paths})")
    lines.extend([
        "",
        "## Task State",
        "",
        f"- Queue tasks: `{len(tasks)}`",
        f"- Worker-ready active tasks: `{len(worker_ready)}`",
        f"- Status counts: `{json.dumps(task_summary(queue), sort_keys=True)}`",
        "",
        "## Documentation, Code And Tasks",
        "",
        f"- Convergence status: `{convergence.get('status', 'not_recorded')}`",
        f"- Convergence blocking count: `{convergence.get('blocking_count', 'not_recorded')}`",
        f"- Classified documents: `{documentation_summary.get('total', 0)}`",
        f"- Actionable documentation orphans: `{documentation_summary.get('actionable_orphan_count', 0)}`",
        f"- Documentation manifest errors: `{len(documentation.get('errors') or [])}`",
        f"- Artifact Discovery findings in last bridge cycle: `{((convergence.get('scan') or {}).get('artifact_findings', 'not_recorded'))}`",
        f"- Task owner gaps in last bridge cycle: `{((convergence.get('cleanup') or {}).get('owner_gap_count', 'not_recorded'))}`",
        f"- Repository hygiene state: `{'healthy' if hygiene.get('ok') is True else 'needs_repair' if hygiene.get('ok') is False else 'not_recorded'}`",
        f"- Open PRs in last hygiene cycle: `{hygiene.get('open_pr_count', 'not_recorded')}`",
        f"- Logical worker salvage branches: `{hygiene_logical_counts.get('dirty_worker_candidate', 'not_recorded')}`",
        f"- Immediate branch delete/archive candidates: `{(int(hygiene_logical_counts.get('merged_safe_delete') or 0) + int(hygiene_logical_counts.get('archive_candidate') or 0)) if hygiene else 'not_recorded'}`",
        "",
        "## Active Foundations Already Present",
        "",
        "- Project State Hub foundation exists under `AiStudio/Project_state/`.",
        "- Project Map machine-readable authority exists at `PROJECT_MAP.json`.",
        "- Project Rules update pipeline exists at `scripts/agent_control/project_rules_update_pipeline.py`.",
        "- Second Brain runtime exists at `scripts/agent_control/project_memory_engine.py` with tenant/project isolation, reviewed intake and scoped retrieval.",
        "- Second Brain activation is dry-run-first at `scripts/agent_control/second_brain_activation.py`; live host apply still requires owner approval.",
        "- Project Memory compatibility workspace exists under `AiStudio/ProjectMemory/` when initialized.",
        "- Artifact Discovery exists for scanner/classifier/router/normalizer flows.",
        "- Repository Hygiene exists for PR topology, guarded branch cleanup and worker salvage routing.",
        "",
        "## Important Boundaries",
        "",
        "- Project State Hub does not replace Task Manager.",
        "- Project State Hub does not replace Project Map.",
        "- Change Intake does not execute work or merge PRs.",
        "- Artifact Discovery findings are evidence, not approval.",
        "- Dispatcher, Integrator and Finalizer remain decision/execution departments.",
        "- Do not work from chat memory alone.",
        "",
        "## Immediate Navigation Gaps",
        "",
        "- Any non-zero Artifact Discovery or documentation orphan count must be handled through an existing queue row or explicit owner route.",
        "- Second Brain customer-facing activation still requires per-project adoption, operator review UX and production authorization tests.",
        "- File-level Project Map ownership and dependency edges still need progressive backfill.",
        "",
        "## When Unsure",
        "",
        "If this summary conflicts with GitHub, `PROJECT_VERSION.json`, Task Manager or current integration reports, treat this file as stale and route to Integrator/Dispatcher for navigation repair.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def build_report(project_root: Path, output: Path | None = None, *, apply: bool = False) -> dict[str, Any]:
    project_root = project_root.resolve()
    generated_at = utc_now()
    target = project_root / "AiStudio" / "Project_state" / "indexes" / "current_summary.md"
    content = markdown(project_root, generated_at=generated_at)
    previous = target.read_text(encoding="utf-8") if target.is_file() else ""
    stale = normalize_generated_at(previous) != normalize_generated_at(content)
    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
    if apply:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        stabilized = markdown(project_root, generated_at=generated_at)
        if normalize_generated_at(stabilized) != normalize_generated_at(content):
            content = stabilized
            target.write_text(content, encoding="utf-8")
            if output:
                output.write_text(content, encoding="utf-8")
    return {
        "schema_version": "1.0",
        "mode": "project_state_summary_builder",
        "project_root": str(project_root),
        "generated_at": generated_at,
        "target": str(target),
        "output": str(output) if output else None,
        "apply": apply,
        "mutated_target": apply,
        "stale": stale,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    report = build_report(Path(args.project_root), output=args.output, apply=bool(args.apply))
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(report["target"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
