CREATE TABLE players (
    id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE save_heads (
    player_id VARCHAR(64) PRIMARY KEY REFERENCES players(id),
    latest_revision BIGINT NOT NULL CHECK (latest_revision >= 0),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE save_revisions (
    player_id VARCHAR(64) NOT NULL REFERENCES players(id),
    revision BIGINT NOT NULL CHECK (revision > 0),
    payload_json TEXT NOT NULL,
    schema_version INTEGER NOT NULL CHECK (schema_version > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, revision)
);

CREATE TABLE matchmaking_tickets (
    id VARCHAR(64) PRIMARY KEY,
    player_id VARCHAR(64) NOT NULL REFERENCES players(id),
    mode VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE duel_sessions (
    id VARCHAR(64) PRIMARY KEY,
    mode VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    config_json TEXT NOT NULL,
    version BIGINT NOT NULL CHECK (version >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE duel_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES duel_sessions(id),
    client_command_id VARCHAR(128) NOT NULL,
    version BIGINT NOT NULL CHECK (version > 0),
    command_type VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (session_id, client_command_id),
    UNIQUE (session_id, version)
);

CREATE TABLE duel_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES duel_sessions(id),
    event_type VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_matchmaking_tickets_player_status ON matchmaking_tickets(player_id, status);
CREATE INDEX idx_duel_events_session_id ON duel_events(session_id, id);
