package com.mirkori.inplacex.platform.localization

internal fun variantLocalizationCatalogs(language: AppLanguage): List<LocalizationCatalog> =
    listOf(
        when (language) {
            AppLanguage.RU -> BuildVariantLocalizationCatalog.ru
            AppLanguage.EN -> BuildVariantLocalizationCatalog.en
        },
    )

private object BuildVariantLocalizationCatalog {
    val ru = localizationCatalog(
        name = "build-variant.ru",
        entries = listOf(
            localizationEntry("game.debug.secret", "Секрет: {value}"),
            localizationEntry("game.debug.hints", "Подсказки: {open} / {digit} / {position}"),
            localizationEntry("game.debug.boosts", "Бустеры: {moves} / {time}"),
            localizationEntry("game.debug.add_hints", "+3 подсказки"),
            localizationEntry("game.debug_screen.title", "Тестовый экран игры"),
            localizationEntry("game.debug_screen.status", "Статус: {phase}"),
            localizationEntry("game.debug_screen.attempts_left", "Осталось попыток: {count}"),
            localizationEntry("game.debug_screen.attempts_made", "Попыток сделано: {count}"),
            localizationEntry("game.debug_screen.debug", "DEBUG"),
            localizationEntry("game.debug_screen.enter_digits", "Введите {count} цифр"),
            localizationEntry("game.debug_screen.action.check", "Проверить"),
            localizationEntry("game.debug_screen.action.restart", "Новая игра"),
            localizationEntry("game.debug_screen.history_title", "История попыток"),
            localizationEntry("game.debug_screen.matches", "Совпадений: {count}"),
            localizationEntry("game.debug_screen.phase.not_started", "Не начата"),
            localizationEntry("game.debug_screen.phase.active", "Активна"),
            localizationEntry("game.debug_screen.phase.won", "Победа"),
            localizationEntry("game.debug_screen.phase.lost", "Поражение"),
            localizationEntry("profile.developer", "Разработчик"),
            localizationEntry("profile.developer.add_coins", "+100 монет"),
            localizationEntry("settings.developer", "Режим разработчика"),
            localizationEntry("developer.title", "Режим разработчика"),
            localizationEntry("developer.description", "Внутренний экран для отладки ресурсов, подписок и поведения бота."),
            localizationEntry("developer.section.resources", "Ресурсы"),
            localizationEntry("developer.section.membership", "Подписки и доступы"),
            localizationEntry("developer.action.add_coins", "+100 монет"),
            localizationEntry("developer.action.add_helpers", "+3 помощи"),
            localizationEntry("developer.action.refill_energy", "Восстановить энергию"),
            localizationEntry("developer.action.clear_boosts", "Сбросить бусты"),
            localizationEntry("developer.action.enable_ads_free", "Включить без рекламы"),
            localizationEntry("developer.action.enable_pro", "Включить Pro"),
            localizationEntry("developer.action.enable_pro_plus", "Включить Pro+"),
            localizationEntry("developer.action.disable_ads_free", "Выключить без рекламы"),
            localizationEntry("developer.action.disable_pro", "Выключить Pro"),
            localizationEntry("developer.action.disable_pro_plus", "Выключить Pro+"),
            localizationEntry("developer.membership.ads", "Реклама"),
            localizationEntry("developer.membership.pro", "Pro"),
            localizationEntry("developer.bot_lab.title", "Лаборатория бота"),
            localizationEntry("developer.bot_lab.subtitle", "Песочница для проверки логики бота и дуэлей."),
            localizationEntry("developer.user_data.title", "Данные пользователя"),
            localizationEntry("developer.user_data.subtitle", "Открыть локальный снимок пользователя и состояние доступов."),
            localizationEntry("developer.user_data.close", "Закрыть"),
            localizationEntry("developer.user_data.player", "Игрок"),
            localizationEntry("developer.user_data.player_id", "ID игрока"),
            localizationEntry("developer.user_data.install_id", "ID установки"),
            localizationEntry("developer.user_data.auth", "Аутентификация"),
            localizationEntry("developer.user_data.guest", "Гость"),
            localizationEntry("developer.user_data.online", "Онлайн"),
            localizationEntry("developer.user_data.locale", "Локаль"),
            localizationEntry("developer.user_data.region", "Регион"),
            localizationEntry("developer.user_data.cloud_revision", "Ревизия облака"),
            localizationEntry("developer.user_data.google_play", "Google Play"),
            localizationEntry("developer.user_data.coins", "Монеты"),
            localizationEntry("developer.user_data.energy", "Энергия"),
            localizationEntry("developer.user_data.energy_refill", "Восстановление энергии"),
            localizationEntry("developer.user_data.minutes", "{value} мин."),
            localizationEntry("developer.user_data.matches_played", "Сыграно матчей"),
            localizationEntry("developer.user_data.matches_won", "Выиграно матчей"),
            localizationEntry("developer.user_data.campaign_level", "Уровень компании"),
            localizationEntry("developer.user_data.campaign_rating", "Рейтинг компании"),
            localizationEntry("developer.user_data.hints", "Подсказки"),
            localizationEntry("developer.user_data.boosts", "Бустеры"),
            localizationEntry("developer.user_data.ads_disabled", "Реклама отключена"),
            localizationEntry("developer.user_data.ad_free", "Без рекламы"),
            localizationEntry("developer.user_data.pro", "Pro"),
            localizationEntry("developer.user_data.pro_plus", "Pro+"),
            localizationEntry("developer.user_data.pve", "PvE"),
            localizationEntry("developer.user_data.pvp", "PvP"),
            localizationEntry("developer.user_data.company", "Компания"),
            localizationEntry("developer.user_data.match_result", "Победы: {wins} / Поражения: {losses}"),
            localizationEntry("developer.user_data.campaign_rows", "Строки компании"),
            localizationEntry("developer.user_data.identity_links", "Связи идентичности"),
            localizationEntry("developer.user_data.relationships", "Отношения"),
            localizationEntry("developer.user_data.rooms", "Комнаты"),
            localizationEntry("developer.user_data.matches", "Матчи"),
            localizationEntry("developer.user_data.sync_queue", "Очередь синхронизации"),
            localizationEntry("developer.bot_lab.back", "Назад"),
            localizationEntry("developer.bot_lab.description", "Экран разработчика для проверки бота. Задайте секрет и сравните число ходов для каждой сложности."),
            localizationEntry("developer.bot_lab.secret", "Секрет (пусто — автоматически)"),
            localizationEntry("developer.bot_lab.length", "Длина"),
            localizationEntry("developer.bot_lab.runs", "Запуски"),
            localizationEntry("developer.bot_lab.allow_duplicates", "Разрешить повторяющиеся цифры"),
            localizationEntry("developer.bot_lab.forbid_adjacent", "Запретить соседние повторы"),
            localizationEntry("developer.bot_lab.forbid_triple", "Запретить тройные повторы"),
            localizationEntry("developer.bot_lab.behavior", "Модель поведения"),
            localizationEntry("developer.bot_lab.error.code_length", "Длина кода должна быть от 4 до 20."),
            localizationEntry("developer.bot_lab.error.secret_length", "Секрет должен содержать ровно {value} цифр."),
            localizationEntry("developer.bot_lab.error.secret_rules", "Секрет не соответствует активным правилам."),
            localizationEntry("developer.bot_lab.running", "Выполнение…"),
            localizationEntry("developer.bot_lab.run", "Запустить проверку"),
            localizationEntry("developer.bot_lab.report", "Отчёт"),
            localizationEntry("developer.bot_lab.report.code_length", "Длина кода: {value}"),
            localizationEntry("developer.bot_lab.report.allow_duplicates", "Повторы разрешены: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_adjacent", "Соседние повторы запрещены: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_triple", "Тройные повторы запрещены: {value}"),
            localizationEntry("developer.bot_lab.report.behavior", "Поведение: {value}"),
            localizationEntry("developer.bot_lab.report.wins", "Победы: {wins}/{samples} ({rate}%)"),
            localizationEntry("developer.bot_lab.report.average_turns", "Среднее число ходов: {value}"),
            localizationEntry("developer.bot_lab.report.best_worst", "Лучший / худший: {best} / {worst}"),
            localizationEntry("developer.bot_lab.report.target_pace", "Целевой темп: {value} ходов"),
            localizationEntry("developer.bot_lab.report.secrets", "Секреты: {value}"),
        ),
    )

    val en = localizationCatalog(
        name = "build-variant.en",
        entries = listOf(
            localizationEntry("game.debug.secret", "Secret: {value}"),
            localizationEntry("game.debug.hints", "Hints: {open} / {digit} / {position}"),
            localizationEntry("game.debug.boosts", "Boosts: {moves} / {time}"),
            localizationEntry("game.debug.add_hints", "+3 hints"),
            localizationEntry("game.debug_screen.title", "Game test screen"),
            localizationEntry("game.debug_screen.status", "Status: {phase}"),
            localizationEntry("game.debug_screen.attempts_left", "Attempts left: {count}"),
            localizationEntry("game.debug_screen.attempts_made", "Attempts made: {count}"),
            localizationEntry("game.debug_screen.debug", "DEBUG"),
            localizationEntry("game.debug_screen.enter_digits", "Enter {count} digits"),
            localizationEntry("game.debug_screen.action.check", "Check"),
            localizationEntry("game.debug_screen.action.restart", "New game"),
            localizationEntry("game.debug_screen.history_title", "Attempt history"),
            localizationEntry("game.debug_screen.matches", "Matches: {count}"),
            localizationEntry("game.debug_screen.phase.not_started", "Not started"),
            localizationEntry("game.debug_screen.phase.active", "Active"),
            localizationEntry("game.debug_screen.phase.won", "Victory"),
            localizationEntry("game.debug_screen.phase.lost", "Defeat"),
            localizationEntry("profile.developer", "Developer"),
            localizationEntry("profile.developer.add_coins", "+100 coins"),
            localizationEntry("settings.developer", "Developer tools"),
            localizationEntry("developer.title", "Developer tools"),
            localizationEntry("developer.description", "Internal screen for debug resources, entitlements and bot diagnostics."),
            localizationEntry("developer.section.resources", "Resources"),
            localizationEntry("developer.section.membership", "Entitlements"),
            localizationEntry("developer.action.add_coins", "+100 coins"),
            localizationEntry("developer.action.add_helpers", "+3 helpers"),
            localizationEntry("developer.action.refill_energy", "Refill energy"),
            localizationEntry("developer.action.clear_boosts", "Clear boosts"),
            localizationEntry("developer.action.enable_ads_free", "Enable ad-free"),
            localizationEntry("developer.action.enable_pro", "Enable Pro"),
            localizationEntry("developer.action.enable_pro_plus", "Enable Pro+"),
            localizationEntry("developer.action.disable_ads_free", "Disable ad-free"),
            localizationEntry("developer.action.disable_pro", "Disable Pro"),
            localizationEntry("developer.action.disable_pro_plus", "Disable Pro+"),
            localizationEntry("developer.membership.ads", "Ads"),
            localizationEntry("developer.membership.pro", "Pro"),
            localizationEntry("developer.bot_lab.title", "Bot Lab"),
            localizationEntry("developer.bot_lab.subtitle", "Open the bot sandbox and debug duel logic."),
            localizationEntry("developer.user_data.title", "User Data"),
            localizationEntry("developer.user_data.subtitle", "Open the full local user snapshot and entitlement state."),
            localizationEntry("developer.user_data.close", "Close"),
            localizationEntry("developer.user_data.player", "Player"),
            localizationEntry("developer.user_data.player_id", "Player ID"),
            localizationEntry("developer.user_data.install_id", "Install ID"),
            localizationEntry("developer.user_data.auth", "Auth"),
            localizationEntry("developer.user_data.guest", "Guest"),
            localizationEntry("developer.user_data.online", "Online"),
            localizationEntry("developer.user_data.locale", "Locale"),
            localizationEntry("developer.user_data.region", "Region"),
            localizationEntry("developer.user_data.cloud_revision", "Cloud Rev"),
            localizationEntry("developer.user_data.google_play", "Google Play"),
            localizationEntry("developer.user_data.coins", "Coins"),
            localizationEntry("developer.user_data.energy", "Energy"),
            localizationEntry("developer.user_data.energy_refill", "Energy Refill"),
            localizationEntry("developer.user_data.minutes", "{value} min"),
            localizationEntry("developer.user_data.matches_played", "Matches Played"),
            localizationEntry("developer.user_data.matches_won", "Matches Won"),
            localizationEntry("developer.user_data.campaign_level", "Campaign Level"),
            localizationEntry("developer.user_data.campaign_rating", "Campaign Rating"),
            localizationEntry("developer.user_data.hints", "Hints"),
            localizationEntry("developer.user_data.boosts", "Boosts"),
            localizationEntry("developer.user_data.ads_disabled", "Ads Disabled"),
            localizationEntry("developer.user_data.ad_free", "Ad Free"),
            localizationEntry("developer.user_data.pro", "Pro"),
            localizationEntry("developer.user_data.pro_plus", "Pro+"),
            localizationEntry("developer.user_data.pve", "PvE"),
            localizationEntry("developer.user_data.pvp", "PvP"),
            localizationEntry("developer.user_data.company", "Company"),
            localizationEntry("developer.user_data.match_result", "W {wins} / L {losses}"),
            localizationEntry("developer.user_data.campaign_rows", "Campaign Rows"),
            localizationEntry("developer.user_data.identity_links", "Identity Links"),
            localizationEntry("developer.user_data.relationships", "Relationships"),
            localizationEntry("developer.user_data.rooms", "Rooms"),
            localizationEntry("developer.user_data.matches", "Matches"),
            localizationEntry("developer.user_data.sync_queue", "Sync Queue"),
            localizationEntry("developer.bot_lab.back", "Back"),
            localizationEntry("developer.bot_lab.description", "Developer screen for bot checks. Fix one secret and compare how many turns each difficulty needs."),
            localizationEntry("developer.bot_lab.secret", "Secret (empty = auto)"),
            localizationEntry("developer.bot_lab.length", "Length"),
            localizationEntry("developer.bot_lab.runs", "Runs"),
            localizationEntry("developer.bot_lab.allow_duplicates", "Allow duplicate digits"),
            localizationEntry("developer.bot_lab.forbid_adjacent", "Forbid adjacent duplicates"),
            localizationEntry("developer.bot_lab.forbid_triple", "Forbid triple duplicates"),
            localizationEntry("developer.bot_lab.behavior", "Behavior model"),
            localizationEntry("developer.bot_lab.error.code_length", "Code length must be between 4 and 20."),
            localizationEntry("developer.bot_lab.error.secret_length", "Secret must contain exactly {value} digits."),
            localizationEntry("developer.bot_lab.error.secret_rules", "Secret does not match the active rules."),
            localizationEntry("developer.bot_lab.running", "Running…"),
            localizationEntry("developer.bot_lab.run", "Run benchmark"),
            localizationEntry("developer.bot_lab.report", "Report"),
            localizationEntry("developer.bot_lab.report.code_length", "Code length: {value}"),
            localizationEntry("developer.bot_lab.report.allow_duplicates", "Allow duplicates: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_adjacent", "Forbid adjacent duplicates: {value}"),
            localizationEntry("developer.bot_lab.report.forbid_triple", "Forbid triple duplicates: {value}"),
            localizationEntry("developer.bot_lab.report.behavior", "Behavior: {value}"),
            localizationEntry("developer.bot_lab.report.wins", "Wins: {wins}/{samples} ({rate}%)"),
            localizationEntry("developer.bot_lab.report.average_turns", "Average turns: {value}"),
            localizationEntry("developer.bot_lab.report.best_worst", "Best / worst: {best} / {worst}"),
            localizationEntry("developer.bot_lab.report.target_pace", "Target pace: {value} turns"),
            localizationEntry("developer.bot_lab.report.secrets", "Secrets: {value}"),
        ),
    )
}
